### ISSUE TITLE
Adding Label field in the Clusterfuzz form fill

### ISSUE THREAD

**Issue by anshuman-goel** [google/clusterfuzz#1001]
To get due credit for the bugs found from Microsoft Fuzzing, a label needs to be added while submitting the job in Clusterfuzz. It can be on the form where one can add the label and it auto adds on the bug created by the Clusterfuzz.

**Comment by oliverchang** [comment]
Re-opening as we need to relax the restrictions here to let non-privileged users add this in ClusterFuzz. However, we can't do this in places like OSS-Fuzz since labels there control deadlines.
