### ISSUE TITLE
How to use clusterfuzz using proxy server

### ISSUE THREAD

**Issue by terenceli** [google/clusterfuzz#1010]
Hi all,
I want to run clusterfuzz in local server, but it downloads a lot of files from google sites.
As you know, some country blocks the google. So I tried to use proxy server.
But it can't work, always has '502 server drop connection' error.

Any idea for how can I use clusterfuzz?

BYW: any roadmap for support proxy server?

Thanks

**Comment by mbarbella-chromium** [comment]
There's some discussion of similar issues in #334. It might be worth looking through some of the workarounds proposed there to see if any help you. We don't have immediate plans to fix this, but we are aware of the issue and hope to get to it at some point (though I'm closing this particular issue out as a duplicate).
