### ISSUE TITLE
Bot in production deploy shows Online, even though Gone

### ISSUE THREAD

**Issue by SecurityInsanity** [google/clusterfuzz#1013]
Having deployed a series of bots using the production deploy in GCP. These were using the default configurations.

After running some jobs we decided we wanted to bump up the bot sizes in GCE. So we changed the machineType to: `n2-standard-2`, provisioned. It didn't take, and then we realized we also needed to bump: `version` to 2. So we did, reprovisioned, and then noticed the bots updated. 

However, one of the bots still shows in the bot list "running" a task. However, the bot is long gone, and not shown in the GCP Console.

**Comment by inferno-chromium** [comment]
We give like 8 hrs for a bot to respond and come back (in case stuck with weird things).

```
def _get_alive_cutoff():
  """Get the time before which we consider bots to be dead."""
  seconds_to_wait_for_dead_bot = (
      tasks.TASK_LEASE_SECONDS + tasks.TASK_COMPLETION_BUFFER +
      data_types.HEARTBEAT_WAIT_INTERVAL)
  alive_cutoff = utils.utcnow() - datetime.timedelta(
      seconds=seconds_to_wait_for_dead_bot)
  return alive_cutoff
```
After 8 hrs, it will start showing as DEAD on UI

For continuously running system, dead bot will be removed from list after 15 days.

**Comment by SecurityInsanity** [comment]
Ah okay, it’s only been 11 days.  Thanks! I’ll close this for now and just reopen if it still shows after 15 days.

**Comment by inferno-chromium** [comment]
Just fyi, this is the code that does the 15 days periodic cleanup in cleanup cron 

```
def cleanup_unused_heartbeats():
  """Clean up unused heartbeat entities."""
  cutoff_time = utils.utcnow() - datetime.timedelta(
      days=UNUSED_HEARTBEAT_THRESHOLD)
  unused_heartbeats = ndb_utils.get_all_from_query(
      data_types.Heartbeat.query(
          data_types.Heartbeat.last_beat_time < cutoff_time),
      keys_only=True)

  ndb.delete_multi(unused_heartbeats)
```
