### ISSUE TITLE
Add a strategy for UBSAN_OPTIONS=halt_on_error=0

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1019]
For projects that upload ASan+UBSan builds, we need a way to suppress UBSan crashes. This can be achieved by setting up `UBSAN_OPTIONS=halt_on_error=0` (assuming the project is built with `-fsanitize-recover=undefined`).

I don't think this feature should be a strategy in our typical sense, e.g. we don't need to put it in stats, but it has to rely on some random decision and we need to make sure the sanitizer options minimization would handle this well.

**Comment by inferno-chromium** [comment]
This is done.
https://github.com/google/clusterfuzz/pull/1257
https://github.com/google/clusterfuzz/pull/1260
https://github.com/google/clusterfuzz/pull/1270
https://github.com/google/clusterfuzz/pull/1276
