### ISSUE TITLE
Reading file using the with open syntax.

### ISSUE THREAD

**Issue by farziengineer** [google/clusterfuzz#1029]
https://github.com/google/clusterfuzz/blob/47a8f2d4d2b3938fdb58f559a4adb1da5998da89/src/python/base/utils.py#L312-L314

https://github.com/google/clusterfuzz/blob/47a8f2d4d2b3938fdb58f559a4adb1da5998da89/src/python/base/utils.py#L447-L449

https://github.com/google/clusterfuzz/blob/47a8f2d4d2b3938fdb58f559a4adb1da5998da89/src/python/base/utils.py#L568-L570

https://github.com/google/clusterfuzz/blob/47a8f2d4d2b3938fdb58f559a4adb1da5998da89/src/python/base/utils.py#L788-L790

The above snippets can all be replaced with the following syntax

```python
with open(file_name, mode) as file_handler:
   data = file_handler.read()
```

**Comment by farziengineer** [comment]
Can I raise a PR for this?

**Comment by inferno-chromium** [comment]
Thanks for fix - https://github.com/google/clusterfuzz/pull/1030
