### ISSUE TITLE
Do not report OOMs found with an MSan build

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1043]
* MSan has the biggest memory overhead
* It doesn't provide the same memory allocation profile as ASan build may provide
* We never run MSan build as the only configuration

Due to these points I believe it should be fine to ignore OOM crashes detected under MSan. Any other opinions?

A caveat I see is that MSan build might be OOMing all the time and we need to have a way to detect this and notify the developer.

**Comment by oliverchang** [comment]
+1 to just disabling. A simple way to disable reporting for MSan would be through setting REPORT_OOMS_AND_HANGS to False in the msan jobs. @inferno-chromium WDYT?

If the MSan build is OOMing all the time, we should be reducing the weight automatically, and eventually report the issue via some other analysis pipeline like we've wanted for a long time.

**Comment by inferno-chromium** [comment]
Yes sure, sounds good in msan template. lets make sure to check current bugs, esp in google instance, don't want too much churn right now.

**Comment by inferno-chromium** [comment]
wont work since two templates here, one with REPORT_OOMS_AND_HANGS=True in libfuzzer and msan in other. might have to disable in code.
