### ISSUE TITLE
Questions for a talk on CI/CD

### ISSUE THREAD

**Issue by timfong888** [google/clusterfuzz#1062]
Hi, I am researching how to incorporate security into CI/CD pipelines for an audience of DevOps professionals. I am especially interested in talking to someone familiar with Hybrid fuzzing or symbolic execution as a way to reduce vulnerabilities. 

[http://reports-archive.adm.cs.cmu.edu/anon/2012/CMU-CS-12-116.pdf](http://reports-archive.adm.cs.cmu.edu/anon/2012/CMU-CS-12-116.pdf)

**Comment by jonathanmetzman** [comment]
I'm sure this is too late but we don't really use hybrid testing. 
We fuzz, we don't use symbolic/concolic execution. I would bet most people in industry do the same.
