### ISSUE TITLE
Don't create empty testcases for timeouts/ooms

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#1063]
When REPORT_OOMS_AND_HANGS is false, we report unreproducible empty crashes, because we see that there is a `Test unit written to...` even if the crash is not something we consider.

**Comment by Dor1s** [comment]
Thanks for noticing this, I was about to send you this example: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=17853

**Comment by oliverchang** [comment]
I think that one is a different issue, since it's unreproducible and if you look at the crash stats it's been happening for at least 2 weeks (hence why we filed).

**Comment by Dor1s** [comment]
Oh, from the issue description I somehow concluded that we wouldn't file an issue like that previously, but did file it now. Even if it's different, I guess we still prefer to ignore it for an MSan build?
