### ISSUE TITLE
PubSub Debug - local

### ISSUE THREAD

**Issue by tick-rick** [google/clusterfuzz#1068]
Env: Local deployment

I cant seem to get the bot to pick up any jobs. Jobs are successfully created.
Error log of bot only shows:
```
2019-10-01 03:08:18,336 - run_bot - INFO - Completed running platform initialization scripts.
2019-10-01 03:08:18,640 - run_bot - ERROR - Failed to get any fuzzing tasks. This should not happen.
```
I had a quick look at the src/python/google_cloud_utils/pubsub.py stuff and can see that under pull_from_subscription, the received_messages is simply empty. Unfortunately it seems that the actual server component to pubsub is a Java app (cloud-pubsub-emulator-0.1-SNAPSHOT-all.jar) where the code is not immediately available, aside from digging into this vendored binary, how should I go about debugging why jobs are not being released to the bot?

**Comment by tick-rick** [comment]
While debugging I also checked the server logs (running with --log-level=debug). Interestingly the server logs do not contain any 'requests' from the bot. I tested with the following script:
```python
# git clone https://github.com/GoogleCloudPlatform/python-docs-samples/ && \
# cd python-docs-samples/pubsub/cloud-client && \
# pip install -r requirements.txt
from google.cloud import pubsub_v1
import os

os.environ['PUBSUB_EMULATOR_HOST'] = 'localhost:9006'

subscriber = pubsub_v1.SubscriberClient()
xs = list(subscriber.list_subscriptions(subscriber.project_path("test-clusterfuzz")))

subscription_path = subscriber.subscription_path('test-clusterfuzz', 'jobs-android')
resp = subscriber.pull(subscription_path, max_messages=1)
len(resp.received_message) == 0
```

In the above, `xs` contains a list of the subscription topics, and confirms jobs-android is one (I also tried jobs-android-local-devices as topic):
```
<SNIP>...
name: "projects/test-clusterfuzz/subscriptions/jobs-android"
topic: "projects/test-clusterfuzz/topics/jobs-android"
push_config {
}
ack_deadline_seconds: 600
message_retention_duration {
  seconds: 604800
}
, name: "projects/test-clusterfuzz/subscriptions/jobs-android-local-devices"
topic: "projects/test-clusterfuzz/topics/jobs-android-local-devices"
push
<SNIP>...
``` 
Here is screenshot from jobs page
![Screenshot_2019-10-02 Job Types](https://user-images.githubusercontent.com/50384876/66008969-da2fca00-e4fb-11e9-8b4b-004aca4eb6ed.png)

**Comment by inferno-chromium** [comment]
This job's platform says Android, did you mean linux there ? Also, there is no custom binary picked for this job. Did you associate any fuzzer with this job, if not, it wont work.

**Comment by tick-rick** [comment]
@inferno-chromium hi, I just uploaded a custom binary (named encoder.so-fuzzer.zip), and im still not getting fuzzing tasks, I meant the jobs platform to be android (i am running android bot using `python butler.py run_bot --name "android" /home/user/clusterfuzz/bots/ --android-serial "192.168.XX.XX:5555"`

**Comment by inferno-chromium** [comment]
If it is libFuzzer job, you need to associate with libFuzzer fuzzer. 

https://google.github.io/clusterfuzz/setting-up-fuzzing/libfuzzer-and-afl/#creating-a-job-type
```
Next we must let ClusterFuzz know which fuzzer the job can be used with:

Navigate to the Fuzzers page.
Click “EDIT” for the desired fuzzer (afl or libFuzzer).
Click “Select/modify jobs”.
Mark the desired job.
Click “SUBMIT”.
```

**Comment by tick-rick** [comment]
@inferno-chromium OK I definitely missed that bit, I went and added 'fuzzer' to the job, still not picking up jobs, does it require a reboot after this?
![Screenshot_2019-10-02 Fuzzers](https://user-images.githubusercontent.com/50384876/66009589-8377bf80-e4fe-11e9-9e0d-85405cedb38d.png)

**Comment by tick-rick** [comment]
OK it seems to be picking it up now! it just took a few minutes to propagate!!

**Comment by inferno-chromium** [comment]
We have an issue for this autoassociation - https://github.com/google/clusterfuzz/issues/596

**Comment by tick-rick** [comment]
Awesome! thank you for your help
