### ISSUE TITLE
libFuzzer for Android support

### ISSUE THREAD

**Issue by tick-rick** [google/clusterfuzz#1071]
I am having some difficulty understanding the workflow for android bots when attempting to fuzz a native binary built for libfuzzer (which works fine manually copying using adb and running the ./fuzzer).  

Problem: The bot copies the test cases to device fine, but it does not seem to copy the custom build (which contains the fuzzer) to the device (the thing that is meant to actually fuzz)

It seems that with out of the box configuration, the resulting command line is blank, resulting in `resources/platform/android/adb -s 192.168.XX.XX:5555 ` being the run command, which results in a warning. 

I have tried by configuring `APP_LAUNCH_COMMAND` to use adb push to get the fuzzer on the target device, but this doesn't feel right? 
(`APP_LAUNCH_COMMAND = shell ip -f inet addr show eth0 | grep inet | awk '{print $2}' | sed 's|\/24|:5555|' > host && resources/platform/android/adb -s "$(cat host)" push /home/user/clusterfuzz/bots/clusterfuzz/bot/builds/libfuzzer_asan_test-clusterfuzz/custom/* /data/local/tmp/ && resources/platform/android/adb -s "$(cat host)" shell 'cd /data/local/tmp/ && chmod +x ./* && LD_LIBRARY_PATH=. ./wrap.sh ./fuzz_me_fuzzer'`)

**Comment by tick-rick** [comment]
I suspect that the set up for android job template will end up looking more like this: https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/ than the default libfuzzer one?

**Comment by inferno-chromium** [comment]
libfuzzer support for android platform is not there yet. it should come sometime in Q4. Keeping bug open till then.

**Comment by Dor1s** [comment]
yes, for Android platform only blackbox fuzzing mode is currently supported
