### ISSUE TITLE
Tagging tickets internal and open for contributors

### ISSUE THREAD

**Issue by tapaswenipathak** [google/clusterfuzz#1126]
Hey maintainers: Can tickets we tagged internal and open for contributors? Do you have a code of conduct? 

Ref: https://github.com/google/clusterfuzz/pull/1048.

**Comment by inferno-chromium** [comment]
I tried to explain more in https://github.com/google/clusterfuzz/pull/1048#issuecomment-546483014. Documentation, without understanding the code context can be hard. We will try to iterate on your future PRs and leave proper review.
