### ISSUE TITLE
Remove Go code.

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#1132]
This effort is unfortunately stalled. We should remove the code which will keep bitroting until the day we revisit this again.

**Comment by lookfwd** [comment]
40 files and 3879 lines of code.

**Comment by Dor1s** [comment]
* Removed Fuzzer Coverage cron task in https://github.com/google/clusterfuzz/pull/1372
  * minor follow up in `butler.py` in https://github.com/google/clusterfuzz/pull/1383
  * and a few other fixes not related to Go code

**Comment by oliverchang** [comment]
This was done.
