### ISSUE TITLE
Add support for go-fuzz

### ISSUE THREAD

**Issue by TheCrott** [google/clusterfuzz#1155]
Add support for go-fuzz

**Comment by inferno-chromium** [comment]
It exists already, see https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/ and https://github.com/google/clusterfuzz/blob/master/src/python/crash_analysis/stack_parsing/stack_analyzer.py#L261

**Comment by Dor1s** [comment]
For further updates on Go support you can subscribe to https://github.com/google/clusterfuzz/issues/860
