### ISSUE TITLE
Using AFL in ClusterFuzz can't work

### ISSUE THREAD

**Issue by terenceli** [google/clusterfuzz#1161]
Hello all,

I just want to try afl in clusterfuzz as the instruction page said:
https://google.github.io/clusterfuzz/setting-up-fuzzing/libfuzzer-and-afl/#afl

Howerver, 
After setup, I got following error:
root@test-virtual-machine:~/afltest# clang -fsanitize=address -fsanitize-coverage=trace-pc-guard afltest.c  FuzzingEngine.a -o afltest
root@test-virtual-machine:~/afltest# AFL_SKIP_CPUFREQ=1 ./afl-fuzz -i input -o output -m none ./afltest
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] You have 1 CPU core and 2 runnable tasks (utilization: 200%).
[*] Checking core_pattern...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'input'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...

[-] Looks like the target binary is not instrumented! The fuzzer depends on
    compile-time instrumentation to isolate interesting test cases while
    mutating the input data. For more information, and for tips on how to
    instrument binaries, please see /usr/local/share/doc/afl/README.

    When source code is not available, you may be able to leverage QEMU
    mode support. Consult the README for tips on how to enable this.
    (It is also possible to use afl-fuzz as a traditional, "dumb" fuzzer.
    For that, you can use the -n option - but expect much worse results.)

[-] PROGRAM ABORT : No instrumentation detected
         Location : check_binary(), afl-fuzz.c:6922

Some of the configuration:
root@test-virtual-machine:~/afltest# clang --version
clang version 10.0.0 (http://llvm.org/git/clang.git 3441aaff8506ac0252f9bba9d1ce117cf35906ce) (http://llvm.org/git/llvm.git 1d098622eca0db46490e2ccd05ae2bf087fb7656)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
root@test-virtual-machine:~/afltest# lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Any hints?
Thanks

**Comment by jonathanmetzman** [comment]
Thanks for this report. It still works for me with different versions of clang on my debian box.
Can you post afltest.c please?

**Comment by terenceli** [comment]
@jonathanmetzman I guess this not related with the afltest. It's just a 'hello world' test program.
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    char s[10];
    scanf("%s", s);
    printf("%s\n", s);
}

**Comment by zounathan** [comment]
@terenceli Have u solved this issue? And how?
