### ISSUE TITLE
Recurring errors before fuzzing even begins

### ISSUE THREAD

**Issue by louiscb** [google/clusterfuzz#1207]
I'm attempting to fuzz an extremely simple C program using AFL fuzzer on the Clusterfuzz application I've created which is hosted on GCP. I decided to let the program run for a couple of days as I've been told that sometimes it can take a while for the website to be updated with fuzzing results. However there has been no output in any way from the website. Instead there is this pattern of errors being produced in the activity log once a day at 9am:

```
Failed: Export entities - failed to export clusterfuzz-111111
Failed: Create dataset - has created afl_stats.
Failed: Create dataset - failed to create datasets
Failed: Create dataset - has created libFuzzer_stats.
Failed: Create dataset -  failed to create datasets
```

I've fuzzed the same exact files locally with AFL and gotten results within seconds. Not sure what to do at the moment as there is literally not output from fuzzing these files.

**Comment by inferno-chromium** [comment]
@louiscb - were you able to resolve this ? there is a bot/logs/bot.log on the actual bot.

**Comment by louiscb** [comment]
@inferno-chromium no I decided to make a different issue instead at #1209 , I tried to delete this one however I couldn't, so if you have the privileges feel free to delete this
