### ISSUE TITLE
Fix heartbleed fuzzer example to run in prod

### ISSUE THREAD

**Issue by louiscb** [google/clusterfuzz#1209]
I've attempted to fuzz some simple C programs using Clusterfuzz which i'm hosting on GCP. I wasn't able to produce any output so I decided to restart the service. Now I am receiving errors related to cron jobs that run regularly throughout the day, despite there not being any currently running fuzzing tasks. 

```
1) RuntimeError: Invalid subscription: projects/clusterfuzz-XXXXX/subscriptions/jobs-linux  
2) Task exited with exception. main
3) Failed to get any fuzzing tasks. This should not happen. get_task
4) RuntimeError: Invalid topic: projects/clusterfuzz-XXXXX/topics/jobs-linux 
```

I can successfully log in to the web application and upload a fuzzing task, however I do not get any output in testcases or the fuzzer statistics.

**Comment by inferno-chromium** [comment]
Did you associate any fuzzers with the jobs (like by going to `/fuzzers` page) ?

**Comment by louiscb** [comment]
@inferno-chromium yes I followed the documentation for the heartbleed example, I couldn't get it to work so I decided to try again with a much simpler 'hello-world' type C program which requested some memory using malloc and that still didn't produce any output.

**Comment by inferno-chromium** [comment]
Did you start any bots using instructions in https://google.github.io/clusterfuzz/production-setup/setting-up-bots/ ?

**Comment by louiscb** [comment]
@inferno-chromium I ran the default bots in `gce/clusters.yaml` which were `clusterfuzz-linux` and `clusterfuzz-linux-pre`. Checking [this](https://console.cloud.google.com/compute/instanceGroups/list) page showed both of these instances working with green ticks. I also checked that the cron job `/manage-vms` is working correctly.

**Comment by louiscb** [comment]
I edited `gce/clusters.yaml` to just deploy 2 instances of the `clusterfuzz-linux-pre` bots and deployed the changes. Once the changes were deployed I immediately got the same bot related errors with `get-task`, `main`, and `pull-from-subscribtion`. However following the `manage-vms` cron job, which as I understand deploys the bot instances, runs successfully and I can see deployed VM-instances in the compute engine which match the `cluster.yaml` configuration file.

**Comment by inferno-chromium** [comment]
Can do this again
```python butler.py deploy --config-dir=$CONFIG_DIR --prod --force```
where CONFIG_DIR points to your configuration dir.

Then checkout this page
https://console.cloud.google.com/cloudpubsub/topic/list
to see if `jobs-linux` subscription is created.

If not, try
```
python butler.py create_config --oauth-client-secrets-path=$CLIENT_SECRETS_PATH   --firebase-api-key=$FIREBASE_API_KEY --project-id=$CLOUD_PROJECT_ID $CONFIG_DIR
python butler.py deploy --config-dir=$CONFIG_DIR --prod --force
``` again, and can you capture logs for these.

I just tried the entire workflow again on a fresh project and i see the subscriptions created. Can you run everything on github/google/clusterfuzz master branch.

**Comment by louiscb** [comment]
@inferno-chromium Okay I'll give that a go. By capturing logs do you mean the output of running the commands?

**Comment by inferno-chromium** [comment]
https://pastebin.com/Ddt23gVt says the fuzzing started but you have a missing c++ lib dependency. are you using the full openssl-fuzzer-build.zip and you didn't exclude "-lstdc++" argument right

**Comment by inferno-chromium** [comment]
> @inferno-chromium Okay I'll give that a go. By capturing logs do you mean the output of running the commands?

yes.

**Comment by louiscb** [comment]
I just ran the full argument from the docs:
```
 # Build OpenSSL fuzz target for ClusterFuzz ($CXX points to clang++ binary):
$CXX -g handshake-fuzzer.cc -fsanitize=address,fuzzer openssl-1.0.1f/libssl.a \
  openssl-1.0.1f/libcrypto.a -std=c++17 -Iopenssl-1.0.1f/include/ -lstdc++fs   \
  -ldl -lstdc++ -o handshake-fuzzer
```

**Comment by inferno-chromium** [comment]
@louiscb - can you try this build - https://storage.cloud.google.com/clusterfuzz-builds/llvm/llvm-address-201911140438.zip. LLVM fuzzers should turn up bugs pretty quickly in a few hours.

We have an issue with this openssl example, which only runs locally. on production (vm), it is missing libstdc++ dependency. We will fix this example in documentation.

**Comment by inferno-chromium** [comment]
Assigning to sheriff @jonathanmetzman for removing the libstdc++ deps in this fuzzer.

**Comment by louiscb** [comment]
@inferno-chromium sorry, i'm a bit unsure of how to use the build, do you want me to use the LLVM build you linked to build a new OpenSSL fuzz target?

**Comment by inferno-chromium** [comment]
@louiscb - i meant if you want to use an example to test things end-to-end, you can use llvm build. llvm build is for llvm project, not related to openssl.

**Comment by jonathanmetzman** [comment]
I converted the heartbleed fuzzer to pure C but libstdc++ is still a dependency. It seems like clang is pulling in libstdc++ whenever libFuzzer is used which causes this error.
I'm not sure this occurs for recent version of clang where libFuzzer uses its own version of libc++
I don't think there's a solution to this problem frankly. Maybe switching to AFL?

**Comment by louiscb** [comment]
@jonathanmetzman  @inferno-chromium  Okay thanks for the responses. I still haven't been able to successfully reproduce fuzzing that I completed locally on the clusterfuzz cloud, so are there any straightforward examples/tutorials I can follow that are known to produce output on the clusterfuzz platform? This way I can identify any issues with my configuration.

**Comment by inferno-chromium** [comment]
Did you try download https://storage.cloud.google.com/clusterfuzz-builds/llvm/llvm-address-201911140438.zip and then uploading it in job definition. What was the result of running this in cloud for a few hours. Some llvm crashes should start showing up in a few hours. Can you paste some output from stackdriver, just like you did previously.

**Comment by louiscb** [comment]
Okay. Do I need to specify anything in the description? Linfuzzer and engine_asan?

**Comment by inferno-chromium** [comment]
Everything same as https://google.github.io/clusterfuzz/setting-up-fuzzing/heartbleed-example/#uploading-the-fuzzer-to-clusterfuzz
Change libfuzzer_asan_linux_openssl to something relevant like libfuzzer_asan_linux_llvm
Instead of openssl-fuzzer-build.zip, use this downloaded zip as custom build.
Let this run for a couple of hours, like 6-7 and you should start seeing crashes.

**Comment by louiscb** [comment]
Great. Thanks for walking me through it. From a front-end point of view it would be nice to see a “Uploading” message for the upload of big files, as I wasn’t sure anything was happening for about a minute after I pressed add on the job button.
