### ISSUE TITLE
Add security flag for recently added UBSan checks

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1235]
As we enabled new UBSan checks and added new signatures, some of those (maybe even all?) should be reported as non security bugs. By default CF reports "unknown" crash types as security crashes (to be extra cautious), example: https://bugs.chromium.org/p/chromium/issues/detail?id=1029052

**Comment by inferno-chromium** [comment]
Probably just need to expand list here - https://github.com/google/clusterfuzz/blob/master/src/python/crash_analysis/crash_analyzer.py#L69
