### ISSUE TITLE
Should GCP be charging money even when no jobs are running in a CF instance deployed in production?

### ISSUE THREAD

**Issue by louiscb** [google/clusterfuzz#1241]
There seems to be quite a lot of activity on the cloud dashboard for my Clusterfuzz project despite there being no jobs running or users using the service at all. In the last 4 days i've been charged $50. Is this to be expected? If it is, is there a way to only charge or put Clusterfuzz online when there is actual fuzzing to be done?

**Comment by Dor1s** [comment]
If you go to the Billing > Reports page in the cloud console, you should see the breakdown of the expenses. From the information you've provided, I would guess that you created some number of bots (in CF terms; in cloud terms these are Google Compute Engine VMs) and those are being charged no matter whether you're running fuzzing jobs or the VMs are idle.

Other than GCE VMs, you're also running ClusterFuzz App Engine instances, which include the front end, task management, etc.

I think the production instance (i.e. deployed to Google Cloud) is expected to spend up to $20 per day, at least based on our evaluations.

**Comment by louiscb** [comment]
Okay thanks I'll check out that page. So just to be clear, if the minimum charge is around $20 per day, is there no way you can "shutdown" the fuzzing service indefinitely and turn it on again when you'd like to do some fuzzing?

**Comment by Dor1s** [comment]
That's an interesting question. It is definitely possible to stop the App Engine application, but I don't know how much that would save. You should be able to stop the app either in the Web UI of the Google Cloud console or find the gcloud command in the GCP docs.

**Comment by inferno-chromium** [comment]
You can do the following:
- For compute engine, change the instance count to 0 (in clusters.yaml). Then deploy using `python butler.py deploy ......`.
- For app engine, there is way to disable your web app, you can reenable whenever you want later. Go to https://console.cloud.google.com/appengine/settings, and disable application.

That should bring your cost to 0.

**Comment by louiscb** [comment]
@inferno-chromium Thanks
