### ISSUE TITLE
afl_driver.cpp not found

### ISSUE THREAD

**Issue by andreafioraldi** [google/clusterfuzz#1244]
Hi,
I tried to execute build_afl.bash from the docs/setting-up-fuzzing and it fails to download afl_driver.cpp.
The used URL is https://cs.chromium.org/codesearch/f/chromium/src/third_party/libFuzzer/src/afl/afl_driver.cpp that seems broken (404).

```The requested URL /codesearch/f/chromium/src/third_party/libFuzzer/src/afl/afl_driver.cpp was not found on this server. That’s all we know.```

**Comment by inferno-chromium** [comment]
codesearch is currently down, should be fixed by Monday. If you want things now, can directly get the files from https://chromium.googlesource.com/chromium/src/+/master/third_party/afl/src/ (might need to download each one by one).

**Comment by Dor1s** [comment]
And codesearch seems to be back online now. Sorry for the trouble -- it's not under our control :|
