### ISSUE TITLE
README clarification around language support

### ISSUE THREAD

**Issue by rudolfolah** [google/clusterfuzz#125]
I know fuzzing is for testing inputs/outputs and is essentially language-agnostic, but it'd be nice if there's some mention of that in the README, or examples of running Clusterfuzz against code that's written in all sorts of languages (Chrome and C and C++ getting name-dropped is cool, but seeing Python or Ruby explicitly mentioned is cooler 😉 )

**Comment by jonathanmetzman** [comment]
You are right that fuzzing/ClusterFuzz is language agnostic.

But I think we did this intentionally (CC @oliverchang).

We've only used ClusterFuzz for fuzzing C/C++ (and a small amount of rust), so we're only confident that with our docs it's easy to setup fuzzing for these kinds of programs.

While we would love it if people started using ClusterFuzz for fuzzing safe programming languages (some possible use cases [here](https://news.ycombinator.com/item?id=19107825)), we don't want to give people the impression that this is something they can easily use to improve their JS/Python etc. code.

**Comment by inferno-chromium** [comment]
If you can find good memory instrumentation for those languages, it is pretty easy to extend ClusterFuzz to detect those crashes (just some parsing signatures in `stack_analyzer.py`). Infrastructure wise, you can run any program on Linux, Windows and Mac.

**Comment by co16353sidak** [comment]
Hey everyone, is this an issue I could work on possibly ? would be a good start as my first contribution here. 
/cc: @inferno-chromium @jonathanmetzman @rudolfolah

**Comment by jonathanmetzman** [comment]
I don't think so since IMO we did this intentionally.
Closing this issue, but if @inferno-chromium disagrees he can reopen.

**Comment by jonathanmetzman** [comment]
Actually, it may be worth mentioning language agnostic part to appeal to go users or users of other languages that already have fuzzer support. Frankly, I don't even know if the tooling for Ruby/Python exists for them to even be integrated into ClusterFuzz. I think for clarity's sake we should say ClusterFuzz supports C/C++ and Rust and supporting go or LLVM-based languages should be doable.
@co16353sidak I don't think this is a good first issue unfortunately.

**Comment by co16353sidak** [comment]
Okay 😞

**Comment by rudolfolah** [comment]
@jonathanmetzman  thanks for updating the FAQ, think this resolves this issue! :smile:
