### ISSUE TITLE
Add feature to skip auto-closing of bugs once verified (needed for Android bugs)

### ISSUE THREAD

**Issue by cjcole8** [google/clusterfuzz#1266]
Please remove auto close feature for Buganizer for Android bugs.  Android will be sure to close them out at the appropriate time - sometimes this means leaving the bug open after it has been fixed in mainline, but still hasn't been backported to older supported versions.  Android will be sure to close out the bugs when they have been fully resolved.  Thanks!

**Comment by inferno-chromium** [comment]
Intent is to still leave comment on verified (and add hotlist), but don't close bug status.

**Comment by cjcole8** [comment]
Correct, thanks for clarification
