### ISSUE TITLE
Add lint check in CI

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#127]

**Comment by cclauss** [comment]
Also not that linters like [flake8](https://github.com/google/clusterfuzz/pull/133#issuecomment-461764837) and pylint will raise different errors on Python 2 and Python 3 (because their Abstract Syntax Trees are different) so it would be good it the CI could do parallel lint runs on both.

**Comment by inferno-chromium** [comment]
@cclauss - right now, we only support 2.7. But Python 3 support should be coming this year.
Linting can be run right now, with `python butler.py lint`.
