### ISSUE TITLE
Default values for strategy stats in BigQuery

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1304]
We used to initialize all strategy columns with 0, but we don't seem to be doing it now, e.g.:

```sql
SELECT
  count(1)
FROM
  `libFuzzer_stats.TestcaseRun`
WHERE
  strategy_dataflow_tracing = 0
  AND timestamp >= 1576195200 /* Dec 13th 00:00 UTC */
  AND timestamp <= 1577059200 /* Dec 23th 00:00 UTC */
```

returns `0`, while

```sql
...
  strategy_dataflow_tracing = 1
...
```

makes it `2,345`, and

```sql
...
  strategy_dataflow_tracing IS NULL
...
```

makes it a large number as well.

Same for e.g. `  strategy_recommended_dict = 0` and likely other strategies.

IMO this is not a big deal, but I'd prefer a default value instead of `NULL`, as it simplifies query writing plus `NULL` works as an indicator that a particular strategy wasn't supported at all. Right now it's indistinguishable whether we do not support a strategy or it just isn't being used.

This also might be the reason why Data Studio charts aren't working //cc @mbarbella-chromium

**Comment by inferno-chromium** [comment]
Marty, can you fix this and dataflow graphs.
