### ISSUE TITLE
Android jobs treated as Linux platform jobs

### ISSUE THREAD

**Issue by audio-farm** [google/clusterfuzz#1306]
Using latest branch (v1.71). 
Set up a local clusterfuzz server and a running bot. 
Tested heartbleed example with libfuzzer and works perfectly fine.
Issue arises when creating Android jobs. 
Jobs aren't picked up by the bot. After debugging, found that clusterfuzz is not calling the android platform initialization scripts due to it detecting the job as a Linux platform job instead of an Android platform job.
Following are Job details:
libfuzzer_asan_android_test1” for the “Name”.
“ANDROID” for the “Platform”.
“libfuzzer” and “engine_asan” for the “Templates”.
CORPUS_PRUNE = True for the “Environment String”.
Appropriate fuzzer and fuzz targets were uploaded in a zip archive  under “Custom Build”.

Please advise if this is a bug or I am missing any requirements.

**Comment by inferno-chromium** [comment]
You need to call run_bot with an --android-serial argument to be considered an android bot. otherwise it runs as a linux bot.

```
usage: butler.py run_bot [-h] [--name NAME]
                         [--server-storage-path SERVER_STORAGE_PATH]
                         [--android-serial ANDROID_SERIAL]
                         directory

positional arguments:
  directory             Directory to create bot in.

optional arguments:
  -h, --help            show this help message and exit
  --name NAME           Name of the bot. (default: test-bot)
  --server-storage-path SERVER_STORAGE_PATH
                        Server storage path. (default: local/storage)
  --android-serial ANDROID_SERIAL
                        Serial number of an Android device to connect to
                        instead of running normally. (default: None)
```
