### ISSUE TITLE
Reg : support for dotNet core application testing

### ISSUE THREAD

**Issue by manojkumaraut** [google/clusterfuzz#132]
Team, 
Do this tool support for dotNet core application testing ?

**Comment by inferno-chromium** [comment]
what type of bugs are you intending to catch (any example or bug classes you can provide) ? is it for crashes under windbg instrumentation ? if yes, our code (see `stack_analyzer.py`) can parse crash stacks from windbg. we can also parse generic assert failure from output as well.

**Comment by inferno-chromium** [comment]
actually ignore last point, these will be exceptions from managed framework. ClusterFuzz can work with this, but you would need to add parsing signatures. See `stack_analyzer.py` and add parsing signatures for stack types you care about.
