### ISSUE TITLE
LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by audio-farm** [google/clusterfuzz#1332]
I'm trying to fuzz  on the android platform (on an odroid) using a locally run version of clusterfuzz,  and it's unable to load path i set for LD_PRELOAD. e.g. bot error:
ERROR: ld.so: object '/system/lib/libclang_rt.asan-arm-android.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Can you please advise or provide suggestions on how i can resolve this? The LD_PRELOAD env variable is set in the UI in the "Edit or upload fuzzer" interface as follows:
LD_PRELOAD =/system/lib/libclang_rt.asan-arm-android.so
The path to libclang_rt.asan-arm-android.so is on the device and i've confirmed that permissions are all set and the device has been set to permissive mode.

**Comment by inferno-chromium** [comment]
Try putting this in AndroidLibFuzzerRunner (src/python/bot/fuzzers/libfuzzer.py) _get_default_args function ? If that works, we can think of generalizing it. This is for libFuzzer targets on Android device right ?
Why not patchelf and update rpath on the binary itself, then you shouldn't need this.

**Comment by audio-farm** [comment]
Thank you for your response. Issue has been resolved. This error was only showing when LD_PRELOAD was included in the UI. Found this not necessary to set for the fuzzer i was uploading to clusterfuzz.
