### ISSUE TITLE
error uploading fuzzer

### ISSUE THREAD

**Issue by am06** [google/clusterfuzz#1335]
Hi,

Please see my attached screenshots regarding my configuration. The only error message I get is "Error", no description whatsoever.......

How can you pass params to a grammar fuzzer for example, grammar files to be used? Can you use env for that? 

I was trying to debug this, but I can't even upload a new fuzzer........

Thanks.

![Screenshot from 2020-01-14 15-12-46](https://user-images.githubusercontent.com/1128817/72356540-5207b600-36e1-11ea-85b0-ade68b6da0c4.png)
![Screenshot from 2020-01-14 15-00-18](https://user-images.githubusercontent.com/1128817/72356539-5207b600-36e1-11ea-87dd-e2883a57a6c9.png)

**Comment by inferno-chromium** [comment]
Do you see any error/traceback on your console where run_server is running ?

**Comment by am06** [comment]
strange, but this worked now...........how do I pass params to the fuzzer though?

can you please have a look at my other issue as well? https://github.com/google/clusterfuzz/issues/1329

thanks.

**Comment by inferno-chromium** [comment]
Fuzzer only support getting three params - https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/#uploading-a-fuzzer
If you want to pass things to your fuzzer, you can create a wrapper script which calls something with whatever arguments.
