### ISSUE TITLE
local/install_deps.bash seems to fail mysteriously when there isn't enough memory

### ISSUE THREAD

**Issue by evverx** [google/clusterfuzz#134]
I launched a VM where `install_deps.bash` failed with
```sh
Running: bazel run //local:create_gopath 2>/dev/null
| Return code is non-zero (1).
| Exit.
```
, which wasn't very helpful. Without `2 >/dev/null` I was able to figure out what happened but unfortunately additionally broke something else because apparently the output is used to set `GOPATH` :-) I think it would be great if the output wasn't sent to "/dev/null" here.

(I relaxed the limits a bit and got past `install_deps.bash` and now `python butler.py run_server --bootstrap` seems to be stuck trying to "build templates for App Engine". The machine is totally unresponsive so it's hard to tell what's going on. I'm going to tweak the limits until it works but it would probably be useful to mention in the documentation how a "typical" machine is supposed to look like, that is something like https://github.com/google/oss-fuzz/blob/master/docs/faq.md#what-are-the-specs-on-your-machines maybe).

**Comment by evverx** [comment]
> The machine is totally unresponsive

Judging by "Out of memory: Kill process 2299 (node) score 115 or sacrifice child", it was the OOM killer that was busy destroying "polymer-bundler". I hope 32Gb will suffice.

**Comment by Dor1s** [comment]
That's really weird, I don't think you need any beefy machine for that. Which OS are you trying this on?

**Comment by evverx** [comment]
That was Ubuntu 18.04.1 LTS run on top of macOS Mojave with VirtualBox.

**Comment by evverx** [comment]
Anyway, I kind of find an abandoned beefy machine :-) and everything seems to be working as far as I can tell. I don't think I'll start to dig deeper any time soon so I think the issue can safely be closed.

And, by the way, congratulations on open-sourcing ClusterFuzz!

**Comment by inferno-chromium** [comment]
Reopening to improve the things mentioned in c#0.

**Comment by inferno-chromium** [comment]
bazel does not support a quite mode, so everything gets dumped to stderr - https://groups.google.com/forum/#!topic/bazel-discuss/JVCotYRXeyk

till then i will fix this to make it more obvious where we are running this command, like this is run in 'src' subdir. maybe also update code with comment.

**Comment by inferno-chromium** [comment]
polymer_bundler will be tracked by its own issue. bazel issue should be fixed now. Thanks for the report.
