### ISSUE TITLE
Connecting new bot running on private Linux server

### ISSUE THREAD

**Issue by mxmssh** [google/clusterfuzz#1353]
Hi,

I am trying to understand how to connect my physical Linux server with ClusterFuzz (GCE app). Everything works fine with GCE instances but I am a bit confused about how to add my own private instance.

There is instruction on how to add a physical machine running MacOS bot [here](https://google.github.io/clusterfuzz/production-setup/setting-up-bots/) and it does mention that it is possible to connect Non-Google Compute Engine bots. However, I do not quite understand how to do that since there is no direct instruction. There are Docker images but how can I use them and which one is suitable for running Linux bot? If you can point me in the right direction it would be great.

Thank you!

**Comment by inferno-chromium** [comment]
It is similar to android.bash which is linux bot running as android. we can explicitly add one, can you try - https://github.com/google/clusterfuzz/pull/1354

**Comment by mxmssh** [comment]
Thank you for the quick answer and script update! It works like a charm. Closing the issue.
