### ISSUE TITLE
Programmatic Job Upload

### ISSUE THREAD

**Issue by tick-rick** [google/clusterfuzz#1374]
Hello,

Current process for upload job is: 
- multipart form POST to port 9008 with key/custombuild zip
- POST to update-job on port 9000 with key and job details 

It appears call to update-job requires csrf token, making it a bit of a pain to interact with from say, CI pipeline. Is there a way to access this type of thing in an easier way than scraping out csrf tokens from html?

**Comment by oliverchang** [comment]
Hi, sorry for the late reply here. The jobs upload endpoint isn't intended for automated tooling. May we know what your use case is, to see if there is some other way CF can accommodate this?

**Comment by inferno-chromium** [comment]
Closing due to lack of response.
