### ISSUE TITLE
Crashers in ROOT_DIR

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#1376]
I just SSHed into a machine and see tons of crash-, oom- etc files in the root directory. I think this may be due to:

https://github.com/google/clusterfuzz/blob/5e9b02204428cb1a81993d512844966d2bee0a80/src/python/bot/fuzzers/libFuzzer/engine.py#L206

Since we're not passing an artifact prefix, we default to the CWD (i.e. ROOT_DIR), and create these files during merge.

@Dor1s does this seem right?

**Comment by Dor1s** [comment]
Sounds totally reasonable, but I'm wondering why this issue didn't manifest itself before. Looks like the previous merge code also used `None`: https://github.com/google/clusterfuzz/pull/1261/files#diff-304418edd63d46911184f5225f349ddeR204

I think in general we don't expect fuzz targets to create have many crashes (if any) during merge, unless a fuzz target is broken or simply bad.

**Comment by Dor1s** [comment]
Is this an OSS-Fuzz bot?

**Comment by oliverchang** [comment]
This was on chromium. I guess this might have been broken before as well without us noticing.

**Comment by Dor1s** [comment]
I see. Yes, looks like that's the case. Another great investigation Sir!

**Comment by Dor1s** [comment]
Ok, so fixing should be easy, but maybe we should take the count of the crashing inputs afterwards and log it anywhere? Might be a good indicator that a particular fuzz target is not doing well.
