### ISSUE TITLE
gsutil error (missing google-compute-engine)

### ISSUE THREAD

**Issue by jfoote** [google/clusterfuzz#143]
Running `python butler.py create_config --oauth-client-secrets-path=$CLIENT_SECRETS_PATH --project-id=$CLOUD_PROJECT_ID $CONFIG_DIR` from the [production setup directions for Clusterfuzz](https://google.github.io/clusterfuzz/production-setup/clusterfuzz/) on a recently provisoned GCE n1-standard-1 node caused a Python error in the [gsutil `defstorageclass` step](https://github.com/google/clusterfuzz/blob/5650a7f1aaa67e1130b67f31015b2514f28fdcdc/src/local/butler/create_config.py#L212): `ImportError: No module named google_compute_engine`. I worked around it by running `pip install google-compute-engine` from within the virtualenv environment and re-running the command.

**Comment by inferno-chromium** [comment]
`sudo rm -f /etc/boto.cfg`

Can you check if you have a stale /etc/boto.cfg file. This is a very weird GCE bug, let me think where to document this. We can't delete this file without user consent i think.

**Comment by inferno-chromium** [comment]
https://github.com/travis-ci/travis-ci/issues/7940

**Comment by inferno-chromium** [comment]
you are right, i think we need to force google-compute-engine to workaround this. coming up with patch.

**Comment by inferno-chromium** [comment]
fixed in https://github.com/google/clusterfuzz/pull/144, thanks for the report.
