### ISSUE TITLE
Fuzzing Strategies not being added to Testcase Metadata

### ISSUE THREAD

**Issue by mpherman2** [google/clusterfuzz#1477]
In fuzz_task.py it appears as if we are attempting to add the fuzzing strategies to testcase metadata: 
https://github.com/google/clusterfuzz/blob/2c9b41570dbcfca3e8bbf1266b1b8ed5e2cef7e4/src/python/bot/tasks/fuzz_task.py#L992-L1003

When we do this though, we try to find the strategies by parsing through crash.stacktrace. We believe the problem is that crash.stacktrace does not have the fuzzing strategy info. This is contained in the logs.

We need to either parse through the logs, or add the fuzzing strategy info to the crash stacktrace.

**Comment by Dor1s** [comment]
Thanks @mpherman2 !

> We need to either parse through the logs, or add the fuzzing strategy info to the crash stacktrace.

By the logs we mean this:

https://github.com/google/clusterfuzz/blob/fb4d1aedce2fb0d93c2d6e5cb280f6f187055101/src/python/bot/tasks/fuzz_task.py#L1303-L1306
