### ISSUE TITLE
Some butler commands wont work with 1.0.0 release zip since it does not have .git directory

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#151]
Needs fixing things like create_config, deploy, package to ignore if .git directory does not exist.

**Comment by inferno-chromium** [comment]
Probably needs 1.0.1 release as well.

**Comment by inferno-chromium** [comment]
the big hurdle here is the packaging script that create source archives, seems to rely on git ls-files to know which files to package.

**Comment by oliverchang** [comment]
Should we just ask users to git checkout to the tagged release instead of using the zip? Not sure if the work here is worth supporting this use case?

**Comment by inferno-chromium** [comment]
yes that sounds good, i didn't find a way to hide source code archive on releases page. should we then just add a line in documentation about this ?

**Comment by oliverchang** [comment]
Might be find to find that line in the documentation...

Maybe we can just add a note to every release? Like:

Please download this release by checking out the release tag in a git checkout:

```bash
$ git checkout tags/v1.0.0
```
Archived versions of ClusterFuzz do **not** work with many `butler.py` commands.

**Comment by inferno-chromium** [comment]
makes sense, updated https://github.com/google/clusterfuzz/releases/tag/v1.0.0
