### ISSUE TITLE
Fuzzing a GUI application

### ISSUE THREAD

**Issue by vadi2** [google/clusterfuzz#153]
Couldn't find a mailing list / forum, and the readme says to ask questions here, so here's a question from a beginner -

I'm just getting into fuzzing now with the open-sourcing of clusterfuzz and looking to set it up to an open-source project I contribute to, [Mudlet](https://github.com/mudlet/mudlet). It's a GUI application that connects to a telnet port, gets input from the player and sends it back and forth. 

I thought I'd start with the telnet class that handles incoming data. If we can ensure that can handle any input thrown at us, then that's great. I've started out by refactoring the socket data read to be [fuzz-friendly](https://github.com/Mudlet/Mudlet/pull/2337).

Next, fuzz target that spawns my `ctelnet` class and passes in the inputs. Problem creating `ctelnet` - it requires an application object to read network-specific settings and to interact with the other parts of the application as a result of the incoming text stream.

What is the best advice here to continue? Should I create the whole application (which would be a more realistic scenario)?

**Comment by jonathanmetzman** [comment]
>What is the best advice here to continue? Should I create the whole application (which would be a more realistic scenario)?

What exactly are the two alternatives? Refactoring the code to be fuzzable or reusing most of the application for fuzzing? 
Hard for us to say, generally factoring out the parts needed is better but that can also change the code more than is worth doing. 
I don't really have an answer here, your guess since you are familiar with the code will be better than anything I can suggest.

**Comment by jonathanmetzman** [comment]
FYI, you may have more luck asking questions about writing fuzzers to the [libFuzzer](https://groups.google.com/forum/#!forum/libfuzzer) or [AFL](https://groups.google.com/forum/#!forum/afl-users) mailing lists. Their focus is actually on fuzzing and not on fuzzing infra (which is ours) and the mailing lists are higher traffic than this issue tracker so there are more people around who may be able to help (though I'm happy to help where I can!).

**Comment by vadi2** [comment]
I'll check there, thanks!

**Comment by jonathanmetzman** [comment]
To follow up a little here. I would go with whatever is easiest for you and improve if needed.

By the way here are some links to general fuzzing documentation that one of my coworkers, compiled.
Maybe you'll find them helpful.
* [libFuzzer documentation](http://libfuzzer.info)
* [libFuzzer tutorial](http://tutorial.libfuzzer.info)
* [libFuzzer workshop](https://github.com/Dor1s/libfuzzer-workshop)
* [Chromium Fuzzing Page](https://chromium.googlesource.com/chromium/src/testing/libfuzzer/)
