### ISSUE TITLE
Fix minimizer tests under Python 3

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#1534]
As of writing, there are only 14 tests left that fail when run with Python 3.

8 of these are from the minimizer. @mbarbella-chromium as you're the most familiar with this code, could you please take a look?

**Comment by inferno-chromium** [comment]
@mbarbella-chromium - lets try to prioritize this week please.

**Comment by mbarbella-chromium** [comment]
Fixed by #1538
