### ISSUE TITLE
Update TensorFlow and other dependencies after Python3 migration

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1540]
We haven't updated it in a while and while working on https://github.com/google/clusterfuzz/issues/1535 it became evident that we're using a too old version. For instance, there is not build of it for Python3.7.

I'm hoping to fix https://github.com/google/clusterfuzz/issues/1535 with some old-but-new-enough version, but we'll definitely should upgrade all ML pieces after the migration.

**Comment by mihaimaruseac** [comment]
I didn't know TF is being used as backend here. But if there's some help needed from TF team, I can do the work.

**Comment by Dor1s** [comment]
Thank you @mihaimaruseac! It's currently used by a small feature only, which isn't even enabled in OSS-Fuzz yet.

**Comment by Dor1s** [comment]
@mihaimaruseac could you please advise whether it makes sense to upgrade to 1.15.10 or should we target 2.2.0 instead? How much code changes would major upgrade involve?

**Comment by mihaimaruseac** [comment]
We recommend using the latest update for longer support. We are currently in the process of releasing 2.3.0, so maybe let's wait a few more weeks and then switch to that?

The main upgrade cost would be in converting from 1.15 to 2.0. There is a script to do the API conversion but that won't cover the transition from Session and graph mode to eager mode.

If you file a bug against me internally I can try to do the conversion in a week (or less) after the 2.3 release.

**Comment by oliverchang** [comment]
I recall running into some issues with tensorflow.contrib.{layers,rnn} no longer being available in tensorflow 2.x when we tried the automated conversion a few months ago. Are there drop in replacements for those?

**Comment by mihaimaruseac** [comment]
Keras should have support for them now.

**Comment by mihaimaruseac** [comment]
Is there a dockerfile I can use to test this? Or should I attempt to build following the existing install instructions?

**Comment by mihaimaruseac** [comment]
I looked through the code and it seems the main issue with conversion would be converting from TF v1 graph API / control flow to the v2 eager one. The APIs used seem to be available. I can send a PR with the fix, though I'm thinking we should wait until 2.3 is fully released. But if that's too long to wait for, I can attempt a fix earlier, against either 2.2.0 or the RC for 2.3.

Also, there are two docker files configured to install TF 1.15. Plus, the CUDA version used is 9.0 but TF 2.2 and 2.3 support only CUDA 10.1. But I think these changes are not a priority, first we need to convert the rnn fuzzer.

**Comment by Dor1s** [comment]
@mihaimaruseac I'll try to update the docker image to use 2.3rc and compatible versions of CUDA / GPU drivers. When 2.3 gets released it should be trivial to switch to the actual released version.

If you could provide even draft patch with the conversion of the scripts in https://github.com/google/clusterfuzz/tree/master/src/python/bot/fuzzers/ml/rnn that would be very much appreciated.

I'll document how to test the changes later in this issue.

**Comment by Dor1s** [comment]
When I'm trying to run `pipenv install tensorflow-gpu==2.3.0rc0`, I'm getting:

```
Adding tensorflow-gpu==2.3.0rc0 to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches tf-estimator-nightly<2.3.0.dev2020062302,>=2.3.0.dev2020062301
```
@mihaimaruseac is there anything I'm doing obviously wrong?

**Comment by mihaimaruseac** [comment]
Oh, apologies. This is caused by us needing to install against Estimator nightly for the rc0. It should pull [the existing pip](https://pypi.org/project/tf-estimator-nightly/2.3.0.dev2020062301/) but  not sure why it doesn't. Either it needs a `--pre` flag to accept download of prereleases or it's because `tf-estimator-nightly` [is not in `Pipfile.lock`](https://pypi.org/project/tf-estimator-nightly/2.3.0.dev2020062301/).

We are planning an rc1 this week which would depend on Estimator rc0. Maybe that would help?

**Comment by Dor1s** [comment]
Thanks for the quick response @mihaimaruseac.

This is becoming urgent on our end, although at the same time I'm having troubles reproducing test failures locally. Seems like we can give a shot at rc1 later this week unless I quickly make things work for 2.2.0

**Comment by mihaimaruseac** [comment]
The API changes between 2.2 and 2.3 should not be major, so we can try going to 2.2 now and converting to 2.3 later.

The main difference between 2.2 and 2.3 is that 2.3 has several massive performance improvements and is a long term release (3 years of patching instead of just 1)

**Comment by Dor1s** [comment]
Thanks, Mihai. Ok let's wait for the next 2.3 RC, as anyway I'm quite swamped this week with two sheriffing rotations and partial OOO.

**Comment by Dor1s** [comment]
@mihaimaruseac I see that 2.3.0-rc1 was indeed released last week (https://github.com/tensorflow/tensorflow/releases/tag/v2.3.0-rc1)

do you know what's the right way to install it via `pipenv`?

**Comment by Dor1s** [comment]
@mihaimaruseac there is still an issue with `tensorflow-estimator`, do you know what's the right way to deal with it?

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches tensorflow-estimator<2.4.0,>=2.3.0-rc0
Tried: 1.10.6, 1.10.7, 1.10.8, 1.10.9, 1.10.10, 1.10.11, 1.10.12, 1.13.0rc0, 1.13.0, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0, 1.15.1, 1.15.2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0, 2.2.0rc0, 2.2.0, 2.3.0rc0
```

**Comment by mihaimaruseac** [comment]
Apologies, that seems like a bug in version number (`2.3.0-rc0` expected versus `2.3.0rc0` found in the versions list).

I'll send a hot patch to TF and the next RC should be ok. Thanks for catching the issue.

**Comment by Dor1s** [comment]
Thanks a lot! Does "the next RC" mean we'd need to wait another couple weeks? Or is it something that gets updated regularly?

**Comment by mihaimaruseac** [comment]
It should be up by end of this week if there are no build failures. In a few weeks the plan is to have a final release for `2.3.0`. and then 2.4 will start in Fall.

**Comment by Dor1s** [comment]
Nice, that sounds good. Thanks again for your help!

**Comment by Dor1s** [comment]
Looks like 2.3.0rc2 was released: https://github.com/tensorflow/tensorflow/releases/tag/v2.3.0-rc2

But I'm still running into (now even weirder issue) with tensorflow-estimator:

```
$ pipenv install tensorflow-estimator==2.3.0rc0
Installing tensorflow-estimator==2.3.0rc0…
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: tensorflow-estimator==2.3.0rc0 in /usr/local/google/home/mmoroz/.local/share/virtualenvs/clusterfuzz-UxmpcJs2/lib/python3.7/site-packages (2.3.0rc0)

Adding tensorflow-estimator==2.3.0rc0 to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches tensorflow-estimator<2.4.0,==2.3.0rc0,>=2.3.0rc0
Tried: 1.10.6, 1.10.7, 1.10.8, 1.10.9, 1.10.10, 1.10.11, 1.10.12, 1.13.0rc0, 1.13.0, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0, 1.15.1, 1.15.2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0, 2.2.0rc0, 2.2.0, 2.3.0rc0
```

It says that it tried `2.3.0rc0`, but failed to satisfy `<2.4.0,==2.3.0rc0,>=2.3.0rc0`, which is nonsense.

@oliverchang is there anything obvious I'm missing when trying to install:

```
tensorflow = "==2.3.0rc2"
tensorflow-estimator = "==2.3.0rc0"
```

?

I've tried both adding these to the Pipfile and also just doing `pipenv install tensorflow==2.3.0rc2 tensorflow-estimator==2.3.0rc0` from within the virtual env. I feel like I'm just using that python3 / pipenv stuff incorrectly.

**Comment by mihaimaruseac** [comment]
This is weird. If you do `pipenv install tensorflow==2.3.0rc2`, does it work?

**Comment by mihaimaruseac** [comment]
Alternatively, what is the output of

```
pipenv install --skip-lock
pipenv graph
```

**Comment by Dor1s** [comment]
Thanks @mihaimaruseac 

`pipenv install tensorflow==2.3.0rc2` failed,

but `pipenv install --skip-lock tensorflow==2.3.0rc2` succeeded, and now

`pipenv graph` shows

```
  - tensorflow-estimator [required: <2.4.0,>=2.3.0rc0, installed: 2.3.0rc0]
```

which seems fine to me. Let me try to fix that now :)

**Comment by Dor1s** [comment]
Well, `pipenv lock` complains once again with that nonsense error:

```
$ pipenv lock
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches tensorflow-estimator<2.4.0,>=2.3.0rc0
Tried: 1.10.6, 1.10.7, 1.10.8, 1.10.9, 1.10.10, 1.10.11, 1.10.12, 1.13.0rc0, 1.13.0, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0, 1.15.1, 1.15.2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0, 2.2.0rc0, 2.2.0, 2.3.0rc0

```


@oliverchang have you seen such an error before?

I can't see any sane reason why it complains:

```
>>> '2.3.0rc0' < '2.4.0'
True
>>> '2.3.0rc0' >= '2.3.0rc0'
True
>>>
```

**Comment by mihaimaruseac** [comment]
I think it might be a bug in `pipenv lock` :(

**Comment by Dor1s** [comment]
Sounds reasonable, filed https://github.com/pypa/pipenv/issues/4397

**Comment by Dor1s** [comment]
Looks like I've manage to install it (https://github.com/google/clusterfuzz/pull/1921) after I manually did `pipenv uninstall tensorflow==2.2.0rc4` and `pipenv uninstall tensorflow-estimator==2.2.0`. Maybe that's unrelated and something else has changed, but either way I'll see of it gets installed correctly in a clean environment and if yes, I can proceed with upgrading other dependencies and migrating the code.

**Comment by mihaimaruseac** [comment]
Oh, so maybe the errors were because of incompatible packages already present in the environment. Interesting

**Comment by Dor1s** [comment]
I'm also able to manually create and set up a GPU both with `tensorflow-gpu==2.3.0rc2` and other dependencies. Now trying to remember how I did that for a bot running COS image...

**Comment by Dor1s** [comment]
looks like a non-RC 2.3 was just released today, gonna try it then: https://github.com/tensorflow/tensorflow/releases/tag/v2.3.0

**Comment by mihaimaruseac** [comment]
So now that all TF bumps finished, it's time for me to look into upgrading the tests and the model :) Probably will have something Friday/early next week, apologies for the delay

**Comment by Dor1s** [comment]
the GPU bots should be in a good shape now:

```
>>> tensorflow.test.gpu_device_name()
2020-07-28 21:38:38.239857: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-28 21:38:38.240752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2020-07-28 21:38:38.240827: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-28 21:38:38.240880: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-07-28 21:38:38.240906: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-07-28 21:38:38.240928: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-07-28 21:38:38.240951: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-07-28 21:38:38.240979: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-07-28 21:38:38.241001: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-07-28 21:38:38.241095: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-28 21:38:38.241891: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-28 21:38:38.242617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-07-28 21:38:38.242667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-28 21:38:38.242685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-07-28 21:38:38.242700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-07-28 21:38:38.242811: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-28 21:38:38.243800: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-28 21:38:38.244574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/device:GPU:0 with 14951 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
'/device:GPU:0'
```

but the bots aren't getting any tasks yet (maybe we disabled it):

```
Error occurred while working on task.
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 82, in task_loop
    task = tasks.get_task()
  File "/mnt/scratch0/clusterfuzz/src/python/base/tasks.py", line 193, in get_task
    return get_regular_task(queue=ML_JOBS_TASKQUEUE)
  File "/mnt/scratch0/clusterfuzz/src/python/base/tasks.py", line 167, in get_regular_task
    pubsub.subscription_name(application_id, queue), max_messages=1)
  File "/mnt/scratch0/clusterfuzz/src/python/google_cloud_utils/pubsub.py", line 160, in pull_from_subscription
    raise RuntimeError('Invalid subscription: ' + subscription)
RuntimeError: Invalid subscription: projects/cluster-fuzz/subscriptions/ml-jobs-linux
```

**Comment by inferno-chromium** [comment]
> the GPU bots should be in a good shape now:
> 
> ```
> >>> tensorflow.test.gpu_device_name()
> 2020-07-28 21:38:38.239857: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-07-28 21:38:38.240752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
> pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
> coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
> 2020-07-28 21:38:38.240827: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> 2020-07-28 21:38:38.240880: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
> 2020-07-28 21:38:38.240906: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
> 2020-07-28 21:38:38.240928: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
> 2020-07-28 21:38:38.240951: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
> 2020-07-28 21:38:38.240979: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
> 2020-07-28 21:38:38.241001: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
> 2020-07-28 21:38:38.241095: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-07-28 21:38:38.241891: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-07-28 21:38:38.242617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
> 2020-07-28 21:38:38.242667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-07-28 21:38:38.242685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
> 2020-07-28 21:38:38.242700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
> 2020-07-28 21:38:38.242811: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-07-28 21:38:38.243800: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-07-28 21:38:38.244574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/device:GPU:0 with 14951 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
> '/device:GPU:0'
> ```
> 
> but the bots aren't getting any tasks yet (maybe we disabled it):
> 
> ```
> Error occurred while working on task.
> Traceback (most recent call last):
>   File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 82, in task_loop
>     task = tasks.get_task()
>   File "/mnt/scratch0/clusterfuzz/src/python/base/tasks.py", line 193, in get_task
>     return get_regular_task(queue=ML_JOBS_TASKQUEUE)
>   File "/mnt/scratch0/clusterfuzz/src/python/base/tasks.py", line 167, in get_regular_task
>     pubsub.subscription_name(application_id, queue), max_messages=1)
>   File "/mnt/scratch0/clusterfuzz/src/python/google_cloud_utils/pubsub.py", line 160, in pull_from_subscription
>     raise RuntimeError('Invalid subscription: ' + subscription)
> RuntimeError: Invalid subscription: projects/cluster-fuzz/subscriptions/ml-jobs-linux
> ```

Maybe we did (since bots were broken), i dont see USE_CORPUS_FOR_ML in any jobs ? if we didn't create any jobs in that subscription, then we see such errors.

**Comment by Dor1s** [comment]
there is `USE_CORPUS_FOR_ML = True` in `libfuzzer_chrome_asan` job

I also didn't find it instantly, perhaps because of the pagination we have there now

**Comment by Dor1s** [comment]
hm `ml-jobs-linux` subscription isn't present in https://pantheon.corp.google.com/cloudpubsub/subscription/list?project=cluster-fuzz

**Comment by Dor1s** [comment]
After I've manually created `ml-jobs-linux` PubSub subscription, the task scheduling and claiming started to work. Thanks @oliverchang for looking into this with me, I filed #https://github.com/google/clusterfuzz/issues/1934

**Comment by Dor1s** [comment]
@mihaimaruseac thanks a lot for willing to help with the scripts migration!

One way you can try running them is this:

```
# python3.7 clusterfuzz/src/python/bot/fuzzers/ml/rnn/train.py   --input-dir=/tmp/max_test_inputs   --model-dir=/tmp/max_test_model   --log-dir=/tmp/mxa_test_log
2020-07-29 19:22:29.533239: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/../fuzzers/ml/rnn/train.py", line 30, in <module>
    from tensorflow.contrib import layers
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

There's also a readme in https://github.com/google/clusterfuzz/tree/master/src/python/bot/fuzzers/ml/rnn


And another workflow would to be follow https://google.github.io/clusterfuzz/getting-started/prerequisites/ and set up a ClusterFuzz development environment, then you would need to run the following commands:

```
$ source prepare_and_export_test_buckets.bash  # attached
$ INTEGRATION=1 python butler.py py_unittest -t core -p '*ml*'
```

then you'll see the failing tests:

```
Running: pkill -KILL -f "dev_appserver.py"
| Return code is non-zero (1).
Running: pkill -KILL -f "CloudDatastore.jar"
| Return code is non-zero (1).
Running: pkill -KILL -f "pubsub-emulator"
| Return code is non-zero (1).
Running: pkill -KILL -f "run_bot"
| Return code is non-zero (1).
test_empty_corpus (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test generation should abort for empty corpus. ... ok
test_generate (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test generate specified number of inputs. ... ok
test_invalid_model (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test TensorFlow should throw exception if model does not match. ... ok
test_timeout (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test timeout case in generation. ... ok
test_combine_worker_tokens_with_prefix_and_suffix (tests.core.bot.minimizer.html_minimizer_test.HTMLMinimizerTest)
Test that combine worker tokens works the way that the minimizer expects ... ok
test_get_tokens_and_metadata_splits_correct_data (tests.core.bot.minimizer.html_minimizer_test.HTMLMinimizerTest)
Test that each of the sections the data is split into for minimization ... ok
test_get_tokens_and_metadata_splits_correct_number (tests.core.bot.minimizer.html_minimizer_test.HTMLMinimizerTest)
Test that the html minimizer splits the data into the correct number of ... ok
test_get_tokens_and_metadata_splits_correct_types (tests.core.bot.minimizer.html_minimizer_test.HTMLMinimizerTest)
Test that each of the sections the data is split into for minimization ... ok
test_minimization_returns_correct_result (tests.core.bot.minimizer.html_minimizer_test.HTMLMinimizerTest)
Test that the minimizer goes through all of the correct sub-minimizers ... ok
test_execute (tests.core.bot.tasks.ml_train_task_test.ExecuteTaskTest)
Test execute task. ... ok
test_get_latest_model (tests.core.bot.tasks.ml_train_task_test.GetLastSavedModelTest)
Test latest model is returned as a dictionary. ... ok
test_get_valid_model (tests.core.bot.tasks.ml_train_task_test.GetLastSavedModelTest)
Test lastest model is not returned if it is invalid. ... ok
test_no_valid_model (tests.core.bot.tasks.ml_train_task_test.GetLastSavedModelTest)
Test no model is returned if all models are invalid. ... ok
test_small_corpus (tests.core.bot.tasks.ml_train_task_test.MLRnnTrainTaskIntegrationTest)
Test small corpus situation. ... FAIL
test_train_rnn (tests.core.bot.tasks.ml_train_task_test.MLRnnTrainTaskIntegrationTest)
Test train RNN model on a simple corpus. ... FAIL

======================================================================
FAIL: test_small_corpus (tests.core.bot.tasks.ml_train_task_test.MLRnnTrainTaskIntegrationTest)
Test small corpus situation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/mmoroz/projects/py3/clusterfuzz/src/python/tests/core/bot/tasks/ml_train_task_test.py", line 204, in test_small_corpus
    self.assertEqual(result.return_code, constants.ExitCode.CORPUS_TOO_SMALL)
AssertionError: 1 != 2

======================================================================
FAIL: test_train_rnn (tests.core.bot.tasks.ml_train_task_test.MLRnnTrainTaskIntegrationTest)
Test train RNN model on a simple corpus.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/mmoroz/projects/py3/clusterfuzz/src/python/tests/core/bot/tasks/ml_train_task_test.py", line 189, in test_train_rnn
    self.assertEqual(result.return_code, constants.ExitCode.SUCCESS)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 15 tests in 18.125s

FAILED (failures=2)

Slow tests:
 10.28s: test_timeout (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
```

[prepare_and_export_test_buckets.bash.txt](https://github.com/google/clusterfuzz/files/4997312/prepare_and_export_test_buckets.bash.txt)

**Comment by mihaimaruseac** [comment]
I'll try to create the environment. Thanks for the guide

**Comment by Dor1s** [comment]
@mihaimaruseac I forgot one more important bit: the failing tests are disabled right now. To enable them:

```diff
$ git diff
diff --git a/src/python/tests/core/bot/tasks/ml_train_task_test.py b/src/python/tests/core/bot/tasks/ml_train_task_test.py
index c8f3029c..c4ef296b 100644
--- a/src/python/tests/core/bot/tasks/ml_train_task_test.py
+++ b/src/python/tests/core/bot/tasks/ml_train_task_test.py
@@ -158,8 +158,6 @@ class ExecuteTaskTest(unittest.TestCase):
                                                 model_directory, log_directory)
 
 
-# TODO(mmoroz): Re-enable this.
-@unittest.skip('Training is broken.')
 @test_utils.integration
 class MLRnnTrainTaskIntegrationTest(unittest.TestCase):
   """ML RNN training integration tests."""
```

**Comment by Dor1s** [comment]
@mihaimaruseac did you have a chance to look into this?

**Comment by mihaimaruseac** [comment]
Apologies for the delay, unfortunately not yet. But I have time from tomorrow after 4 until Monday noon and will try to get at least the system running and get a list of the errors.

**Comment by Dor1s** [comment]
@mihaimaruseac no worries, you're obviously not obliged to do that at all. Please let us know if you don't have cycles to help with this, and we'll try to migrate on our own :)

**Comment by mihaimaruseac** [comment]
I tried the first version to reproduce but got 

```
Traceback (most recent call last):
  File "src/python/bot/fuzzers/ml/rnn/train.py", line 33, in <module>
    from bot.fuzzers.ml.rnn import constants
ModuleNotFoundError: No module named 'bot'
```

I will try creating an environment

**Comment by mihaimaruseac** [comment]
Seem the import issue is actually a python3 import change. I managed to reproduce outside of the tree:

```
mihaimaruseac@ankh:/tmp/x$ tree -alps
.
└── [drwxr-x---        4096]  src
    ├── [-rw-r-----           0]  __init__.py
    └── [drwxr-x---        4096]  python
        ├── [drwxr-x---        4096]  bot
        │   ├── [drwxr-x---        4096]  fuzzers
        │   │   ├── [-rw-r-----           0]  __init__.py
        │   │   └── [drwxr-x---        4096]  ml
        │   │       ├── [-rw-r-----           0]  __init__.py
        │   │       └── [drwxr-x---        4096]  rnn
        │   │           ├── [-rw-r-----          23]  constants.py
        │   │           ├── [-rw-r-----           0]  __init__.py
        │   │           └── [-rw-r-----          64]  train.py
        │   └── [-rw-r-----           0]  __init__.py
        └── [-rw-r-----           0]  __init__.py
```

Where `constants.py` is

```python
RNN_MODEL_NAME = 'rnn'
```

And `train.py` is

```python
from bot.fuzzers.ml.rnn import constants

print(RNN_MODEL_NAME)
```

I get the same error:

```
mihaimaruseac@ankh:/tmp/x$ python3.7 src/python/bot/fuzzers/ml/rnn/train.py
Traceback (most recent call last):
  File "src/python/bot/fuzzers/ml/rnn/train.py", line 1, in <module>
    from bot.fuzzers.ml.rnn import constants
ModuleNotFoundError: No module named 'bot'
```

I think this is a python3 import issue. Looking for a fix. Probably `__init__.py` needs updating instead of being empty

**Comment by mihaimaruseac** [comment]
This seems to work, but I need to create some training data:

```
(venv) mihaimaruseac@ankh:~/src/repos/clusterfuzz/src/python$ python3.7 -m bot.fuzzers.ml.rnn.train   --input-dir=/tmp/max_test_inputs   --model-dir=/tmp/max_test_model   --log-dir=/tmp/mxa_test_log
2020-08-09 11:04:10.704890: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-09 11:04:10.704932: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Loaded 0 corpus files.
No training data has been found. Aborting.
```

**Comment by mihaimaruseac** [comment]
Oh, I need to download corpus from CNS.

**Comment by mihaimaruseac** [comment]
Managed to get it running. Will now look into fixing the model.

**Comment by mihaimaruseac** [comment]
So there are two options:

1. Rewrite the entire model using Keras layers and eager execution. Will reduce amount of code (Keras layers are declarative, no need to declare all placeholders) and make it easier to debug internal state

2. Keep model as it is and only attempt to replace the `tf.contrib.rnn` and `tf.contrib.layers` code after adding `tf.compat.v1.disable_eager_execution` at the start.

First option will require retraining any saved model as I am not sure that the existing `tf.compat.v1.train.Saver` can be read from V2 code (I'll look into it). Will also require more refactoring time but it's very doable. Second option has the issue that we might not find replacements for the two modules that work properly with graph mode.

I'd go with the first option if that's ok with you.

**Comment by Dor1s** [comment]
@mihaimaruseac thank you SO MUCH for looking into this!

Retraining the existing models is totally fine -- all our existing models are quite old already and we do re-training every 2 weeks anyway.

Would the first model require us to install any other dependencies? Other than that sounds great to me.

**Comment by mihaimaruseac** [comment]
Sounds great. I think the first option only uses TF and its dependencies, so it should be done without changing anything in `Pipfile`.

**Comment by Dor1s** [comment]
Awesome! Even if we need to add something, that most likely would be fine. The only edge case is when we need to satisfy revision compatibility (like TF <-> CUDA <-> Nvidia drivers).

**Comment by mihaimaruseac** [comment]
Got a model that trains, now I need to clean up the code and plug in the knobs that existed in the old model (since I just used defaults for now to ensure shape of tensors matches expected).

Unfortunately, probably the PR with the fix will be late Friday or early next week. Sorry for the delay

**Comment by Dor1s** [comment]
That is super awesome @mihaimaruseac, thanks for the update!

**Comment by mihaimaruseac** [comment]
I think #1978 works now.

**Comment by Dor1s** [comment]
Yay, the training works in prod! 

```
I 2020-08-19T21:53:03.297656469Z Launching the training with the following arguments: "['/mnt/scratch0/clusterfuzz/src/python/bot/tasks/../fuzzers/ml/rnn/train.py', '--input-dir=/mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/usrsctp_fuzzer_corpus', '--model-dir=/mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/usrsctp_fuzzer_model', '--log-dir=/mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/usrsctp_fuzzer_log']". 
I 2020-08-19T22:49:56.743119698Z Uploading the model for usrsctp_fuzzer: rnn.data-00000-of-00001, rnn.index. 
```

**Comment by Dor1s** [comment]
I guess we should delete old `rnn.meta` files though. @mihaimaruseac those aren't needed anymore, right?

**Comment by mihaimaruseac** [comment]
> I guess we should delete old `rnn.meta` files though. @mihaimaruseac those aren't needed anymore, right?

They are not used anymore, except if you want to load old models with the old TF format.

**Comment by Dor1s** [comment]
> They are not used anymore, except if you want to load old models with the old TF format.

Thanks, deleted those.

**Comment by Dor1s** [comment]
Confirmed that everything is working end-to-end on the Chromium instance.

**Comment by Dor1s** [comment]
@mihaimaruseac one more question for you. I saw the recent 2.3.1 release. Would it make sense for us to keep following the latest minor release? Or maybe we're good with sticking to 2.3.0?

**Comment by mihaimaruseac** [comment]
2.3.1 has several patches though I don't think any affect the usage of the model in CF. Since you don't have users sending their models, it is ok to not upgrade. There should be no changes in the API and behavior so upgrading should also be easy.

**Comment by Dor1s** [comment]
Thank you @mihaimaruseac !
