### ISSUE TITLE
Better eviction of data bundles

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#1543]
Right now we log an error and clear every all data dirs when we run out of disk space and build eviction isn't enough. We should come up with a slightly more elegant approach that allows the task to proceed rather than restart.

**Comment by inferno-chromium** [comment]
yes similar / same as https://github.com/google/clusterfuzz/issues/893

**Comment by inferno-chromium** [comment]
right now, running out of disk space is a common issue.

either bad targets fill up stuff during fuzz, then merge fails.
or over time, data bundles build up, and then we clear stuff, but we do it not elegantly, so exceptions all over the place.

**Comment by oliverchang** [comment]
Ah ok, let's close this one in favour of the existing one.
