### ISSUE TITLE
Can we deploy clusterfuzz in a private shared VPC?

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#1586]
We are looking to deploy clusterfuzz for our internal development teams to use for testing their binary files.  From a security perspective we need to run our fuzzing VMs in our private VPCs that have VPN connections back to our corporate network.  We are using shared VPCs to manage the VPN connections and we cut out a slice of our corporate private IPs so that traffic from these VMs will travel back through our VPNs and exit out of our corporate internet gateways.  This allows for monitoring from our security teams the traffic leaving.  So I know in the instance templates that you have that you guys are using NATs which I assume is what the VMs use to pull any kind of external dependencies.  We would prefer that they not go through google's NATs and matter of fact our shared VPC routes all internet traffic back through our corporate networks where we have Palo Altos monitoring the traffic.  

I tried to deploy my VMs using this shared VPC setup that we have on a clean GCP project but for some reason it doesn't seem to want to deploy the VMs.  Matter of fact I believe clusterfuzz assumes that there are default VPCs which we set as an org policy not to allow.  So there is no default networks and we have to create the VPCs prior to creating the first time the clusterfuzz deployment.  Is there a way to preconfigure a shared VPC so that the clusterfuzz will deploy there?  I don't see where we could preset the network features.  We also want to turn off the NAT configuration and I just removed those parts in the instance template but that was after we first failed to deploy everything in the create process and it configures the config files and we tried to deploy again but it fails to create the VMs.  Any help would be much appreciated.

**Comment by oliverchang** [comment]
Hi, I'm afraid none of us are familiar with shared VPCs or have tried them. Our instance templates are just the GCP standard format: https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates

So you'd need to figure out the right fields to change to use your shared VPC instead. For pre creating a shared VPC, this seems like something that you'd be able to do with a single script maintained by your side.

**Comment by urbanenomad** [comment]
yeah I have been playing around with the instance templates on our end.  One thing I am not clear about is that clusterfuzz expects a default VPC to exist but in our enterprise environment that is not allowed and the VPC has to be created before hand to be shared with the project.

I started to modify the clusterfuzz configuration to utilize a shared VPC.  The one part I am running into challenges to leverage is the memorystore the managed redis service due to it's need for PRIVATE_SERVICE_ACCESS connectionMode ip addresses and setting up.  I am wondering if this service is necessary for clusterfuzz to work?  How does this work when it is running in local development?

**Comment by inferno-chromium** [comment]
> yeah I have been playing around with the instance templates on our end. One thing I am not clear about is that clusterfuzz expects a default VPC to exist but in our enterprise environment that is not allowed and the VPC has to be created before hand to be shared with the project.

yes you can setup network whatever way you want and then change the instance template (+ increment version) and redeploy to pick up changes.

> 
> I started to modify the clusterfuzz configuration to utilize a shared VPC. The one part I am running into challenges to leverage is the memorystore the managed redis service due to it's need for PRIVATE_SERVICE_ACCESS connectionMode ip addresses and setting up. I am wondering if this service is necessary for clusterfuzz to work? How does this work when it is running in local development?

Everything will still work even if memorystore is not available. it is more like an optimization, everything should still work.

**Comment by urbanenomad** [comment]
in the butyler.py create_config python script do I need to remove that in the script or is there a flag to remove that feature?

**Comment by inferno-chromium** [comment]
you can fix network in your config dir, then memorystore should go in the right network

https://github.com/google/clusterfuzz/blob/dd48705324f2f86856565516751c5be62d289fbb/configs/test/redis/memorystore-instance.jinja#L21

if you dont want redis, might need to comment out few lines in deploy.py
https://github.com/google/clusterfuzz/blob/7b34b465a94844cf8ae2fae6326dee42273ed0ea/src/local/butler/deploy.py#L84
and
https://github.com/google/clusterfuzz/blob/7b34b465a94844cf8ae2fae6326dee42273ed0ea/src/local/butler/deploy.py#L267
we can put this behind flag, but try first suggestion to use the right network.

**Comment by urbanenomad** [comment]
awesome thanks!

Won

**Comment by urbanenomad** [comment]
Ok...so I removed the redis code but it seems that the appEngine still needs the Serverless VPC Access connector which fails since the redis build handles that and that the we need to create that separately in the host project.  I  had to create that by hand and then modify the app.yaml and cron-service.yaml in the config file and for now just hard coded the vpc-access connector.  I was wondering if the memorystore is not created do we still need this vpc-access connector?

**Comment by inferno-chromium** [comment]
It is just used for memorystore, so that vpc connector can be removed.

Nice it worked, was just curious if changing network to right one (in clusterfuzz/configs/test/redis/memorystore-instance.jinja), did that work. since that allows to use redis as intended without modifying code.

**Comment by urbanenomad** [comment]
ok...I think I have a better idea of how to do this.  I can create the default VPC for the appEngine and memorystore to run on.  And I can deploy the VMs in the private shared VPC.  Does the fuzzing VMs need to have direct access to the memorystore?  Can I keep the appEngine and memorystore on seperate VPCs from the fuzzing VMs?

**Comment by urbanenomad** [comment]
So I have gotten bots deployed using the private shared VPC subnet but leveraged appEngine and memorystore deployed with service project's default VPC.  But now I am seeing that the bots are deployed in the host project's private ips with no NATs but this VPC has a VPN that should allow to route traffic out to the internet.   How does these VMs notify to appEngine that they are up and running?  It looks like these VMs are up and running but the bots page doesn't show anything.
