### ISSUE TITLE
Clean up unused libraries

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#159]
We may have a bunch of pip packages that we don't use anymore, such as pycrypto.

**Comment by inferno-chromium** [comment]
yes @mbarbella-chromium was mentioning that as well. I think when we removed HTTPSServer support to serve testcases from, we probably forgot to remove pycrypto.

**Comment by inferno-chromium** [comment]
had to revert ssl module in https://github.com/google/clusterfuzz/commit/c44bf3f81d19148548a913e6585101c5d9241585

**Comment by inferno-chromium** [comment]
We can keep this open to check others. Wished there was a tool for this :)
