### ISSUE TITLE
Using Shared VPC VMs

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#1642]
So I got clusterfuzz appEngine and memorystore in a Service project's default VPC and we configured the GCE VMs to run on a shared subnet from a Host project where we attached the Service project to this Host project and gave permissions to the service  project's service accounts to use the private subnet.  The host project has a VPN connection and all internet traffic is funneled back into our corporate network for any egress out to the internet through our corporate NATs that are monitored.

So I see that the VMs were created on the custom subnet and we removed the NATs from the clusters.yaml file's instance templates so all traffic out bound is via our corporate NATs.  I am not completely clear how the VMs get registered in the bot page of the clusterfuzz website.  I don't see the VMs there even though the VMs are up and running in the service project.  I suspect this maybe due to the appEngine and the memorystore are on the service project's default VPC while the VMs are on a private VPC on the shared VPC?  How does the bot page get updated with the VMs?

**Comment by inferno-chromium** [comment]
Memorystore is just an optimization, it does not impact any part of running system.
For bots to show up on /bots page, bots need to be able to talk to appengine. Does the bot logs show that they are leasing tasks from appengine and running them. If yes, they are talking to appengine, that feels weird that you dont see anything on bots page. Did you try this heartbleed example ?

**Comment by urbanenomad** [comment]
how does VMs talk to appengine?  In this situation they don't have direct VPC access to each other since appEngine is not in the shared VPC.  The only way they would be able to talk to appEngine is via public endpoints.  Is that how the VMs talk to appEngine or is there some backend access they need to have?  Also is it possible to deploy VMs in other environments such as on-premise how do they talk back to appEngine?

**Comment by inferno-chromium** [comment]
VMs talk to the Appengine through the public endpoint.
Maybe this is what you are looking for
https://cloud.google.com/vpc/docs/configure-serverless-vpc-access

**Comment by urbanenomad** [comment]
Ok from GCP support it looks like this app is running AppEngine Standard and only AppEngine Flex can use Shared VPC.  

https://cloud.google.com/vpc/docs/shared-vpc#resources_that_can_be_attached_to_shared_vpc_networks_from_a_service_project

https://cloud.google.com/appengine/docs/flexible/python/using-shared-vpc

When you say the VMs talk to Appengine through the public endpoint you mean the VMs makes calls to the default public appEngine endpoint?  But then how does it get past IAM in my case IAP?  

So I already notice in your appEngine app.yaml file that you guys are already using vpc_access_connector which is something we can't do with the standard AppEngine for shared VPC.  We would have to deploy this app using AppEngine Flexible in order to use shared VPC.  I assume there is no thoughts of using AppEngine Flexible?  Or even better yet turn your app into a kubernetes app?

**Comment by oliverchang** [comment]
Bots do not talk to App Engine directly. Rather communication is done via GCP services such as Pub/Sub and Datastore.

There should be no need to connect anything directly between App Engine and bots. For bots to show up on /bots, they just need to be able to access Datastore.

**Comment by urbanenomad** [comment]
ok so not sure why the VMs don't show up in the bots page because these VMs are running in the shared VPC subnet and the /manage-vms cron job is able to spin them up and I see them in the VM instances page but they do not show up in the bots page.  The VMs also have full API access in the scopes so I am not sure why they don't show up in the bots page.

**Comment by urbanenomad** [comment]
ok after some further investigation on the VMs I found the error below.  We are using VPC service controls to lock down access to the service project resources based on IP address in both this project and it's host project.  This seems to happen during the startup script for the VM.

------
Mar 23 03:41:12 clusterfuzz-linux-94sz systemd[1]: Started Start ClusterFuzz.
Mar 23 03:41:12 clusterfuzz-linux-94sz bash[848]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Mar 23 03:41:12 clusterfuzz-linux-94sz bash[848]:                                  Dload  Upload   Total   Spent    Left  Speed
Mar 23 03:41:12 clusterfuzz-linux-94sz bash[848]: [158B blob data]
Mar 23 03:41:13 clusterfuzz-linux-94sz bash[848]: Error response from daemon: Get https://gcr.io/v2/clusterfuzz-images/base/manifests/c44bf3f-201902112042: denied: Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier: c45c76a3f28239f8
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 03:41:13 clusterfuzz-linux-94sz docker[862]: Error: No such container: clusterfuzz
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Control process exited, code=exited status=1
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Failed with result 'exit-code'.
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Consumed 199ms CPU time
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Service RestartSec=100ms expired, scheduling restart.
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Scheduled restart job, restart counter is at 5.
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: Stopped Start ClusterFuzz.
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Consumed 199ms CPU time
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Start request repeated too quickly.
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: clusterfuzz.service: Failed with result 'exit-code'.
Mar 23 03:41:13 clusterfuzz-linux-94sz systemd[1]: Failed to start Start ClusterFuzz.
------

I removed GCR from the VPC sc but this error still occurs.  Is the https://gcr.io/v2/clusterfuzz-images/base/manifests/c44bf3f-201902112042 located in a public registry?

**Comment by inferno-chromium** [comment]
Yes these images are in a public registry, you can build your own images [see docker/build.sh or copy from public one into your own project] and then subsitute those in clusters.yaml file.

**Comment by urbanenomad** [comment]
ok so I copied the docker registry for the base linux over to our own gcr instances and that seems to allow for the bot VMs in the shared VPC to start up properly.  I uploaded the heartbleed example and it doesn't seem to test that job.  When I ssh and docker exec into clusterfuzz docker container on the bot VM I see the follwing error in the following location.  /mnt/scratch0/clusterfuzz/bot/logs

--
2020-03-24 00:55:00,211 - run_bot - INFO - Checking source code for updates.
2020-03-24 00:55:00,335 - run_bot - INFO - Local source code version: 20200323231538-utc-b4d69d87-wkim.
2020-03-24 00:55:00,336 - run_bot - INFO - Remote source code version: 20200323231538-utc-b4d69d87-wkim.
2020-03-24 00:55:00,336 - run_bot - INFO - Remote souce code <= local source code. No update.
2020-03-24 00:55:00,336 - run_bot - INFO - Running platform initialization scripts.
2020-03-24 00:55:00,847 - run_bot - INFO - Completed running platform initialization scripts.
2020-03-24 00:55:04,384 - run_bot - ERROR - Failed to get any fuzzing tasks. This should not happen.
None
--

Also I noticed that the bots page seems to not clean up bots that have died.  I went away for a couple of hours and when I returned I see 3 VMs (1 on-demand and 2 premeptibles) in the VM google web console but when I look in the bots page I see 6 VMs and 3 of them are old ones that no longer exist.  How does the bots get notified of a new job and where does it pick it up?

**Comment by inferno-chromium** [comment]
Did you associate the fuzzer with a job ? that is usually the issue that there are no fuzzing task in pubsub queue.
/bots page just shows deleted bots, it does not remove them.

**Comment by oliverchang** [comment]
Hi, was this ever resolved?

**Comment by urbanenomad** [comment]
Sorry just looking over some of the issues I had written before and I never responded to this question.  We ended up not using a Shared VPC but opted to just stick with the public endpoints to keep things simple.  It was getting a bit too complex to get this to work.  We may still try to do this as we start looking to use this for more high profile testing code...but for now we tabled this idea.
