### ISSUE TITLE
Update configs/test startup scripts for Py2>3 samples

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#1654]

**Comment by oliverchang** [comment]
@mbarbella-chromium Could you please help with with the macOS and Android startup script/bot changes?

**Comment by mbarbella-chromium** [comment]
Sure, I can take a look.

**Comment by inferno-chromium** [comment]
need probably this in other platform startup script -https://github.com/google/clusterfuzz/pull/1666

**Comment by mbarbella-chromium** [comment]
Good point. I'll add it when editing them.
