### ISSUE TITLE
what is lost when running clusterfuzz locally?

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#1667]
I have not fully run the local clusterfuzz with full testing since I am the cloud architect evalulating clusterfuzz for our corporate engineers and I only were able to deploy on a local laptop.  We want to understand what features or capabilities are lost if we run clusterfuzz locally as compared to deploying into GCP?  I get that we won't be able to easily scale up the VMs and we are limited by the number of VMs that we have running in our local deployment.  But what other optimizations or features are lost when we run clusterfuzz locally?

**Comment by Dor1s** [comment]
Please see the list of GCP services documented in https://google.github.io/clusterfuzz/architecture/#requirements

At a high level, scalability and statistics are the main features you'll be missing with a local CF instance.

Also see https://github.com/google/clusterfuzz/issues/1375 and follow https://github.com/google/clusterfuzz/issues/1402 for better documentation on this topic.

**Comment by urbanenomad** [comment]
Ok that is kind of what I suspected.  I have been running several clusterfuzz instances for testing to see if we can provide this as a service for our engineers to use.  Some engineers were debating whether to run this in the cloud or whether to run it on premise and I needed to have a good explanation of what the benefit of running in the cloud is.  I personally am not a fuzzing expert so can't address how many bots are needed for how complex the testing and what is being testd, I am just a cloud architect trying to see how we can secure this service for our engineers to start using.  I also assume the ease of maintaining the service in the cloud would be easier since we don't have to worry about VMs going down when we move to a serverless and cloud managed architecture with appEngine and the other GCP services.

**Comment by inferno-chromium** [comment]
Cloud provides all the scalability, reliability and performance of ClusterFuzz since that is where it is run in production. Local setup wont scale and is not tested/supported beyond a few clients-one server model. Local setup wont have any access control (like emails/domains) which is needed for security vulns. In local setup, we use cloud emulators which are only written with testing in mind and not for production workload. And in local setup, we dont have Bigquery which is key service for crash and fuzzer statistics. When develop write fuzzer, stats are critical to tell which mistakes they did and then improve upon it.

**Comment by urbanenomad** [comment]
So technically this service only properly runs in GCP.  Thanks for the clarification, I will bring this up to our engineers.

**Comment by Dor1s** [comment]
To add on top of the previous comment, a local instance makes sense for a single user use case (e.g. doing fuzzing / security research) or for some sort of trial of ClusterFuzz -- just to get basic sense of it. If you consider using CF inside an organization, with multiple users and presumably many fuzzers and VMs (in the long run), then yes, "production" instance (i.e. deployed in Cloud) is the best way to move forward.

In production deployments, the vast majority of the expenses goes is paid for the GCE -- these are fuzzing VMs -- and these can actually be on premise without any severe limitations.

Coincidentally, a few weeks ago I was doing some calculations, and came up with the following estimate. Please do not take it too seriously, I've spent a few minutes working on it, it might be not very precise. Running ClusterFuzz in GCP with 500 fuzzing VMs (400 preemptibles and 100 regular) would cost roughly $80,000 per year, where $70,000 are GCE expenses (i.e. fuzzing VMs aka bots), and the rest $10,000 are other GCP expenses which are "required" for the production instance.
