### ISSUE TITLE
_check_last_get_build_time is wrong

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1671]
Noticed while investigating https://github.com/google/oss-fuzz/issues/3537

The builds were actually missing for <= 2 days, i.e. just one day was missing.

# Hypothesis 1

The code doesn't respect timezones.

The cron task ran on 3/24/20, 3:00 AM PT or 10:00 AM UTC.

The last build (e.g. for zlib) was dated 3/22/20, 8:56:10 PM UTC-7 (i.e. PT) and that's how the code could've thought it was 2 days difference. It would have ignored the time then (used just dates), which I'm not sure is the case.

# Hypothesis 2

Something's wrong with `TIMESTAMP_PATTERN` regex used in `get_build_time` helper. Not sure about this either, still haven't figured out where `build['finish_time']` comes from.

# Hypothesis 3

Something else?

**Comment by oliverchang** [comment]
The builds status cron was also red for a long time (https://builder.oss-fuzz.com/job/infra/job/builds_status/), so that's probably why the dates weren't updated in time and caused this to be triggered.

**Comment by Dor1s** [comment]
I see. This means no issues on ClusterFuzz side, and OSS-Fuzz side we'll hopefully fix/improve as a part of https://github.com/google/oss-fuzz/issues/3538.

Thanks, Oliver!
