### ISSUE TITLE
Add links to fuzzing resources in documentation

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#168]
We should add more links to tutorials for fuzzing to our documentation for people who may not be as familiar with it.

**Comment by Sai-Adarsh** [comment]
@oliverchang Shall I work on this?

**Comment by Dor1s** [comment]
Something like these? Mostly taken from OSS-Fuzz page + a new structure aware fuzzing one.

* [libFuzzer documentation](http://libfuzzer.info)
* [libFuzzer tutorial](http://tutorial.libfuzzer.info)
* [libFuzzer workshop](https://github.com/Dor1s/libfuzzer-workshop)
* [Chromium Fuzzing Page](https://chromium.googlesource.com/chromium/src/testing/libfuzzer/)
* [Structure-Aware Fuzzing with libFuzzer](https://github.com/google/fuzzer-test-suite/blob/master/tutorial/structure-aware-fuzzing.md)

**Comment by Sai-Adarsh** [comment]
> Something like these? Mostly taken from OSS-Fuzz page + a new structure aware fuzzing one.
> 
> * [libFuzzer documentation](http://libfuzzer.info)
> * [libFuzzer tutorial](http://tutorial.libfuzzer.info)
> * [libFuzzer workshop](https://github.com/Dor1s/libfuzzer-workshop)
> * [Chromium Fuzzing Page](https://chromium.googlesource.com/chromium/src/testing/libfuzzer/)
> * [Structure-Aware Fuzzing with libFuzzer](https://github.com/google/fuzzer-test-suite/blob/master/tutorial/structure-aware-fuzzing.md)

looks good to me.

**Comment by inferno-chromium** [comment]
actually wanted more like what fuzzing is and more overview stuff. above links are already in libfuzzer/afl documentation.

**Comment by Sai-Adarsh** [comment]
> 
> 
> actually wanted more like what fuzzing is and more overview stuff. above links are already in libfuzzer/afl documentation.

Like these?

* [Fuzz testing: Beginner’s guide](https://medium.com/ouspg/fuzz-testing-beginners-guide-da2c9179caa7)
* [Complete Guide to Fuzzing](https://www.cybrary.it/2017/08/your-complete-guide-to-fuzzing/)
* [15 minute guide to fuzzing](https://www.mwrinfosecurity.com/our-thinking/15-minute-guide-to-fuzzing/)
* [Curated list of fuzzing resources](https://github.com/secfigo/Awesome-Fuzzing)

**Comment by Sai-Adarsh** [comment]
> 
> 
> > actually wanted more like what fuzzing is and more overview stuff. above links are already in libfuzzer/afl documentation.
> 
> Like these?
> 
>     * [Fuzz testing: Beginner’s guide](https://medium.com/ouspg/fuzz-testing-beginners-guide-da2c9179caa7)
> 
>     * [Complete Guide to Fuzzing](https://www.cybrary.it/2017/08/your-complete-guide-to-fuzzing/)
> 
>     * [15 minute guide to fuzzing](https://www.mwrinfosecurity.com/our-thinking/15-minute-guide-to-fuzzing/)
> 
>     * [Curated list of fuzzing resources](https://github.com/secfigo/Awesome-Fuzzing)

@inferno-chromium could you check if these are the resources your are expecting?
