### ISSUE TITLE
chromium-ml-with-gpu docker image is completely broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#1686]
This probably needs to be looked once we have cycles. Putting errors here for reference, right now image does not boot at all.

```
[  111.694330] docker[1071]: [WARNING 2020-03-28 06:04:01 UTC] Error fetching gpu-driver-signature.tar.gz from https://storage.googleapis.com/cos-tools/12871.59.0/gpu-driver-signature.tar.gz, retrying
[  112.787206] docker[1071]: curl: (22) The requested URL returned error: 404
```
```
[  117.773829] docker[1071]: [WARNING 2020-03-28 06:04:07 UTC] Error fetching GPU installer from https://us.download.nvidia.com/tesla/384.130/NVIDIA-Linux-x86_64-384.130.run, retrying
[  119.222680] docker[1071]: curl: (22) The requested URL returned error: 404
```

**Comment by oliverchang** [comment]
@Dor1s FYI

**Comment by Dor1s** [comment]
Not the error I anticipated, but anyway I thought it would break (even if the drivers were still available).

Please disable GPU bots and ML model training task for now. I'll upgrade all the deps when I can (most likely in summer).

Let's not disable the strategy though, the existing models should be useful for the majority of fuzz targets.

**Comment by Dor1s** [comment]
duping into https://github.com/google/clusterfuzz/issues/1540
