### ISSUE TITLE
Retry logic in storage.py

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1737]
Filing this to clarify whether I misunderstand it or we need to fix something.

Once in a while we get the following exception: https://console.cloud.google.com/errors/CIuh6-K0uKWFNw?time=P30D&project=clusterfuzz-external

It comes from https://github.com/google/clusterfuzz/blob/e0c6ad071951c403d17ef11a3020ca75b4bf9a09/src/appengine/handlers/cron/corpus_backup.py#L65

Which calls into https://github.com/google/clusterfuzz/blob/e0c6ad071951c403d17ef11a3020ca75b4bf9a09/src/python/google_cloud_utils/storage.py#L786

which calls into https://github.com/google/clusterfuzz/blob/e0c6ad071951c403d17ef11a3020ca75b4bf9a09/src/python/google_cloud_utils/storage.py#L253

and the particular failing operation is https://github.com/google/clusterfuzz/blob/e0c6ad071951c403d17ef11a3020ca75b4bf9a09/src/python/google_cloud_utils/storage.py#L263

If I check the logs, I see the request that was sent prior to the copy operation (setting ACL): https://console.cloud.google.com/logs/viewer?resource=gae_app%2Fmodule_id%2Fcron-service%2Fversion_id%2F20200410t180004&logName=projects%2Fclusterfuzz-external%2Flogs%2Fapp&expandAll=false&timestamp=2020-04-12T03%3A26%3A25.013000000Z&project=clusterfuzz-external&minLogLevel=0&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.project_id%3D%22clusterfuzz-external%22%0Aresource.labels.version_id%3D%2220200410t180004%22%0Aresource.labels.module_id%3D%22cron-service%22%0Atimestamp%3D%222020-04-12T03%3A25%3A44.899340000Z%22%0AinsertId%3D%22gddy5ufk382zt%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-04-12T03%3A25%3A55.876537987Z

and that request happens 10 second earlier than when the copy error is recorded, even though we use the following constants:

```
# The number of retries to perform some GCS operation.
DEFAULT_FAIL_RETRIES = 8

# The time to wait between retries while performing GCS operation.
DEFAULT_FAIL_WAIT = 2
```

and the time interval between the previous request and the error should be 14+ seconds at least, but actually even more given that the copy error is `google.api_core.exceptions.GatewayTimeout` which is also a few seconds at least?

**Question**

Does the retry logic actually work? How can I verify it? Or do I miss something important in my debugging?

**Comment by oliverchang** [comment]
Very nice catch! 

Seems like refactoring broke this -- we weren't actually retrying at all on the majority of operations here. Uploaded #1739 to fix this.
