### ISSUE TITLE
install_deps.bash: pipenv not found

### ISSUE THREAD

**Issue by mykter** [google/clusterfuzz#1740]
When running install_deps.bash on Ubuntu 18.04 I get:
E: Unable to locate package pipenv

I commented out that line (as I have pipenv already) and the rest of the script runs fine.

**Comment by oliverchang** [comment]
Did you run `local/install_deps.bash` ? We have dependencies in two main places, the Pipfile and our vendored dependencies from src/requiremenents.txt. To install the second one, `python butler.py bootstrap` should also work.

**Comment by mykter** [comment]
Thanks, I had run it but it failed and I didn't notice. Updated to reflect that issue instead.

**Comment by mykter** [comment]
thanks!
