### ISSUE TITLE
Bot list empty on default Production setup

### ISSUE THREAD

**Issue by asudhak** [google/clusterfuzz#1754]
I've set up a production instance and i've checked that the /manage-vms cron job has run and I can see the 3 default VMs in here : https://console.cloud.google.com/compute/instances

I did see an AppEngine error about something related,

`handlers.cron.helpers.bot_manager.NotFoundError: <HttpError 404 when requesting https://compute.googleapis.com/compute/v1/projects/xxxx/global/instanceTemplates/clusterfuzz-linux?alt=json returned "The resource 'projects/xxxx/global/instanceTemplates/clusterfuzz-linux' was not found">
at execute (/srv/handlers/cron/helpers/bot_manager.py:154)
at _wrapper (python/base/retry.py:89)`

but the instance template is indeed present, and I've not seen that error since.

Anything I can do here to debug?

**Comment by asudhak** [comment]
There were no interesting stackdriver logs, so I ssh'd into the VM. AFAICT, the bot is not running 

`asudhakar@clusterfuzz-linux-qx13 ~ $ docker images
REPOSITORY                       TAG                    IMAGE ID            CREATED             SIZE
gcr.io/clusterfuzz-images/base   ce67e3c-202004060711   8242f939b3f2        3 weeks ago         4.15GB

asudhakar@clusterfuzz-linux-qx13 ~ $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
asudhakar@clusterfuzz-linux-qx13 ~ $ ps ax | grep python
    355 ?        Ss     0:03 /usr/bin/python2.7 /usr/lib/python-exec/python2.7/google_network_daemon
    356 ?        Ss     0:01 /usr/bin/python2.7 /usr/lib/python-exec/python2.7/google_clock_skew_daemon
    357 ?        Ss     0:03 /usr/bin/python2.7 /usr/lib/python-exec/python2.7/google_accounts_daemon
 682381 ?        R      0:00 python2 /usr/bin/../lib/google-cloud-sdk/bin/bootstrapping/gsutil.py...
asudhakar@clusterfuzz-linux-qx13 ~ $ ps ax | grep butler
 683008 pts/0    S+     0:00 grep --colour=auto butler`

This deployment is from tag/v1.9.0

**Comment by inferno-chromium** [comment]
Can you do `journalctl` on the vm to see where it is failing. It should be pulling docker image and then running it, something is going wrong.

**Comment by asudhak** [comment]
hmm, looking at my deployment, i'm getting some failures that I may have overlooked before

`Running: gsutil cp deployment/windows-3.zip gs://deployment.vfuzz-275401.appspot.com/windows-3.zip
| BucketNotFoundException: 404 gs://deployment.xxx.appspot.com bucket does not exist.
| Return code is non-zero (1).
| Exit.`

I'm not sure why the deployment bucket wasn't created. I may try to redeploy everything from scratch to ensure that I didn't miss anything. I will re-open if the issue persists.
