### ISSUE TITLE
pipenv shell

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#1814]
Hey I am new to pipenv so I am trying to create a docker file that can consistenly deploy a clusterfuzz cluster.  I have been able to run the requisites and run the local/install_deps.bash.  But when I try to get into an interactive shell in the container and I try to run the pipenv shell command  as the documentation states, it says "bash: pipenv: command not found".  It isn't clear how pipenv gets installed.  Any guidance would be greatful.

**Comment by inferno-chromium** [comment]
in root of clusterfuzz dir,

python3 -m pip install --user pipenv
python3 -m pipenv --python $PYTHON_VERSION
python3 -m pipenv sync --dev

then just
python3 -m pipenv shell

you should just run ./local/install_deps.bash to install pipenv.

**Comment by urbanenomad** [comment]
So I have a docker image that completed the local/install_deps.bash script already.  So then I want to be able to do a docker run locally and map my local gcloud config to the docker image config so that I can run commands in the container.  

I ran the commands you listed above and I am getting a tensorflow installation error?  Is tensorflow needed with clusterfuzz?  I looked around and it seems there is no library that supports python3.7.

In any case I got the pipenv shell to work, but now I still get this error when running butler.py

python butler.py create_config --oauth-client-secrets-path=$CLIENT_SECRETS_PATH \
  --firebase-api-key=$FIREBASE_API_KEY --project-id=$PROJECT_ID $CONFIG_DIR

Traceback (most recent call last):
  File "butler.py", line 316, in <module>
    main()
  File "butler.py", line 301, in main
    command = importlib.import_module('local.butler.%s' % args.command)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/local/butler/create_config.py", line 27, in <module>
    from googleapiclient import discovery
ModuleNotFoundError: No module named 'googleapiclient'
(clusterfuzz) cfzuser@eb52fed03a65:/opt/local/clusterfuzz$ 

Does pipenv not install this module?  Do I need to configure this myself?

**Comment by inferno-chromium** [comment]
> So I have a docker image that completed the local/install_deps.bash script already. So then I want to be able to do a docker run locally and map my local gcloud config to the docker image config so that I can run commands in the container.
> 
> I ran the commands you listed above and I am getting a tensorflow installation error? Is tensorflow needed with clusterfuzz? I looked around and it seems there is no library that supports python3.7.

Are you using master branch for latest code. We have tensorflow = "==2.2.0rc4" in there which works with python 3.7

> 
> In any case I got the pipenv shell to work, but now I still get this error when running butler.py
> 
> python butler.py create_config --oauth-client-secrets-path=$CLIENT_SECRETS_PATH
> --firebase-api-key=$FIREBASE_API_KEY --project-id=$PROJECT_ID $CONFIG_DIR
> 
> Traceback (most recent call last):
> File "butler.py", line 316, in
> main()
> File "butler.py", line 301, in main
> command = importlib.import_module('local.butler.%s' % args.command)
> File "/usr/local/lib/python3.7/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "src/local/butler/create_config.py", line 27, in
> from googleapiclient import discovery
> ModuleNotFoundError: No module named 'googleapiclient'
> (clusterfuzz) cfzuser@eb52fed03a65:/opt/local/clusterfuzz$

Did you run python butler.py bootstrap first. check with python3 -m pip freeze that this lib is there.

> 
> Does pipenv not install this module? Do I need to configure this myself?

**Comment by urbanenomad** [comment]
Thanks I tried to run the python butler.py boostrap and now I get the following error.  Am I not in the right path to run this command?  I assume I need to be in the root of the clusterfuzz local git.  Here is the error message.  BTW I just rebuilt the docker image with the master version of clusterfuzz.
------------
...
| bower shadycss#^1.0.6                          cached https://github.com/webcomponents/shadycss.git#1.9.1
| bower shadycss#^1.0.6                        validate 1.9.1 against https://github.com/webcomponents/shadycss.git#^1.0.6
| bower iron-a11y-keys-behavior#^2.0.0          ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/PolymerElements/iron-a11y-keys-behavior.git", exit code of #128 fatal: Not a git repository: ../.git/modules/clusterfuzz
| 
| Additional error details:
| fatal: Not a git repository: ../.git/modules/clusterfuzz
| Return code is non-zero (1).
| Exit.
(clusterfuzz) cfzuser@b8dbe4e77cbc:/opt/local/clusterfuzz$
