### ISSUE TITLE
Is there a way to change URL?

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#1817]
I am deploying the clusterfuzz in GCP and using IAP and not using Firebase for authentication.  I got it working with the URL clusterfuzzapp.appspot.com.  I want to switch this to use our corporate subdomain name.  

I was able to setup a public hosted zone and I am in the process of having our corporate DNS team point to the hosted zone's name servers for a subdomain to our corporate domain.  I can then use the appEngine to use a custom domain name and use the CNAME verification process.  I was wondering once I do this if there needs to be any other activities to make this work with a custom domain name.  Do you guys have any documentation on how to configure this?  Can we configure this in the deployment of the cluster?

thanks

Won

**Comment by inferno-chromium** [comment]
@oliverchang - thoughts ?

**Comment by oliverchang** [comment]
If you set add custom URL in your App Engine console, I believe it should just work assuming the DNS is set up correctly. You can additionally set https://github.com/google/clusterfuzz/blob/master/configs/test/gae/config.yaml#L19 if you want automatic redirects etc.

**Comment by oliverchang** [comment]
Let us know if you run into any issues. In the meantime I'm closing this as there seems to be nothing more outstanding here.
