### ISSUE TITLE
Trying to create cluster but getting FailedToDecompressContent

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#1819]
So trying to run the create project as well as update project and I am getting this error. 

-----------------------
 Beginning deployment of service [cron-service]...
| ╔════════════════════════════════════════════════════════════╗
| ╠═ Uploading 0 files to Google Cloud Storage                ═╣
| ╚════════════════════════════════════════════════════════════╝
| File upload done.
| Updating service [cron-service]...
| ............................................................................................................................................................................................................................................................................................................................done.
| Setting traffic split for service [cron-service]...
| ...................................done.
| Deployed service [cron-service] to [https://cron-service-dot-clusterfuzzsbx6.uc.r.appspot.com]
| Updating config [index]...
| .......
| done.
| done.
| Updating config [cron]...
| .failed.
| ERROR: gcloud crashed (FailedToDecompressContent): Content purported to be compressed with gzip but failed to decompress.
| 
| If you would like to report this issue, please run the following command:
|   gcloud feedback
| 
| To check gcloud for common problems, please run the following command:
|   gcloud info --run-diagnostics
| Return code is non-zero (1).
gcloud deployment failed, retrying...
Running: gcloud app deploy --no-stop-previous-version --quiet --project=clusterfuzzsbx6  src/appengine/index.yaml src/appengine/app.yaml src/appengine/cron.yaml src/appengine/cron-service.yaml

Not sure why this keeps failing, any idea?

**Comment by urbanenomad** [comment]
This seems to prevent the deployment of cron-services and doesn't create all the buckets needed by clusterfuzz.  Any idea why this is happening?  I tried running this with the most current master as well as with v2.0.1.

**Comment by inferno-chromium** [comment]
What is 
gcloud --version
python3 --version
and OS version ?
check git status if there are any weird extra files in your checkout ?
are you deploying from inside the pipenv shell ?
can you try removing pipenv using:
python3 -m pipenv --rm
./local/install_deps.bash again

**Comment by urbanenomad** [comment]
What is
gcloud --version: Google Cloud SDK 296.0.0
python3 --version 3.7
and OS version debian stretch
check git status if there are any weird extra files in your checkout ?  
are you deploying from inside the pipenv shell ? Yes

I am using a docker image that installs all the prerequisites so I can create new clusters 

Here is the dockerfile 

`FROM python:3.7-stretch

SHELL ["/bin/bash", "-c"]

RUN apt-get update; \
	apt-get install -y \
	lsb-release \
	ca-certificates \
	sudo \
	vim \
	git 

#Configure User account to use going forward
RUN groupadd -g 999 cfzuser && \
	useradd -r -u 999 -g cfzuser cfzuser && \
	mkdir -p /home/cfzuser && \
	chown cfzuser:cfzuser /home/cfzuser
RUN echo "cfzuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER cfzuser

RUN sudo mkdir -p /opt/local && \
	sudo chown cfzuser:cfzuser /opt/local

#Install gcloud  
RUN export CLOUD_SDK_REPO="cloud-sdk-stretch" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | \
    	sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    	sudo apt-key add -

RUN sudo apt-get update && \
	sudo apt-get install -y \
    google-cloud-sdk \
    google-cloud-sdk-app-engine-go \
    google-cloud-sdk-app-engine-python \
    google-cloud-sdk-app-engine-python-extras \
    google-cloud-sdk-datastore-emulator \
    google-cloud-sdk-pubsub-emulator 


#Install Go
RUN cd /tmp && \
	curl https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz --output go.tar.gz && \
	tar -C /opt/local -xzf go.tar.gz
ENV PATH="/opt/local/go/bin:${PATH}"

#install clusterfuzz
RUN mkdir -p /opt/local/conf; cd /opt/local && \
	git clone https://github.com/google/clusterfuzz 

RUN	cd /opt/local/clusterfuzz && \
	git checkout tags/v2.0.1

RUN cd /opt/local/clusterfuzz && \
	bash local/install_deps.bash 

WORKDIR /opt/local/clusterfuzz`

**Comment by inferno-chromium** [comment]
Probably try adding --verbosity=debug to this command in deploy.py and see if verbose output points to something more debuggable. We have never run across this across 3 big clusterfuzz instances, so cannot debug from our side.

src/local/butler/deploy.py:        'gcloud app deploy %s --quiet '

**Comment by urbanenomad** [comment]
Here is the error log.

| Deployed service [cron-service] to [https://cron-service-dot-clusterfuzzsbx6.uc.r.appspot.com]
| Updating config [index]...







| .......
| done.
| done.


| Updating config [cron]...
| DEBUG: Host: appengine.google.com

| DEBUG: _Authenticate configuring auth; needs_auth=False
| DEBUG: Sending request to https://appengine.google.com/api/cron/update?app_id=clusterfuzzsbx6 headers={'X-appcfg-api-version': '1', 'content-length': '2519', 'Content-Type': 'application/octet-stream'} body=cron:
| - description: Obtain code coverage information from the coverage GCS bucket.
|   schedule: every day 18:30
|   target: cron-service
|   url: /fuzzer-coverage
| - description: Backup
|   schedule: every day 01:47
|   target: cron-service
|   url: /backup
| - description: Build crash stats.
|   schedule: every 5 minutes
|   target: cron-service
|   url: /build-crash-stats
| - description: Cleanup.
|   schedule: every 1 minutes
|   target: cron-service
|   url: /cleanup
| - description: Make corpus backups public.
|   schedule: every day 03:00
|   target: cron-service
|   url: /corpus-backup/make-public
| - description: Exercise cache on the fuzzer stats page.
|   schedule: every 7 minutes
|   target: cron-service
|   url: /fuzzer-stats/cache
| - description: Load important stats from yesterday into the cache.
|   schedule: every day 04:30
|   target: cron-service
|   url: /fuzzer-stats/preload
| - description: Adjust target and job weights based on fuzzer stats.
|   schedule: every day 03:00
|   target: cron-service
|   url: /fuzzer-and-job-weights
| - description: Adjust strategy selection weights based on strategy stats.
|   schedule: every day 05:00
|   target: cron-service
|   url: /fuzz-strategy-selection
| - description: Load BigQuery stats.
|   schedule: every day 01:00
|   target: cron-service
|   url: /load-bigquery-stats
| - description: Manage VMs.
|   schedule: every 30 minutes
|   target: cron-service
|   url: /manage-vms
| - description: Schedule corpus pruning task.
|   schedule: every day 19:00
|   target: cron-service
|   url: /schedule-corpus-pruning
| - description: Schedule impact tasks.
|   schedule: every day 09:00
|   target: cron-service
|   timezone: US/Pacific
|   url: /schedule-impact-tasks
| - description: Train ML model.
|   schedule: every tuesday 09:00
|   target: cron-service
|   url: /schedule-ml-train-tasks
| - description: Schedule progression tasks.
|   schedule: every day 07:00
|   target: cron-service
|   timezone: US/Pacific
|   url: /schedule-progression-tasks
| - description: Upload reports task.
|   schedule: every 3 hours
|   target: cron-service
|   url: /schedule-upload-reports-tasks
| - description: Pull blame results from the Predator service.
|   schedule: every 5 minutes
|   target: cron-service
|   url: /predator-pull
| - description: Exercise cache on the testcase list page.
|   schedule: every 7 minutes
|   target: cron-service
|   url: /testcases/cache
| - description: File bugs for open test cases.
|   schedule: every 1 hours
|   target: cron-service
|   url: /triage
| - description: Sync admin users.
|   schedule: every 1 hours
|   target: cron-service
|   url: /sync-admins
| 
| INFO: Attempting refresh to obtain initial access_token
| INFO: Refreshing access_token



| .failed.
| DEBUG: Content purported to be compressed with gzip but failed to decompress.
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
|     resources = calliope_command.Run(cli=self, args=args)
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
|     resources = command_instance.Run(args)
|   File "/usr/lib/google-cloud-sdk/lib/surface/app/deploy.py", line 117, in Run
|     default_strategy=flex_image_build_option_default))
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 666, in RunDeploy
|     ac_client.UpdateConfig(config.name, config.parsed)
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_client.py", line 180, in UpdateConfig
|     return self.UpdateCron(parsed_yaml)
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_client.py", line 197, in UpdateCron
|     app_id=self.project, payload=cron_yaml.ToYAML())
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/util.py", line 393, in Send
|     response = self._server.Send(*args, **kwargs)
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/third_party/appengine/tools/appengine_rpc_httplib2.py", line 258, in Send
|     url, method=method, body=payload, headers=headers)
|   File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/oauth2client/transport.py", line 153, in new_request
|     credentials._refresh(orig_request_method)
|   File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/oauth2client/client.py", line 782, in _refresh
|     self._do_refresh_request(http_request)
|   File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/oauth2client/client.py", line 818, in _do_refresh_request
|     body=body, headers=headers)
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/http.py", line 298, in WrappedRequest
|     response = orig_request(*modified_args, **kwargs)
|   File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/oauth2client/transport.py", line 169, in new_request
|     redirections, connection_type)
|   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/http.py", line 298, in WrappedRequest
|     response = orig_request(*modified_args, **kwargs)
|   File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/httplib2/python2/httplib2/__init__.py", line 2161, in request
|     cachekey,
|   File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/httplib2/python2/httplib2/__init__.py", line 1821, in _request
|     conn, request_uri, method, body, headers
|   File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/httplib2/python2/httplib2/__init__.py", line 1792, in _conn_request
|     content = _decompressContent(response, content)
|   File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/httplib2/python2/httplib2/__init__.py", line 526, in _decompressContent
|     content,
| FailedToDecompressContent: Content purported to be compressed with gzip but failed to decompress.
| ERROR: gcloud crashed (FailedToDecompressContent): Content purported to be compressed with gzip but failed to decompress.
| 
| If you would like to report this issue, please run the following command:
|   gcloud feedback
| 
| To check gcloud for common problems, please run the following command:
|   gcloud info --run-diagnostics
| Return code is non-zero (1).
gcloud deployment failed, retrying...
Running: gcloud app deploy --no-stop-previous-version --quiet --verbosity=debug --project=clusterfuzzsbx6  src/appengine/index.yaml src/appengine/app.yaml src/appengine/cron.yaml src/appengine/cron-service.yaml
| DEBUG: Running [gcloud.app.deploy] with arguments: [--no-stop-previous-version: "false", --project: "clusterfuzzsbx6", --quiet: "True", --verbosity: "debug", DEPLOYABLES:4: "[u'src/appengine/index.yaml', u'src/appengine/app.yaml', u'src/appengine/cron.yaml', u'src/appengine/cron-service.yaml']"]

**Comment by inferno-chromium** [comment]
There is some weird response coming from your server. You can add print to see the response coming and debug it, but this is not a clusterfuzz issue.

        raise FailedToDecompressContent(
            _("Content purported to be compressed with %s but failed to decompress.")
            % response.get("content-encoding"),
            response,
            content,
        )
