### ISSUE TITLE
Python 3 migration

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#183]
Adding a tracking bug for Python 3 migration.

The main blocker we have so far is:
- [x] NDB support for Python 3. This appears to be ongoing: https://github.com/googleapis/google-cloud-python/blob/master/ndb/MIGRATION_NOTES.md

**Comment by inferno-chromium** [comment]
Need to move to latest mozprocess version sometime - https://pypi.org/project/mozprocess/#files. As you said, it supports Python 3 now.

**Comment by gpshead** [comment]
FYI the URL for NDB on Python 3 seems to have changed to https://github.com/googleapis/python-ndb/blob/master/MIGRATION_NOTES.md

**Comment by inferno-chromium** [comment]
```
git ls-files | grep requirements.txt | xargs -n1 -t caniusepython3 -r
caniusepython3 -r docker/base/requirements.txt 
Finding and checking dependencies ...

🎉  You have 0 projects blocking you from using Python 3!

caniusepython3 -r docker/ci/requirements.txt 
Finding and checking dependencies ...

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  googledatastore
caniusepython3 -r src/local/requirements.txt 
Finding and checking dependencies ...

🎉  You have 0 projects blocking you from using Python 3!

caniusepython3 -r src/platform_requirements.txt 
Finding and checking dependencies ...

🎉  You have 0 projects blocking you from using Python 3!

caniusepython3 -r src/requirements.txt 
Finding and checking dependencies ...

🎉  You have 0 projects blocking you from using Python 3!
```

**Comment by inferno-chromium** [comment]
I think googledatastore should go away after moving to the new ndb package, right @oliverchang ?

**Comment by oliverchang** [comment]
right, googledatastore will no longer be required afterwards.

**Comment by inferno-chromium** [comment]
Step 1a completed:
```
git ls-files "*.py" | xargs futurize -w -n --stage1 -x libfuturize.fixes.fix_absolute_import
```

**Comment by inferno-chromium** [comment]
Need to enable --py3k in pylint here, but first need help on fixing absolute import things.
```
butler/lint.py:    _execute_command_and_track_error('pylint ' + file_path)
```

**Comment by inferno-chromium** [comment]
Some notes for tracking
```
ml/rnn/generator.py:   rnn_runner = new_process.ProcessRunner('python')
protos/generate.sh: python2 -m grpc_tools.protoc --proto_path=$SCRIPT_DIR --python_out=$SCRIPT_DIR --grpc_python_out=$SCRIPT_DIR $SCRIPT_DIR/*.proto
```

**Comment by inferno-chromium** [comment]
appengine.mail dependency removed in https://github.com/google/clusterfuzz/commit/26bd818f1f176aca373518fce62c26fda2dd6bb9. we now provide support for sendgrid (also one of recommendations by appengine).

**Comment by inferno-chromium** [comment]
Stage 1 migration is now complete with https://github.com/google/clusterfuzz/commit/30169653745d6e629dfab6e13538868e04d44c7e

**Comment by oliverchang** [comment]
ndb still looks like it's in early development based on commits on https://github.com/googleapis/python-ndb ...

to replace the users module, firebase auth looks like the easiest and nicest way forward: https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine 

(from the suggested options on https://cloud.google.com/appengine/docs/standard/python/oauth/ )

**Comment by oliverchang** [comment]
It's unclear if firebase auth has a local emulator of sorts so that people can still do run_server without setting up any real projects though...

Perhaps local server instances could have auth disabled completely (i.e. no auth required) to keep things simple? @inferno-chromium what do you think?

**Comment by inferno-chromium** [comment]
yes no auth for local sounds good. and i had the same idea on firebase, firebase support multiple other auth systems, so that will be great!

**Comment by oliverchang** [comment]
great, I can give firebase auth a shot next week :)

**Comment by oliverchang** [comment]
Rough plan for the remainder of the migration:

- Complete remaining futurize migrations for bot code.
- Add support for using the Python 3 ndb (dynamically based on if we're running on Python 2 or 3).
- Get all tests passing under Python 3, and more generally get our code in a state which makes it easy to run under both Python 2 and 3.
- Find a replacement for App Engine memcache.
- Migrate App Engine deployment to Python 3. Completely remove dependency on App Engine SDK and migrate to App Engine Python 3 Standard.
- Migrate preemptible bot deployment to Python 3, and gradual rollout to non-preemptible.

@mbarbella-chromium WDYT ?

**Comment by mbarbella-chromium** [comment]
The only thing I'd add is to evaluate packages in requirements for Python 3 compaitbility, but that will be part of getting all of the tests passing under Python 3. SGTM overall.

**Comment by oliverchang** [comment]
Current state is that most unit tests pass. All App Engine unit tests pass.

The next steps:
1. Set up CI for Python 3 tests to make sure we don't regress anything.
2. Pick a deployment (chromium?) to dogfood Python 3 appengine.
3. Start staging of Python 3 bots.

**Comment by oliverchang** [comment]
Main part is done here.
