### ISSUE TITLE
js_minimizer is not callable

### ISSUE THREAD

**Issue by iamarshsingh** [google/clusterfuzz#1834]
The following run function of JSMinimizer class is not callable as `js_minimizer` is an object and not a function, thus it should not be callable.

```
    js_tokenizer = AntlrTokenizer(JavaScriptLexer)

    js_minimizer = JSMinimizer(
        utils.test,
        max_threads=thread_count,
        tokenizer=js_tokenizer.tokenize,
        token_combiner=js_tokenizer.combine,
        file_extension=file_extension)

    result = line_minimizer.minimize(data)
    result = js_minimizer(result)
    result = js_minimizer(result)
    result = line_minimizer.minimize(result)
```

Location in codebase [here](https://github.com/google/clusterfuzz/blob/master/src/python/bot/minimizer/js_minimizer.py#L187).

Also, does js_minimizer should be called two times?
I guess `js_minimizer(result)` should be replaced with `js_minimizer.minimize(data)`, but I am not really sure. Can someone please confirm if it is a bug or not?

**Comment by mbarbella-chromium** [comment]
How are you running this code such that you see this error? I don't recall exactly how we've managed to set this up, but objects can be callable. We repeat the calls because we actually want to run the minimizer twice and take the second result, as there are certain types of issues that are not caught by a single pass.

**Comment by iamarshsingh** [comment]
I got the error while using pylint to check this file for any linting issues:

```
************* Module src.python.bot.minimizer.js_minimizer
bot/minimizer/js_minimizer.py:187:13: E1102: js_minimizer is not callable (not-callable)
bot/minimizer/js_minimizer.py:188:13: E1102: js_minimizer is not callable (not-callable)
```

**Comment by oliverchang** [comment]
> How are you running this code such that you see this error? I don't recall exactly how we've managed to set this up, but objects can be callable. We repeat the calls because we actually want to run the minimizer twice and take the second result, as there are certain types of issues that are not caught by a single pass.

I don't see `__call__` defined in https://github.com/google/clusterfuzz/blob/master/src/python/bot/minimizer/js_minimizer.py#L35 or the base class (https://github.com/google/clusterfuzz/blob/master/src/python/bot/minimizer/minimizer.py#L145). @mbarbella-chromium can you please confirm how these are working?
