### ISSUE TITLE
butler.py run_server -getting HttpError 403 "Forbidden"

### ISSUE THREAD

**Issue by Kankarollo** [google/clusterfuzz#1855]
ENV:
Machine: Ubuntu 18.04 - VirtualBox on Windows 10
Python 3.8

I'm trying to run local server instance as it's written in https://google.github.io/clusterfuzz/getting-started/local-instance/.
Everything works fine till executing command:

       python butler.py run_server --bootstrap
        
I receive this error and I am confused because I'm connecting to localhost, so I don't expect authentication error like 403. 

- I tried to do everything on the root user but with no success. 
- Changed ports but no difference.
- This machine is behind proxy, but I've unset HTTP_PROXY, HTTPS_PROXY env variables, set localhost in NO_PROXY, so I'm not sure if this is the problem especially that issues like #334 have different symptoms.

        Traceback (most recent call last):
        File "butler.py", line 316, in <module>
            main()
          File "butler.py", line 302, in main
            command.execute(args)
          File "src/local/butler/run_server.py", line 158, in execute
            test_utils.setup_pubsub(constants.TEST_APP_ID)
          File                 "/home/kanka/Desktop/ClusterFuzz/clusterfuzz/src/python/tests/test_libs/test_utils.py", line         312, in setup_pubsub
            create_pubsub_topic(client, project, queue['name'])
          File         "/home/kanka/Desktop/ClusterFuzz/clusterfuzz/src/python/tests/test_libs/test_utils.py", line         288, in create_pubsub_topic
            if client.get_topic(full_name):
          File         "/home/kanka/Desktop/ClusterFuzz/clusterfuzz/src/python/google_cloud_utils/pubsub.py",         line 198, in get_topic
            response = self._execute_with_retry(request)
          File "/home/pkanka/Desktop/ClusterFuzz/clusterfuzz/src/python/base/retry.py", line         89, in _wrapper
            result = func(*args, **kwargs)
          File         "/home/kanka/Desktop/ClusterFuzz/clusterfuzz/src/python/google_cloud_utils/pubsub.py",         line 108, in _execute_with_retry
            return request.execute()
          File         "/home/kanka/Desktop/ClusterFuzz/clusterfuzz/src/third_party/googleapiclient/_helpers.py"        , line 134, in positional_wrapper
            return wrapped(*args, **kwargs)
          File         "/home/kanka/Desktop/ClusterFuzz/clusterfuzz/src/third_party/googleapiclient/http.py",         line 907, in execute
            raise HttpError(resp, content, uri=self.uri)
        googleapiclient.errors.HttpError: <HttpError 403 when requesting         http://localhost:9006/v1/projects/test-clusterfuzz/topics/jobs-linux?alt=json returned "Forbidden">

**Comment by inferno-chromium** [comment]
You probably would have to open these ports - https://github.com/google/clusterfuzz/blob/master/src/local/butler/constants.py#L63

**Comment by Kankarollo** [comment]
Okay, I don't know why this was the case, but I've reinstalled ClusterFuzz and python3.8 and everything works fine. Thanks for help!
