### ISSUE TITLE
install_deps.bash: support Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by l2dy** [google/clusterfuzz#1864]
Would Ubuntu 20.04 become a supported distro?

**Comment by inferno-chromium** [comment]
Yes we want to do this.

@iamarshsingh - can you help with this. Just try making local/install_deps_linux.bash run correctly on a Ubuntu 20.04 docker container.

**Comment by iamarshsingh** [comment]
Sure @inferno-chromium!

**Comment by inferno-chromium** [comment]
Check out related 18.04 which we fixed some time back.
https://github.com/google/clusterfuzz/issues/1781

Basically python butler.py bootstrap
python butler.py run_server should work (localhost:9000 works).

**Comment by inferno-chromium** [comment]
Should be fixed now, use master.
