### ISSUE TITLE
linting in CI works differently than locally

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#188]
I'm pretty sure it is pylint 1.9.4.
See https://github.com/google/clusterfuzz/pull/185 for a discrepancy I noticed between running pylint locally and running it in CI.

When I upgraded my local copy of pylint to 1.9.4 I was able to discover the issue showing up in CI.

**Comment by oliverchang** [comment]
That's really strange...

```bash
$ sudo docker run --rm -ti -v $(pwd)/clusterfuzz:/workspace gcr.io/clusterfuzz-images/ci /bin/bash
root@6bcbbf462031:/workspace# pylint --version
No config file found, using default configuration
pylint 1.9.3, 
astroid 1.6.5
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609]
root@6bcbbf462031:/workspace# pylint src/appengine/handlers/upload_testcase.py
No config file found, using default configuration
************* Module src/appengine/handlers/upload_testcase.py
F:  1, 0: No module named src/appengine/handlers/upload_testcase.py (fatal)
```

**Comment by oliverchang** [comment]
My ENV version is also 1.9.3, but also cannot find this.

**Comment by jonathanmetzman** [comment]
Actually, I may have spoke too soon about 1.9.4 being the fix.

**Comment by oliverchang** [comment]
I think the issue may be PYTHONPATH.

In the CI, we have `/data/google_appengine:/workspace/src`. If I remove the app engine path, it no longer reports that issue. Maybe it's exiting early when it can't import the appengine modules.

**Comment by jonathanmetzman** [comment]
>I think the issue may be PYTHONPATH.

Sounds correct to me. I don't actually think it has to do with using 1.9.4 (I think I thought this because of similar issues that came up when I used pylint in a fresh virtualenv)

**Comment by jonathanmetzman** [comment]
It seems to me the pylint result from CI is more accurate than my local one. Do you think the fix is to make CI like local? It seems like making local like pylint on CI is the more ideal fix no?

**Comment by jonathanmetzman** [comment]
Looks like you decided this :)

**Comment by oliverchang** [comment]
Yup :) Looks like local was missing results.
