### ISSUE TITLE
Missing Validation checks in Pagination Request Handlers

### ISSUE THREAD

**Issue by iamarshsingh** [google/clusterfuzz#1883]
There is lack of Validation checks for negative page numbers in Testcase-list and Crash-stats.

**To Reproduce:** (Enter a negative page number in the URL)
1. https://oss-fuzz.com/testcases?open=yes&page=-5
2. https://oss-fuzz.com/crash-stats?block=day&days=7&end=442789&group=platform&number=count&page=-2&sort=total_count

**Screenshot**
![Error in Negative Page number](https://user-images.githubusercontent.com/30122295/86598654-0ca2b200-bfbb-11ea-9e0b-ad06404a3ec1.png)

I discussed with @oliverchang and he suggested to put validation checks and display empty list.

**Comment by oliverchang** [comment]
Should be fixed now.
