### ISSUE TITLE
build_afl.bash fails to download correct files because cs.chromium.org does a 302 redirect without a specific cookie

### ISSUE THREAD

**Issue by phwd** [google/clusterfuzz#1899]
[build_afl.bash](https://google.github.io/clusterfuzz/setting-up-fuzzing/libfuzzer-and-afl/#afl) tries to download files from cs.chromium.org however that site does a 302 to a newer "code search"

adding `-H "cookie:REDIRECT_STATUS=optout" ` to each curl command in the bash script will fix the download issue (until Google decides to change it again)

`curl -H "cookie:REDIRECT_STATUS=optout" -O "https://cs.chromium.org/codesearch/f/chromium/src/third_party/afl/src/$source_file"`

`curl -H "cookie:REDIRECT_STATUS=optout" "https://cs.chromium.org/codesearch/f/chromium/src/third_party/afl/src/llvm_mode/afl-llvm-rt.o.c" > "llvm_mode/afl-llvm-rt.o.c"`

`curl -H "cookie:REDIRECT_STATUS=optout" -O "https://cs.chromium.org/codesearch/f/chromium/src/third_party/libFuzzer/src/afl/afl_driver.cpp"`

**Comment by Dor1s** [comment]
Thanks for reporting this. We should probably use https://github.com/google/AFL now. Would you be interested in uploading a pull request and contributing to ClusterFuzz? :)
