### ISSUE TITLE
Add .lgtm.yml

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#190]
@evverx thank you for adding ClusterFuzz to LGTM.com.
I created a new issue because I don't want to clutter #126.
On further thought, it seems like adding a .lgtm.yml may be a good idea (even if it means I have to conceed static analysis can be useful :-)

I'm just curious what's the advantage of adding the file if #126 fixes most of the python3-python2 issues LGTM.com is currently running into?

Feel free to add the file in a PR if you'd like. Or I can do this since I (incorrectly) preemptively rejected the PR last time :)
CC @cclauss

**Comment by evverx** [comment]
@jonathanmetzman when LGTM started to analyze python code in the systemd project it detected some issues we didn't care about there and it seemed a good idea at the time to just enforce the right version of Python (it was Python3 in our case) so as not to spend time on fixing unimportant stuff. My proposal was kind of a knee-jerk reaction based on that experience :-) I realized a little bit later that @alex's PR is likely to reduce the "python3" noise considerably. I'd just wait for #126 to land to see how it goes.

**Comment by evverx** [comment]
@cclauss I've just noticed the PR you opened and I'm not sure it would be useful to use LGTM to run flake8 especially given that it's unlikely that LGTM will analyze PRs when they're opened.

**Comment by cclauss** [comment]
That is what LGTM does...  It runs automatically on new PRs when they are opened.

The user “google” would first need to log into lgtm.com and enable this repo for the service to run.

**Comment by evverx** [comment]
It does if it's told to do so and I'm not sure that at this point the maintainers of ClusterFuzz are convinced that it's worth the hassle. Even if automatic code review was enabled, I don't think that LTGM would be the right place to run `flake8`.

**Comment by evverx** [comment]
@cclauss thank you for bringing up this topic [on the LGTM community site](https://discuss.lgtm.com/t/can-i-get-lgtm-to-run-flake8-tests/1445/7?u=evverx)! I always wondered what the official position is but kept following my hunches :-)

**Comment by cclauss** [comment]
Your hunches were different than mine but at least we now know the official word.

I sense that [GitHub Actions][https://github.com/features/actions) change the landscape yet again.

**Comment by evverx** [comment]
It's still a beta feature and it's usually hard to "Focus on what matters: code" using beta features. Plus it will take some time to figure out the weirdness of containers and the underlying infrastructure there to adjust tests and/or code accordingly (like a franken-kernel used on Travis CI that prevents overlayfs notify-events from reaching processes properly :-) Having said that I see a lot of people experimenting with GitHub Actions so it seems likely that they will take off. Given that the maintainers of ClusterFuzz are planning to switch to something public it would probably be useful if you could share your experience.

**Comment by jonathanmetzman** [comment]
>Given that the maintainers of ClusterFuzz are planning to switch to something public it would probably be useful if you could share your experience.

I think we are. I'm not actually sure. @oliverchang can you confirm if we are planning on moving to something like travis (I don't know if you know about the results being public, but I've seen this before, e.g. https://travis-ci.org/google/swiftshader)
