### ISSUE TITLE
adding ubuntu16 to clusterfuzz VM ?

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#1933]
Hi,  i see cos OS is the default for adding new VM.
Can I add ubuntu VM to clusterfuzz ?

**Comment by inferno-chromium** [comment]
CoS OS just executes a Ubuntu 16.04 docker image, so CF code runs in Ubuntu 16.04
see 
https://github.com/google/clusterfuzz/blob/master/docker/base/Dockerfile#L14
