### ISSUE TITLE
PubSub subscriptions (at least some of them) aren't created automatically

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1934]
It's expected that the subscriptions will be created automatically during deployment, but many subscriptions are not getting created. 

One example is `ml-jobs-linux`: https://github.com/google/clusterfuzz/issues/1540#issuecomment-665298171

After I created the subscription manually, the task scheduling / claiming started to work.

An additional request here: maybe `add_task` function can raise an error if the subscription doesn't exist and it doesn't really add any tasks.

**Comment by oliverchang** [comment]
This is most likely fixed by https://github.com/google/clusterfuzz/pull/2230
