### ISSUE TITLE
Fuzzer process command lost APP_ARGS

### ISSUE THREAD

**Issue by lion-roadbike** [google/clusterfuzz#1938]
Hello, 
Environment String in my job:
APP_ARGS = -fuzzy_type=xyz
REQUIRED_APP_ARGS = -fuzzy_type=xyz

But there is no "-fuzzy_type=xyz" in the process command:
```
(clusterfuzz) root@881ff12e25be:/clusterfuzz# cat /clusterfuzz/local/storage/local_gcs/test-fuzz-logs-bucket/objects/libFuzzer_myapp_xyz_fuzzer/libfuzzer_asan_linux_myapp_xyz_fuzzer/2020-07-31/07\:29\:10\:280742.log
Component revisions (build r1):
Not available.

Return code: 1

Command: /path/to/my-bot/clusterfuzz/bot/builds/libfuzzer_asan_linux_myapp_xyz_fuzzer/custom/myapp_xyz_fuzzer -timeout=25 -rss_limit_mb=2560 -fork=2 -artifact_prefix=/path/to/my-bot/clusterfuzz/bot/inputs/fuzzer-testcases/ -max_total_time=2550 -print_final_stats=1 /path/to/my-bot/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-14376/new /path/to/my-bot/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-14376/subset
Bot: my-bot
Time ran: 2640.0384311676025
```

version: tag/v2.0.2

https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/#creating-a-job-type
Thank you!

**Comment by lion-roadbike** [comment]
In the version(tags/1.2.1) I deployed earlier, It is OK for APP_ARGS.

**Comment by inferno-chromium** [comment]
libFuzzer and honggfuzz use the new engine pipeline https://github.com/google/clusterfuzz/tree/master/src/python/bot/fuzzers/libFuzzer in latest code. I dont see any reson for a custom argument in libFuzzer, since different command line options that libFuzer support already get used in strategies in some percent of fuzzing runs. APP_ARGS is geared towards black-box fuzzer jobs where you run a custom binary compiled with sanitizers and need to run that app binary, it is also only documented in blackbox fuzzer jobs - https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/ (and not libfuzzer jobs).

**Comment by lion-roadbike** [comment]
I want to use a custom argument to control the behavior of my app in libFuzzer.

**Comment by inferno-chromium** [comment]
> I want to use a custom argument to control the behavior of my app in libFuzzer.

This can be done via the options file and can be different with different fuzzers. In fuzzer archive, add <fuzz_target>.options next to <fuzz_target> binary. That file can have like

```
[libfuzzer]
<option name 1> = <option 1 value>
<option name 2> = <option 2 value>
```

Will that work for you ?

To make APP_ARGS work for engine based fuzzers is some little work as it needs to be done for libFuzzer, AFL, Honggfuzz in a generic way. Can you give an example of argument you always need to pass to libFuzzer binary ?

**Comment by lion-roadbike** [comment]
Ok, I try options.

example: 
```
extern "C" int LLVMFuzzerInitialize(int *argc, char ***argv)
{
	QStringList args;
	for (int i = 0; i < *argc; ++i)
	{
		args << QString::fromLocal8Bit((*argv)[i]);
	}

	const QString argName = "-format_type=";
	for (int i = 1; i < args.count(); i++)
	{
		if (args[i].indexOf(argName) == 0)
		{
			QString format_type = args[i].mid(argName.length()).toLower();
			if (format_type == "abc")
				gFuzzFormatType = 1;
			else if (format_type == "def")
				gFuzzFormatType = 2;
			else if (format_type == "xyz")
				gFuzzFormatType = 3;
		}
	}

	return 0;
}
```

**Comment by inferno-chromium** [comment]
> Ok, I try options.
> 
> An example of argument:
> 
> ```
> extern "C" int LLVMFuzzerInitialize(int *argc, char ***argv)
> {
> 	QStringList args;
> 	for (int i = 0; i < *argc; ++i)
> 	{
> 		args << QString::fromLocal8Bit((*argv)[i]);
> 	}
> 
> 	const QString argName = "-format_type=";
> 	for (int i = 1; i < args.count(); i++)
> 	{
> 		if (args[i].indexOf(argName) == 0)
> 		{
> 			QString format_type = args[i].mid(argName.length()).toLower();
> 			if (format_type == "abc")
> 				gFuzzFormatType = 1;
> 			else if (format_type == "def")
> 				gFuzzFormatType = 2;
> 			else if (format_type == "xyz")
> 				gFuzzFormatType = 3;
> 		}
> 	}
> 
> 	return 0;
> }
> ```

Why don't you just create three fuzz targets, they will have different corpus anyway. See ffmpeg as an example in OSS-Fuzz that has 400+ file format parser [https://github.com/google/oss-fuzz/blob/master/projects/ffmpeg/build.sh]. We don't create 400 job types. You just put the different file type parsers as different fuzzers, put in archive in one job and then ClusterFuzz is smart to pick a different one for fuzzing every cycle.
