### ISSUE TITLE
update cluster failure?

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#1948]
I tried to redeploy an update to my clusterfuzz cluster and I keep running into the following error.

| Successfully installed Automat-20.2.0 PyHamcrest-2.0.2 PyYAML-5.1 antlr4-python3-runtime-4.7.2 attrs-19.3.0 backports.lzma-0.0.13 cachetools-4.1.1 certifi-2020.6.20 chardet-3.0.4 configparser-3.7.4 constantly-15.1.0 distro-1.5.0 ecdsa-0.15 future-0.17.1 google-api-core-1.22.0 google-api-python-client-1.8.3 google-auth-1.14.3 google-auth-httplib2-0.0.4 google-auth-oauthlib-0.4.1 google-cloud-core-1.3.0 google-cloud-datastore-1.12.0 google-cloud-logging-1.15.0 google-cloud-monitoring-0.36.0 google-cloud-ndb-1.2.0 google-cloud-profiler-1.0.3 google-cloud-storage-1.28.1 google-resumable-media-0.5.1 googleapis-common-protos-1.52.0 grpcio-1.28.1 httplib2-0.11.3 hyperlink-20.0.0 idna-2.8 incremental-17.5.0 lxml-4.5.0 mozfile-2.1.0 mozinfo-1.2.2 mozprocess-1.1.0 oauth2client-4.1.3 oauthlib-3.1.0 protobuf-3.11.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 python-dateutil-2.8.1 pytz-2018.5 redis-3.3.11 requests-2.21.0 requests-oauthlib-1.3.0 rsa-4.0 selenium-3.141.0 setuptools-49.2.1 six-1.14.0 tlslite-ng-0.7.5 twisted-20.3.0 typing-3.7.4.3 uritemplate-3.0.1 urllib3-1.24.3 zope.interface-5.1.0
Running: pip3 download --no-deps --only-binary=:all: --platform=win_amd64 --abi=cp37m -r src/platform_requirements.txt -d /tmp/tmpi65vln71
| Traceback (most recent call last):
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/bin/pip3", line 8, in <module>
|     sys.exit(main())
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
|     command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
|     module = importlib.import_module(module_path)
|   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
|     return _bootstrap._gcd_import(name[level:], package, level)
|   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
|   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
|   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
|   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_internal/commands/download.py", line 11, in <module>
|     from pip._internal.cli.req_command import RequirementCommand, with_cleanup
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
|     from pip._internal.index.package_finder import PackageFinder
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
|     from pip._internal.index.collector import parse_links
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
|     from pip._vendor import html5lib, requests
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
|     from . import utils
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
|     from . import certs
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
|     from pip._vendor.certifi import where
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
|     from .core import contents, where
|   File "/home/cfzuser/.local/share/virtualenvs/clusterfuzz-EcNB5a_N/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
|     from importlib.resources import read_text
|   File "/usr/local/lib/python3.7/importlib/resources.py", line 11, in <module>
|     from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
|   File "/opt/local/clusterfuzz/src/third_party/typing.py", line 1359, in <module>
|     class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
|   File "/opt/local/clusterfuzz/src/third_party/typing.py", line 1007, in __new__
|     self._abc_registry = extra._abc_registry
| AttributeError: type object 'Callable' has no attribute '_abc_registry'
| Return code is non-zero (1).

This is running on python 3.7 and ran this same update commmand a couple of weeks ago and it seemed to work.  But for some reason now it does not.  Not sure if something changed?

**Comment by inferno-chromium** [comment]
Pull from master again, that was fixed today - https://github.com/google/clusterfuzz/commit/07c1ba38ce01315f69f30a760f60856d5059ab75
