### ISSUE TITLE
(Question) Corpus files are not being added to corpus bucket

### ISSUE THREAD

**Issue by sanchitvohra** [google/clusterfuzz#1951]
I have setup clusterfuzz (by following the documentation) for my project and have been monitoring the fuzzing logs. It seems that the fuzzing bots are working as expected, however, the new corpus files that they generate are not syncing to the corpus bucket. I have a few questions regarding this.

1. Are all new corpus files supposed to be synced to the default corpus bucket after every fuzzer run?
2. Do I need some additional setup to make the bots save new corpus files in the bucket?

Thanks!

**Comment by inferno-chromium** [comment]
Check bot.log file or stackdriver logs for any errors. It can happen if your service account does not have permission or is not storage owner for that gcs bucket.

**Comment by sanchitvohra** [comment]
What bucket is the bot.log file stored in? Right now fuzzer-logs.<project-name>.appspot.com is empty,  and fuzz-logs.<project-name>.appspot.com has individual fuzz runs. Also, service account permissions should be set up by the deployment scripts right? If there is a permissions error, would redeploying help?

**Comment by inferno-chromium** [comment]
bot.log i meant to check on actual bot
ssh into bot
docker exec -ti clusterfuzz /bin/bash
cd clusterfuzz/bot/logs
cat bot.log

**Comment by sanchitvohra** [comment]
Just checked the log, it appears the fuzzing is finding new files and putting them into the local corpus directory stat::number_of_executed_units: 816017, stat::new_units_added: 500. I checked the clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-<some-number>/new which I am assuming is the local corpus directory which is also populated with files. The trace also says "0 new corpus files generated by fuzzer <name> (job <job-name> ). Do crashes during fuzzing prevent corpus upload?

**Comment by inferno-chromium** [comment]
Can you paste the full fuzz task log content from bot.log. Looks like something is wrong with either corpus merge as otherwise it should be syncing corpus back to gcs.

**Comment by sanchitvohra** [comment]
It appears the corpus merge is failing (because of my code crashing on shutdown) which is likely the cause of this. I will fix the shutdown bugs and try again. Thank you for your help!
