### ISSUE TITLE
How to removed dead bots from /bots list?

### ISSUE THREAD

**Issue by prestonvanloon** [google/clusterfuzz#1958]
As title describes, we have hundreds of dead bots in this list and cannot figure out how to clean it up.

Thanks!

**Comment by inferno-chromium** [comment]
The cron auto-deletes them every 15 days, otherwise you can delete them from HeartBeat entity in Appengine db.
https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/cleanup.py#L1230

**Comment by prestonvanloon** [comment]
Thanks!
