### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/scratch0/clusterfuzz/bot/builds/

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#1968]
I get FileNotFoundError for some fuzzer targets. I SSHed into the VM and the fuzz target is present under 

/var/scratch0/clusterfuzz/bot/inputs/data-bundles/toy_target
/var/scratch0/clusterfuzz/bot/builds/libfuzzer_asan_toy_xyz/custom/toy_target
/mnt/stateful_partition/var/scratch0/clusterfuzz/bot/inputs/data-bundles/toy_target
/mnt/stateful_partition/var/scratch0/clusterfuzz/bot/builds/libfuzzer_asan_toy_xyz/custom/toy_target

the exact stacktrace is:

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/scratch0/clusterfuzz/bot/builds/libfuzzer_asan_toy_xyz/custom/toy_target': '/mnt/scratch0/clusterfuzz/bot/builds/libfuzzer_asan_toy_xyz/custom/toy_target'
at _execute_child (/usr/local/lib/python3.7/subprocess.py:1551)
at __init__ (/usr/local/lib/python3.7/subprocess.py:800)
at run (/mnt/scratch0/clusterfuzz/src/python/system/new_process.py:286)
at run_and_wait (/mnt/scratch0/clusterfuzz/src/python/system/new_process.py:337)
at run_and_wait (/mnt/scratch0/clusterfuzz/src/python/system/new_process.py:362)
at fuzz (/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libfuzzer.py:236)
at fuzz (/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libfuzzer.py:413)
at fuzz (/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py:256)
at run_engine_fuzzer (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1301)
at do_engine_fuzzing (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1603)
at run (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1888)
at execute_task (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1968)
at run_command (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:201)
at process_command (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:377)
at wrapper (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:147)
at task_loop (/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py:89)

Could you help me to debug what is the exact issue ?

**Comment by Dor1s** [comment]
Does the binary have executable bit set? i.e. `chmod +x`

**Comment by ravi50041** [comment]
Yes @Dor1s  the target has execute bit set. 

**-rwxr-xr-x** 1 clusterfuzz clusterfuzz 16713252 Aug 11 12:31 /mnt/stateful_partition/var/scratch0/clusterfuzz/bot/builds/libfuzzer_asan_toy_xyz/custom/toy_target

Along with FileNotFoundError I get below error
Task exited with exception (payload="fuzz libFuzzer libfuzzer_asan_toy_xyz").

**Comment by ravi50041** [comment]
Has anyone seen this issue in the past?

**Comment by inferno-chromium** [comment]
Nope, we havent seen this, but 
the path it is complaining is `/mnt/scratch0/clusterfuzz/bot/builds/libfuzzer_asan_toy_xyz/custom/toy_target'
and that is not equal to either ones you mentioned [this one starts with /mnt/scratch0]. Did you change any of /mnt to /var in docker ?

**Comment by urbanenomad** [comment]
I am the cluster admin and we don't do any modifications to the docker image we pretty much run it based on the deployment script provided.  Where would we even be able to modify the mount in the deployment configuration?

**Comment by Dor1s** [comment]
@ravi50041 could you please check access rights on `/mnt/scratch0/clusterfuzz/bot/builds/libfuzzer_asan_toy_xyz/custom/toy_target` path, the one that you mentioned in the first comment?

Another pretty dumb guess (but who knows): are you sure that is a libFuzzer binary compiled for the right OS / architecture?

**Comment by urbanenomad** [comment]
Ok it looks like the issue was some missing 32bit libraries in the docker image.  If we want to change the docker image to add a couple of library files is there a simple way to do that locally?  I see there is a docker folder with which will build the images used in the bots but it also points to a public gcr.io/clusterfuzz-images and it is referenced everywhere.  Is there an easier way to customize the docker image?

**Comment by inferno-chromium** [comment]
> Ok it looks like the issue was some missing 32bit libraries in the docker image. If we want to change the docker image to add a couple of library files is there a simple way to do that locally? I see there is a docker folder with which will build the images used in the bots but it also points to a public gcr.io/clusterfuzz-images and it is referenced everywhere. Is there an easier way to customize the docker image?

Make change to docker/base, build it using https://github.com/google/clusterfuzz/tree/master/docker/base, this will give you your own gcr.io/whatever/something, and then use that image name instead of gcr.io/clusterfuzz-images in your clusters.yaml file.

**Comment by urbanenomad** [comment]
yep I just realized that.  I was looking at the production build. Thanks

Won
