### ISSUE TITLE
Perf report and charts are missing in fuzzer statistics

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#1988]
Hi,

I have deployed clusterfuzz on google cloud. I don't see perf_report/edge_coverage/ cov_report in fuzzer statistics. It shows "-".

charts also are not getting generated. 

could someone help ?

**Comment by inferno-chromium** [comment]
Edge_coverage and cov_report require another setup - https://google.github.io/clusterfuzz/using-clusterfuzz/advanced/code-coverage/

Perf_report should be visible, did you select the exact fuzzer and job combination.e.g pick exact libFuzzer_<fuzzer_name> and job type, then you should see performance report hyperlink.
