### ISSUE TITLE
VM allocation to fuzz targets

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#1989]
Hi, 

Can i allocate some minimum number of VMs to a particular fuzz target while submitting job ? As far as I know. jobs get uniform share of VMs. 

Also I observe that some jobs are getting more number of VMs and some jobs are getting less. the distribution is not uniform. 

can someone explain possible reasons behind it ?

**Comment by inferno-chromium** [comment]
Check out https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/fuzzer_and_job_weights.py

You can modify a job weight in Datastore - see this field - https://github.com/google/clusterfuzz/blob/master/src/python/datastore/data_types.py#L1409
