### ISSUE TITLE
Try to use libfuzzer in android platform fail

### ISSUE THREAD

**Issue by coffeezh** [google/clusterfuzz#2041]
Recently,I try to use Clusterfuzz to work in android.So I upload libfuzzer offical testcase,and from log,I can see ClusterFuzz already push testcase into android device.But I don't see do ./testcase,lead to next step pull from android devices is null.

If don't collect crash message,Clusterfuzz will let android reboot and do the same things again.

I suspect whether my method to test android is wrong,can you tell me how to test in andorid,thank you.

**Comment by inferno-chromium** [comment]
Are you using a HWAsan build - https://source.android.com/devices/tech/debug/hwasan that is the one we use for libfuzzer builds
Can you paste your job definition and some log contents, without it it is hard to see what is going on.

**Comment by coffeezh** [comment]
I add "LOCAL_SANITIZE := address  LOCAL_CLANG := true" to Android.mk,after compile,I can do "./fuzzer" in android platform and see crash report quickly.

Log contents I get:
 - run_bot - INFO - Running: adb shell 'su root sh -c "rm -rf /data/fuzz/bot/inputs/data-bundles/fuzz_me_fuzzer"'
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb shell "mkdir -p /data/fuzz/bot/inputs/data-bundles/fuzz_me_fuzzer"
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb shell "mkdir -p /data/fuzz/bot/inputs/data-bundles/fuzz_me_fuzzer"
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb shell 'su root sh -c "rm -rf /data/fuzz/bot/inputs/fuzzer-testcases"'
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb shell "mkdir -p /data/fuzz/bot/inputs/fuzzer-testcases"
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb shell "mkdir -p /data/fuzz/bot/inputs/fuzzer-testcases"
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb shell 'su root sh -c "rm -rf /data/fuzz/bot/inputs/fuzzer-testcases-disk/temp-28486/new"'
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb shell "mkdir -p /data/fuzz/bot/inputs/fuzzer-testcases-disk/temp-28486/new"
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb shell "mkdir -p /data/fuzz/bot/inputs/fuzzer-testcases-disk/temp-28486/new"
 - run_bot - INFO - Output: ()
 - run_bot - INFO - Running: adb pull /data/fuzz/bot/inputs/data-bundles/fuzz_me_fuzzer/. /home/user/Documents/Sl3-bot/clusterfuzz/bot/inputs/data-bundles/fuzz_me_fuzzer
 - run_bot - INFO - Output: (/data/fuzz/bot/inputs/data-bundles/fuzz_me_fuzzer/./: 0 files pulled.)
 - run_bot - INFO - Running: adb pull /data/fuzz/bot/inputs/fuzzer-testcases/. /home/user/Documents/Sl3-bot/clusterfuzz/bot/inputs/fuzzer-testcases
 - run_bot - INFO - Output: (/data/fuzz/bot/inputs/fuzzer-testcases/./: 0 files pulled.)
 - run_bot - INFO - Running: adb pull /data/fuzz/bot/inputs/fuzzer-testcases-disk/temp-28486/new/. /home/user/Documents/Sl3-bot/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-28486/new
 - run_bot - INFO - Output: (/data/fuzz/bot/inputs/fuzzer-testcases-disk/temp-28486/new/./: 0 files pulled.)
 - run_bot - INFO - Skipped corpus merge since no new units added by fuzzing.
 - run_bot - INFO - Extracting and analyzing recommended dictionary for fuzz_me_fuzzer.
 - run_bot - INFO - No recommended dictionary in output from fuzz_me_fuzzer.
 - run_bot - INFO - Used strategies.
 - run_bot - INFO - Uploaded file to logs bucket.
 - run_bot - INFO - Uploaded file to logs bucket.

According to log,adb pull 0 file seems cause not file upload to logs bucket.In my opinion,I think Clusterfuzz should do "./fuzzer" before doing pull file,maybe I was wrong.

I don't use HWAsan build all android system,I run this work in Android10 arm32 platform,from the offical description seems it can't support except "AArch64".

So I use Asan to compile object,not compile all system.

**Comment by inferno-chromium** [comment]
Try applying this patch and check the output in log, looks like your libfuzzer binary is not working on device and this will show what is going wrong
```
diff --git a/src/python/bot/fuzzers/libfuzzer.py b/src/python/bot/fuzzers/libfuzzer.py
index 5dd35c7a..cfcf258e 100644
--- a/src/python/bot/fuzzers/libfuzzer.py
+++ b/src/python/bot/fuzzers/libfuzzer.py
@@ -1200,6 +1200,7 @@ class AndroidLibFuzzerRunner(new_process.UnicodeProcessRunner, LibFuzzerCommon):
         additional_args=additional_args,
         extra_env=extra_env)
 
+    logs.log('Run output: %s.' % result.output)
     result.output = self._append_logcat_output_if_needed(result.output)
 
     self._copy_local_directories_from_device(sync_directories)
```

**Comment by inferno-chromium** [comment]
You should also see the logs output in gs://<whatever> you configured for your FUZZ_LOGS_BUCKET in project.yaml file.

**Comment by coffeezh** [comment]
After I imported this patch，I can see:
Run output: ERROR: ld.so: object '/home/usr/android-bot/clusterfuzz/resources/platform/android/radamsa/libradamsa.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
==4443==AddressSanitizer: detect_leaks is not supported on this platform.

Pherhaps libradamsa.so can't support.And FUZZ_LOGS_BUCKET default config is test-fuzz-logs-bucket,I see gs://test-fuzz-logs-bucket but 404，file not find.How can I see all logs?I think it's very important for me.Thank you for you help.

**Comment by inferno-chromium** [comment]
All values in projects.yaml are just an example, e.g. for FUZZ_LOGS_BUCKET, create your own bucket in your project and then change test-fuzz-logs-bucket to that bucket to see all the logs.

And yes, looks like libradamsa is not built properly or something, so disable it and try to get a working setup first.

**Comment by coffeezh** [comment]
Thank you for your help,I have succeed after set 'detect_leaks = 0 '.
