### ISSUE TITLE
Pub/Sub feed for bug updates

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#2043]
Hi ,

Is there any option to send emails for each new crash to configured email-address ?

**Comment by inferno-chromium** [comment]
This could be a crazy simple feature to add, you want to give it a shot and propose PR

Basically needs to be call like this
https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/cleanup.py#L773

in this code
https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/triage.py#L327

**Comment by hpathuri** [comment]
It would good to add this feature. Creating JIRA tickets from ClusterFuzz cloud to a company hosted internal JIRA needs to clear lot of security challenges.

If an email can be generated with the unique crash with a URL, companies can develop Bots to cosume these emails , pull additional info such as test case info, binary file and create internal tickets.

This is one of the issues we are trying to figure out with our eval.

As you may have noticed, oneFuzz seems to have better integration into Teams. So At least ClusterFuzz team should consider supporting this quickly.

**Comment by oliverchang** [comment]
Thanks for the feedback. Would a [pub/sub](https://cloud.google.com/pubsub/docs/overview) topic work for you as well? Pub/Sub can give you structured messages that are much easier to script on in your bots.

Emails can be tricky to parse and relies on third party services (sendgrid) which may cause additional security concerns.

**Comment by inferno-chromium** [comment]
@hpathuri - see @oliverchang suggestion.

Regarding ClusterFuzz, we do automatic bug filing, triage (e.g. discovery of bugs on other platforms, tell if something is top crashes, see full list here - https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/cleanup.py#L133 , etc), and automatic bug verification. Filing the bug itself is just one piece of the puzzle, ClusterFuzz value addition is a lot of other triage stuff that ClusterFuzz helps developers with in a fully automated way.

If talking with internal issue tracker is an issue, we can do other publishing mechanisms like pub/sub as Oliver mentioned. Email feels insecure to do from a third-party service like sendgrid. Do you have any preferred way of getting this info in a secure way ?

**Comment by hpathuri** [comment]
pub/sub will work.

I assume, we need to develop subscriber that runs on ClusterFuzz and use gsutil to export to our internal system of sort?

Where would be the subscriber need to be deployed?

**Comment by oliverchang** [comment]
The subscriber can be deployed anywhere, as long as it's running with a service account that has the correct permissions.

**Comment by urbanenomad** [comment]
Is there a built in mechanism in clusterfuzz that will publish cash reports to pub/sub or do we have to write that ourselves?

**Comment by oliverchang** [comment]
This doesn't exist today, but it should be fairly simple to add it and we'd be happy to support this feature. Will see if I have time to implement this in the next week or so.

**Comment by oliverchang** [comment]
This was implemented in #2047 

To use it, you need to create a Pub/Sub topic and specify it in your project.yaml like so: https://github.com/google/clusterfuzz/blob/63ab479e8442ab4707ee71e63a91078427c0dd71/configs/test/project.yaml#L127. You'll need to make sure that the service account your bots are running as has permissions to publish to this topic.

The messages have the following attribute format: https://github.com/google/clusterfuzz/blob/63ab479e8442ab4707ee71e63a91078427c0dd71/src/python/tests/appengine/libs/issue_filer_test.py#L793

Note that this currently will only notify on *new bugs* that would've been filed, and not when bugs are going to be closed as it's a little messy to untangle that logic when there is no issue tracker. Would this be sufficient?

**Comment by hpathuri** [comment]
Thanks for quick response.
