### ISSUE TITLE
Entropic is now the default in libFuzzer

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#2052]
Matt landed it 9 days ago in https://reviews.llvm.org/D87476

I think we should probably delete that strategy at all from CF, to keep things simple. Does anyone think we should invert the existing strategy or do anything else with it?

**Comment by inferno-chromium** [comment]
Yes just deleting sounds good.

**Comment by Dor1s** [comment]
Uploaded https://github.com/google/clusterfuzz/pull/2053 but need to clarify something w.r.t BigQuery columns.
