### ISSUE TITLE
How to run different Jobs in the same Fuzzers

### ISSUE THREAD

**Issue by coffeezh** [google/clusterfuzz#2079]
I add a job about Android test and upload to libfuzzer,Android bot can do this job.Afterly,I add a job about Linux test and upload to libfuzzer,I found Android bot stop work,and Linux bot start work.

Q1:
It means a Fuzzer,e.g libfuzzer,can only do one job.If I want to do the Android test and the Linux test at the same time,what should I do?

Q2:
After the bot find a bug and produce a report,I found the bot never stop work.The bot execute command "fuzz" continuously.Ask why let the bot do this thing after producing a report?

Q3:
For example,if I have two Android bot.After I uploading a job,I want one of the bot do this job,and the other refuse this job.How can I do to achieve this things?

Thank you for your answers.

**Comment by inferno-chromium** [comment]
> I add a job about Android test and upload to libfuzzer,Android bot can do this job.Afterly,I add a job about Linux test and upload to libfuzzer,I found Android bot stop work,and Linux bot start work.
> 

If you have just one bot, it shares cycles between different jobs. and it picks a random one after it is done finishing the first one. you need more bots if you want to do atleast one job always at any time.

> Q1:
> It means a Fuzzer,e.g libfuzzer,can only do one job.If I want to do the Android test and the Linux test at the same time,what should I do?

android and linux jobs shouldn't share cycles as they should be on different platform, did you select the right platform when creating the job.

> 
> Q2:
> After the bot find a bug and produce a report,I found the bot never stop work.The bot execute command "fuzz" continuously.Ask why let the bot do this thing after producing a report?
> 

fuzz is continuous, as long as bot is alive, it is keep fuzzing. if you want fuzzing to stop, just remove the fuzzer to job association on /fuzzers page.

> Q3:
> For example,if I have two Android bot.After I uploading a job,I want one of the bot do this job,and the other refuse this job.How can I do to achieve this things?

it is randomly choosen to pick a job to do it. there is no way currently to customize which bot gets which job.

> 
> Thank you for your answers.

**Comment by coffeezh** [comment]
Thank you for your answers.I have another question.

I want to run blackbox fuzz in Android platform,accoring to "https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/",it need create new Fuzzers.When I create Fuzzers,I meet a problem.I don't know how to make an archive to upload,it seems run.py,but I don’t know the specific content.Can you guide me or have a specific example?

I see a pdf introduce ClusterFuzz,It mentioned ClusterFuzz can produce Coverage Report,but I don't know how to achieve this goal.Can you guide me about this things?

Thank you for your help.

**Comment by inferno-chromium** [comment]
> Thank you for your answers.I have another question.
> 
> I want to run blackbox fuzz in Android platform,accoring to "[https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/",it](https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/%22,it) need create new Fuzzers.When I create Fuzzers,I meet a problem.I don't know how to make an archive to upload,it seems run.py,but I don’t know the specific content.Can you guide me or have a specific example?
> 
> I see a pdf introduce ClusterFuzz,It mentioned ClusterFuzz can produce Coverage Report,but I don't know how to achieve this goal.Can you guide me about this things?
> 
> Thank you for your help.

See https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/#uploading-a-fuzzer, it can just a run.py wrapper and your fuzzer files in archive. run.py calls your fuzzers and accept those three arguments and creates static files in the output directory. then clusterfuzz automatically copies them to android device and runs your app.
