### ISSUE TITLE
VM Allocation to jobs is not uniform.  

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#2081]
Hi Team,

I have setup clusterfuzz on Gcloud. i have 100 preemptible machines which are running around 33 jobs. All the jobs are ASAN based. 

Ideally it should be allocating 3 VMs per job but i dont see that happening. some VMs are allocated 3 and some are allocated 1.

I am trying to understand this behaviour and possible reasons of it. 

Also can we get data of what preemptible VM ran which job and for how much time before dying. This would help me to understand more about bots behaviour.

**Comment by Dor1s** [comment]
@ravi50041 did you find answers for your questions? Or was this issue closed unintentionally?
