### ISSUE TITLE
Clarification on fuzzer statistics

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#2084]
Hi,

I see new_features and new_tests_added columns in fuzzer statistics. 

I have few questions :
1. the count of new_tests_added is with minimization(-merge) or without minimization?

2. I see new_features is     
merge_stats['new_features'] = (merge_stats['feature_coverage'] - 
merge_stats['initial_feature_coverage'])

could you please tell me what exactly new_features means and what does the value indicates?

**Comment by ravi50041** [comment]
Hi, 

I wanted to understand how the tests_excecuted is calculated. 

i have below scenario.

tests_executed:93,849,799
avg_exec_per_sec:1,558.4
total_fuzzing_time_hrs:100.1


I was  assuming that **total_fuzzing_time_hrs * avg_exec_per_sec * 3600** should give me tests_executed. 


but total_fuzzing_time_hrs * avg_exec_per_sec * 3600 result is way higher than tests_executed.

Could you tell me is it because of a job is running on more than 1 core or maths of tests_executed is all togather different ?


total_fuzzing_time_hrs * avg_exec_per_sec * 3600 =  561,585,024
tests_executed:93,849,799


if we take the ratio of both I get 561,585,024 / 93,849,799 = 5.98.


Does this mean that on an average job runs on 6 Pre. VMs ?

**Comment by ravi50041** [comment]
Hi, 

There are two fields one is corpus_size and one is new_tests_added.

It is mentioned that:
1. corpus_size: minimized testcase generated based on code coverage.
2. new_tests_added: new testcase added to corpus during fuzzing based on code coverage.


I just wanted to understand what is the difference between these 2 columns. 

in my scenario:

new_tests_added : 32,193
corpus_size: 4690  


my assumption is(please correct me if i am wrong).

**new_tests_added** is obtained after corpus minimization(-merge=1) and **corpus_size** is obtained after testcase minimization(reducing the size of each testcase).

**Comment by inferno-chromium** [comment]
new_tests_added is added after every fuzzing iteration, with only local merge on one bot (1-1.5 hr job). SO that number is without deduplication across bots, and every bot contributes to that number. that number will be higher than corpus size.
corpus_size is size calculated after per-day corpus pruning, so that removes duplicate elements and this is a global view of corpus.
