### ISSUE TITLE
Remove fuzz targets with "run_" prefix

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#2093]
That was confusing me a few times and I think @inferno-chromium mention on one of the chats that those needs to be ignored / removed.

**Comment by inferno-chromium** [comment]
this might need a chromium builder change since i think it creates those junk files in archive.

**Comment by Dor1s** [comment]
Thanks for the pointer. I looked into where it's coming from and don't see a good way to disable it (https://source.chromium.org/chromium/chromium/src/+/master:testing/test.gni;l=566;drc=ddae81d0aaa4c045efe31c7dfa4c82207024acd3)

The other options:

1) Update the filter function used by Chromium builder and skip those files
2) Update CF code and make this check a bit more sophisticated: https://github.com/google/clusterfuzz/blob/1d27ac053f2cefaa5f71722d83b264acbfb49f61/src/python/bot/fuzzers/utils.py#L47-L48

**Comment by Dor1s** [comment]
I'm leaning towards 1), as the naming convention we have in ClusterFuzz used to work for a while. I'll upload a CL.

**Comment by inferno-chromium** [comment]
yes +1 for 1)

**Comment by Dor1s** [comment]
https://chromium-review.googlesource.com/c/chromium/tools/build/+/2476671

**Comment by Dor1s** [comment]
Should be fixed now: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8865713758211113216/+/steps/zipping/0/stdout?format=raw
