### ISSUE TITLE
Did not find com_google_cloud_go//datastore package

### ISSUE THREAD

**Issue by chenhb-zte** [google/clusterfuzz#210]
Hit this issue while running ` python butler.py bootstrap`. What is  the happen? THANKS
| ERROR: Analysis of target '//local:create_gopath' failed; build aborted: no such package '@com_google_cloud_go//datastore': failed to fetch com_google_cloud_go: 2019/02/15 12:35:41 unrecognized import path "cloud.google.com/go"

**Comment by chenhb-zte** [comment]
Sometimes  perform this error information, What can i do to avoid these issues?

| ERROR: Analysis of target '//local:create_gopath' failed; build aborted: no such package '@org_golang_google_api//iterator': failed to fetch org_golang_google_api: 2019/02/15 15:28:03 unrecognized import path "google.golang.org/api"

**Comment by chenhb-zte** [comment]
I set GOPATH and get the package with `go get -u cloud.google.com/go` , but the issue still existed.
 Did i specify a wrong GOPATH ?  the GOPATH was pointed a self-defined directory.

**Comment by chenhb-zte** [comment]
add the error content. looks `--connect_timeout_secs`  is invalid.
bazel --connect_timeout_secs 60  run //local:create_gopath
INFO: Invocation ID: c7987d40-5b94-4bc4-bf47-b17479c34e6c
ERROR: Analysis of target '//local:create_gopath' failed; build aborted: no such package '@com_github_pkg_errors//': failed to fetch com_github_pkg_errors: # cd .; git clone https://github.com/pkg/errors /root/.cache/bazel/_bazel_root/2ad9d25912904b4b1a3186f98d003514/external/com_github_pkg_errors
Cloning into '/root/.cache/bazel/_bazel_root/2ad9d25912904b4b1a3186f98d003514/external/com_github_pkg_errors'...
fatal: unable to access 'https://github.com/pkg/errors/': Could not resolve host: github.com
2019/02/15 19:22:22 exit status 128
INFO: Elapsed time: 30.639s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @com_google_cloud_go; fetching 30s
    Fetching @org_golang_google_api; fetching 30s
    Fetching @com_github_pkg_errors; fetching 30s

**Comment by Dor1s** [comment]
Which revision are you using? Could you please post output from `git rev-parse HEAD`?

**Comment by chenhb-zte** [comment]
HI @Dor1s   revision is 3ed4f7bc69fea3340650f8a5a2ce04b0e9d7f68e
I avoided this issue with other ways, commented this line  https://github.com/google/clusterfuzz/blob/master/src/local/butler/appengine.py#L133 and specify the GOPATH, download these packages via `go get -u xxxxxx` , but looks it had some errors, performed the service unavaiable.

| INFO     2019-02-15 11:46:43,919 devappserver2.py:224] Using Cloud Datastore Emulator.
| We are gradually rolling out the emulator as the default datastore implementation of dev_appserver.
| If broken, you can temporarily disable it by --support_datastore_emulator=False
| Read the documentation: https://cloud.google.com/appengine/docs/standard/python/tools/migrate-cloud-datastore-emulator
| Help us validate that the feature is ready by taking this survey: https://goo.gl/forms/UArIcs8K9CUSCm733
| Report issues at: https://issuetracker.google.com/issues/new?component=187272
|
| INFO     2019-02-15 11:46:43,998 devappserver2.py:278] Skipping SDK update check.
| INFO     2019-02-15 11:46:44,215 datastore_emulator.py:155] Starting Cloud Datastore emulator at: http://localhost:9004
| WARNING  2019-02-15 11:46:46,237 simple_search_stub.py:1196] Could not read search indexes from local/storage/search_indexes
| INFO     2019-02-15 11:46:46,579 datastore_emulator.py:161] Cloud Datastore emulator responded after 2.364020 seconds
| INFO     2019-02-15 11:46:46,581 api_server.py:275] Starting API server at: http://localhost:44145
| INFO     2019-02-15 11:46:46,590 api_server.py:265] Starting gRPC API server at: http://localhost:36384
| INFO     2019-02-15 11:46:46,820 dispatcher.py:256] Starting module "default" running at: http://localhost:9000
| INFO     2019-02-15 11:46:47,041 dispatcher.py:256] Starting module "cron-service" running at: http://localhost:9001
| INFO     2019-02-15 11:46:47,042 admin_server.py:150] Starting admin server at: http://localhost:9002
Bootstrapping datastore...
Running: python butler.py run setup --non-dry-run --local --config-dir=configs/test
| DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
| Creating config
| Creating fuzzer afl
| Creating fuzzer libFuzzer
| Creating template afl
| Creating template libfuzzer
| Creating template engine_asan
| Creating template engine_ubsan
| Creating template engine_msan
| Done
| INFO     2019-02-15 11:47:44,000 instance.py:294] Instance PID: 28166
| HTTPError()
| HTTPError()
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
|     req.respond()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
|     self.server.gateway(self).respond()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 2115, in respond
|     response = self.req.server.wsgi_app(self.env, self.start_response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 292, in __call__
|     return app(environ, start_response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/request_rewriter.py", line 314, in _rewriter_middleware
|     response_body = iter(application(environ, wrapped_start_response))
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/request_handler.py", line 165, in __call__
|     self._flush_logs(response.get('logs', []))
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/request_handler.py", line 308, in _flush_logs
|     apiproxy_stub_map.MakeSyncCall('logservice', 'Flush', request, response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 97, in MakeSyncCall
|     return stubmap.MakeSyncCall(service, call, request, response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 331, in MakeSyncCall
|     rpc.CheckSuccess()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_rpc.py", line 136, in CheckSuccess
|     self._traceback)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_rpc.py", line 161, in _WaitImpl
|     self.request, self.response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 223, in MakeSyncCall
|     self._MakeRealSyncCall(service, call, request, response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 248, in _MakeRealSyncCall
|     encoded_response = self._server.Send(self._path, encoded_request)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/appengine_rpc.py", line 469, in Send
|     f = self.opener.open(req)
|   File "/usr/lib/python2.7/urllib2.py", line 435, in open
|     response = meth(req, response)
|   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
|     'http', request, response, code, msg, hdrs)
|   File "/usr/lib/python2.7/urllib2.py", line 473, in error
|     return self._call_chain(*args)
|   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
|     result = func(*args)
|   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
|     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
| HTTPError: HTTP Error 503: Service Unavailable
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
|     req.respond()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
|     self.server.gateway(self).respond()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 2115, in respond
|     response = self.req.server.wsgi_app(self.env, self.start_response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 292, in __call__
|     return app(environ, start_response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/request_rewriter.py", line 314, in _rewriter_middleware
|     response_body = iter(application(environ, wrapped_start_response))
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/request_handler.py", line 165, in __call__
|     self._flush_logs(response.get('logs', []))
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/request_handler.py", line 308, in _flush_logs
|     apiproxy_stub_map.MakeSyncCall('logservice', 'Flush', request, response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 97, in MakeSyncCall
|     return stubmap.MakeSyncCall(service, call, request, response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 331, in MakeSyncCall
|     rpc.CheckSuccess()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_rpc.py", line 136, in CheckSuccess
|     self._traceback)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_rpc.py", line 161, in _WaitImpl
|     self.request, self.response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 223, in MakeSyncCall
|     self._MakeRealSyncCall(service, call, request, response)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 248, in _MakeRealSyncCall
|     encoded_response = self._server.Send(self._path, encoded_request)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/appengine_rpc.py", line 469, in Send
|     f = self.opener.open(req)
|   File "/usr/lib/python2.7/urllib2.py", line 435, in open
|     response = meth(req, response)
|   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
|     'http', request, response, code, msg, hdrs)
|   File "/usr/lib/python2.7/urllib2.py", line 473, in error
|     return self._call_chain(*args)
|   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
|     result = func(*args)
|   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
|     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
| HTTPError: HTTP Error 503: Service Unavailable
| INFO     2019-02-15 11:47:49,269 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 500 -
| WARNING  2019-02-15 11:47:52,257 tasklets.py:468] suspended generator run_to_queue(query.py:969) raised HTTPError(HTTP Error 503: Service Unavailable)
| WARNING  2019-02-15 11:47:52,258 tasklets.py:468] suspended generator helper(context.py:890) raised HTTPError(HTTP Error 503: Service Unavailable)
| WARNING  2019-02-15 11:47:52,258 tasklets.py:468] suspended generator has_next_async(query.py:1793) raised HTTPError(HTTP Error 503: Service Unavailable)
| WARNING  2019-02-15 11:47:52,259 tasklets.py:468] suspended generator _fetch_page_async(query.py:1380) raised HTTPError(HTTP Error 503: Service Unavailable)
| ERROR    2019-02-15 11:47:52,264 logs.py:327] Error occurred while grouping test cases.
| Traceback (most recent call last):
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|     self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|     self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run

**Comment by inferno-chromium** [comment]
```
fatal: unable to access 'https://github.com/pkg/errors/': Could not resolve host: github.com
2019/02/15 19:22:22 exit status 128
```
in your logs point towards the error. Is github.com blocked in your firewall, need to open for package install.

**Comment by aressu1985** [comment]
Hi chenhb-zte,have you fixed this isuue?
Now I am confusing by this and have tried lots of methods,but still don't resolve it.
So,if you have ,can you share me the resolution?

**Comment by chenhb-zte** [comment]
HI @aressu1985 , you could find some ways in this issue.
https://github.com/google/clusterfuzz/issues/220

**Comment by aressu1985** [comment]
> HI @aressu1985 , you could find some ways in this issue.
> #220

Thanks!it works!
