### ISSUE TITLE
How to run fuzzing test about heartbleed example on the production

### ISSUE THREAD

**Issue by zhtrb** [google/clusterfuzz#2124]
I have follow https://google.github.io/clusterfuzz/setting-up-fuzzing/heartbleed-example/.

However, I just can find 3 bot on Bots page and all of them are in "no tasks!". And I can find 
`/fuzz-strategy-selection` and `/fuzzer-and-job-weights` are both failed.

What can I do to make this example run properly?

**Comment by zhtrb** [comment]
I do this again. And bot is run as expected. But `/fuzz-strategy-selection` and `/fuzzer-and-job-weights` still failed. How can I make this 2 run properly.

**Comment by inferno-chromium** [comment]
Check your errors in the stackdriver logs.
