### ISSUE TITLE
What are the main differences among these fuzzing engines ( libFuzzer, AFL, HonggFuzz and SyzKaller )

### ISSUE THREAD

**Issue by sanjaychaurasia** [google/clusterfuzz#2133]
I am new to Fuzz testing and studying Cluster Fuzz.
I did the google so much but I did not get proper answer of my queries related to libFuzzer, afl, honggFuzz and syzKaller which Cluster fuzz supports
Could anyone please help me to answer following queries.

1. What are the main differences among these fuzzing engines ( libFuzzer, AFL, HonggFuzz and SyzKaller )
2. Which fuzzing engine is used to find which type of bug.
3. When should we use which engine.
4. Can we use any fuzzing engine to find out any type of bug.

**Comment by oliverchang** [comment]
Hi, unfortunately this is not the right place for general fuzzing questions.

Please check out https://github.com/google/fuzzing/blob/master/docs/intro-to-fuzzing.md.
