### ISSUE TITLE
Typo in repo description? 

### ISSUE THREAD

**Issue by abhsag24** [google/clusterfuzz#214]
Hey,
shouldn't this be "all your bugs belong to us"? 
If not shouldn't it be somewhere on the readme that this is intentional :P
![image](https://user-images.githubusercontent.com/8532031/52904047-2a4b6c00-324c-11e9-8c58-8a8e3c2a0df0.png)

**Comment by Dor1s** [comment]
https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us :)

**Comment by abhsag24** [comment]
thanks, hope the issue serves as reference :P
