### ISSUE TITLE
What's the difference between "Custom Build" in Jobs and "Fuzzer archive" in Fuzzers ?

### ISSUE THREAD

**Issue by chenhb-zte** [google/clusterfuzz#216]
I added the test fuzz into "Custom Build" in Jobs as the sample,  the "Fuzzer archive" was required when creating a new fuzzer.

**Comment by oliverchang** [comment]
Custom build is a build of the target that you are trying to fuzz. Fuzzer archive is for an archive containing the [black box](https://google.github.io/clusterfuzz/reference/coverage-guided-vs-blackbox/#blackbox-fuzzing) fuzzer that you want to use to generate inputs for your target.

If you're trying to use libFuzzer/AFL, you shouldn't need to create a new Fuzzer. You can just associate your job with the existing `libFuzzer/afl` fuzzers which are created by `python butler.py run_server --bootstrap` if you are running things locally.

**Comment by chenhb-zte** [comment]
thanks!
Where can i find the documents of blackbox fuzzer?

**Comment by jonathanmetzman** [comment]
https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/
