### ISSUE TITLE
Clusterfuzz runs in a docker container,can't work

### ISSUE THREAD

**Issue by coffeezh** [google/clusterfuzz#2160]
Hi,I install all dependencies about clusterfuzz in a docker container.But when I run "python3.7 butler.py run_server --bootstrap --skip-install-deps",it stuck "Created symlink: source: /root/clusterfuzz/local/storage/local_gcs, target /root/clusterfuzz/src/appengine/local_gcs.".
    After 2 hours,it stuck "Running: python butler.py run setup --non-dry-run --local --config-dir=configs/test",and can't proceed to the next step.
    I try to visit "127.0.0.1:9000",can't access "[CRITICAL] WORKER TIMEOUT (pid:4520)".
    I don't know how to solve this problem,can you help me?
About log:
`Running: pkill -KILL -f "dev_appserver.py"
| Return code is non-zero (-9).
Running: pkill -KILL -f "CloudDatastore.jar"
| Return code is non-zero (-9).
Running: pkill -KILL -f "pubsub-emulator"
| Return code is non-zero (-9).
Running: pkill -KILL -f "run_bot"
| Return code is non-zero (-9).
Created symlink: source: /root/clusterfuzz/configs/test, target /root/clusterfuzz/src/appengine/config.
Created symlink: source: /root/clusterfuzz/src/protos, target /root/clusterfuzz/src/appengine/protos.
Created symlink: source: /root/clusterfuzz/src/python, target /root/clusterfuzz/src/appengine/python.
Running: python polymer_bundler.py (cwd='local')
| App Engine templates are up to date.
Clearing local datastore by removing local/storage.
Created symlink: source: /root/clusterfuzz/local/storage/local_gcs, target /root/clusterfuzz/src/appengine/local_gcs.
Running: gunicorn -b :9000 main:app (cwd='src/appengine')
| [2020-11-30 02:57:24 +0000] [4387] [INFO] Starting gunicorn 20.0.4
| [2020-11-30 02:57:24 +0000] [4387] [INFO] Listening at: http://0.0.0.0:9000 (4387)
| [2020-11-30 02:57:24 +0000] [4387] [INFO] Using worker: sync
| [2020-11-30 02:57:24 +0000] [4520] [INFO] Booting worker with pid: 4520
Bootstrapping datastore...
Running: python butler.py run setup --non-dry-run --local --config-dir=configs/test
| [2020-11-30 03:06:54 +0000] [4387] [CRITICAL] WORKER TIMEOUT (pid:4520)
| [2020-11-30 03:06:54 +0000] [4520] [INFO] Worker exiting (pid: 4520)
| [2020-11-30 03:06:54 +0000] [4570] [INFO] Booting worker with pid: 4570
| [2020-11-30 03:07:25 +0000] [4387] [CRITICAL] WORKER TIMEOUT (pid:4570)
| [2020-11-30 03:07:25 +0000] [4570] [INFO] Worker exiting (pid: 4570)
| [2020-11-30 03:07:25 +0000] [4577] [INFO] Booting worker with pid: 4577
| [2020-11-30 03:07:56 +0000] [4387] [CRITICAL] WORKER TIMEOUT (pid:4577)
| [2020-11-30 03:07:56 +0000] [4577] [INFO] Worker exiting (pid: 4577)
| [2020-11-30 03:07:56 +0000] [4584] [INFO] Booting worker with pid: 4584
`

**Comment by inferno-chromium** [comment]
You need to strace on that command to see where it is getting stuck, does it have access to network ? Are you running bot and server on same or different machines ?

**Comment by coffeezh** [comment]
I strace on that command found "/clusterfuzz/src/python/google_cloud_utils/pubsub.py", line 187, in create_topic".Can't access "http://localhost:9006/v1/projects/test-clusterfuzz/topics/jobs-linux?alt=json",show 404.And see "http://localhost:9006/v1/projects/test-clusterfuzz/topics/" is null.

How to produce "http://localhost:9006/v1/projects/test-clusterfuzz/topics/"，I don't know how to create topics.

**Comment by coffeezh** [comment]
Hi,I found "PUT" command can't produce "/v1/projects/test-clusterfuzz/topics/jobs-linux?alt=json".The problem is socket.timeout.I don't know how to solve this problem,need your help,thanks.

**Comment by coffeezh** [comment]
Hi,I solve this problem.In a docker environment,I set the proxy,it will can't connect pubsub emulators.After I unset proxy,this problem gone.Thank you very much.
