### ISSUE TITLE
Why it only  shown 1 test case in testcases page?

### ISSUE THREAD

**Issue by chenhb-zte** [google/clusterfuzz#217]
ClusterFuzz was deployed locally. 
Started 2 bots and created 2 different jobs, they crashed. BUT Only 1 test case was shown.

**Comment by chenhb-zte** [comment]
Job type is libFuzzer

**Comment by jonathanmetzman** [comment]
>ClusterFuzz was deployed locally.
Started 2 bots and created 2 different jobs, they crashed. BUT Only 1 test case was shown.

Which testcase was this?
One of the big benefits of ClusterFuzz is that it deduplicates crashes. Meaning that if the same crash is found twice or more, only one testcase gets created.

>Job type is libFuzzer. The heartbleed example was not shown. :(

Did you see the crash happen in your logs?

**Comment by chenhb-zte** [comment]
HI @jonathanmetzman   Yes , i saw the crash in bot logs. They are the same crash type "Heap-buffer-overflow", but they are belong to the different job, one is heartbleed, another is my custom function

`bool VulnerableFunction1(const uint8_t* data, size_t size) {
      bool result = false;
      if (size >= 3) {
          result = data[0] == 'F' &&
          data[1] == 'U' &&
          data[2] == 'Z' &&
          data[3] == 'Z';
      }
      return result;
}
`

`
#include "vulnerable_functions.h"

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
      VulnerableFunction1(data, size);
      return 0;
}
`

**Comment by jonathanmetzman** [comment]
How long has your server run for and it still hasn't appeared?
Based on #197 it might be a while for the crash to become a testcase.
Can you please post the bot logs where your heartbleed crash is found?

**Comment by chenhb-zte** [comment]
Thanks for your reminding.  I commented the `start_cron_threads()`  to inspect, forgot this comment.Now that is all right.
I am the beginner for ClusterFuzz, try to introduce it into our project. Looks ClusterFuzz is suitable for c or c++ with clang tool chain,  have some samples which is coded with Python?

**Comment by jonathanmetzman** [comment]
>I am the beginner for ClusterFuzz, try to introduce it into our project.

Please do! Is it a C/C++ project?

>Looks ClusterFuzz is suitable for c or c++ with clang tool chain, 

Yes. Though other languages with fuzzing support such as rust, and go (with some effort) should work.

>have some samples which is coded with Python?

No not really, we focus on finding bugs in the languages mentioned above though in theory if someone were to write a fuzzer for python, integrating it in ClusterFuzz wouldn't be too hard.

**Comment by chenhb-zte** [comment]
> Please do! Is it a C/C++ project?

Yes, contain a C/C++ project， but use the GCC tool chain now. 

> Yes. Though other languages with fuzzing support such as rust, and go (with some effort) should work.

So it could support other languages which could be compiled with LLVM tool, not only C/C++ ?

**Comment by jonathanmetzman** [comment]
> > Please do! Is it a C/C++ project?
> 
> Yes, contain a C/C++ project， but use the GCC tool chain now.
> 
> > Yes. Though other languages with fuzzing support such as rust, and go (with some effort) should work.
> 
> So it could support other languages which could be compiled with LLVM tool, not only C/C++ ?

I'm not too familiar with them, but I think they might work pretty easily. We do have some rust fuzzers running on ClusterFuzz already actually.
