### ISSUE TITLE
Missing permissions on GCP default service account

### ISSUE THREAD

**Issue by 4OH4** [google/clusterfuzz#2171]
Having done a fresh setup of Clusterfuzz on GCP, following these instructions:
https://google.github.io/clusterfuzz/production-setup/clusterfuzz/

The user interface was accessible at `https://<project-name>.appspot.com`,  although an error was generated when accessing 'Upload Testcase' via the menu:

`<HttpError 403 when requesting https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/<project-name>@appspot.gserviceaccount.com:signBlob?alt=json returned "The caller does not have permission"> (<my account email address>)`

To rectify this, I added the 'Service Account Token Creator' role to the 'App Engine default service account' via the GCP console (Access -> IAM), as suggested by [this post](https://stackoverflow.com/questions/57564505/unable-to-assign-iam-serviceaccounts-signblob-permission). (N.B. I'm not an expert on IAM policies, so that may be an overkill solution with other side effects.)

**Comment by inferno-chromium** [comment]
Either whitelist your domain by adding here - https://github.com/google/clusterfuzz/blob/master/configs/test/gae/auth.yaml#L19 and then deploy
Or add your email to IAM as Project Viewer. You shouldn't be changing service account permissions, etc.
