### ISSUE TITLE
How to achieve the shared seed of all fuzzers performing the same target?

### ISSUE THREAD

**Issue by gtt1995** [google/clusterfuzz#2182]
Hello,
Excuse me,
First,i already deploy the clusterfuzz to run locally,
Now, i want fuzz a target program by using afl,libfuzzer,honggfuzz and other greybox fuzzer etc. at the same time,
note that ,i need to exchange the testcases  between them Periodically.
How should i implenment this new feature?
ie,which source code should i modify?
thanks
wish you good!

**Comment by inferno-chromium** [comment]
This is already done automatically, they share the same libFuzzer corpus.
See
https://github.com/google/clusterfuzz/blob/master/src/local/butler/scripts/setup.py#L57
https://github.com/google/clusterfuzz/blob/master/src/local/butler/scripts/setup.py#L70

**Comment by gtt1995** [comment]
hello,
what i want ask is if i use libfuzzer , afl,honggfuzz to fuzz the same target binary ,like xpdf, can they share afl_corpus,libfuzzer_corpus and honggfuzz_corpus 
As described in this article  https://wcventure.github.io/FuzzingPaper/Paper/USENIX19_EnFuzz.pdf
 if not ,which source code should i modify? please,thanks

    Abstract: Fuzzing is widely used for software vulnerability detection. There are various kinds of fuzzers with different fuzzing strategies, and most of them perform well on their targets. However, in industry practice and empirical study, the performance and generalization ability of those well-designed fuzzing strategies are challenged by the complexity and diversity of real-world applications. In this paper, inspired by the idea of ensemble learning, we first propose an ensemble fuzzing approach EnFuzz, that integrates multiple fuzzing strategies to obtain better performance and generalization ability than that of any constituent fuzzer alone. First, we define the diversity of the base fuzzers and choose those most recent and well-designed fuzzers as base fuzzers. Then, EnFuzz ensembles those base fuzzers with seed synchronization and result integration mechanisms. For evaluation, we implement EnFuzz , a prototype basing on four strong open-source fuzzers (AFL, AFLFast, AFLGo, FairFuzz), and test them on Google’s fuzzing test suite, which consists of widely used real-world applications. The 24-hour experiment indicates that, with the same resources usage, these four base fuzzers perform variously on different applications, while EnFuzz shows better generalization ability and always outperforms others in terms of path coverage, branch coverage and crash discovery. Even compared with the best cases of AFL, AFLFast, AFLGo and FairFuzz, EnFuzz discovers 26.8%, 117%, 38.8% and 39.5% more unique crashes, executes 9.16%, 39.2%, 19.9% and 20.0% more paths and covers 5.96%, 12.0%, 21.4% and 11.1% more branches respectively.

**Comment by inferno-chromium** [comment]
That is exactly what we do, we make afl and hongfuzz use corpus directory with the same name as libFuzzer, so it effectively cross pollinates.

**Comment by gtt1995** [comment]
hello,i am sorry ,but i want to make sure if i got what you mean 
Like this case,  aiming at the same target program,(for example , xpdf program), they fuzzers can share .pdf files as testcase?
as you say,afl,honggfuzz can share corpus with libfuzzer, is there some limitations? for example, i have 7 jobs now, afl_xpdf,afl_ffmpeg,honggfuzz_bzip,honggfuzz_openssl,libfuzzer_tcpdump,libfuzzer_xpdf,libfuzzer_bzip,they all work together，what testcases will they share?
what corpus do they use?
Thanks for reading! Looking forward to your answer
