### ISSUE TITLE
why does my clusterfuzz(local) not support rnn_model？

### ISSUE THREAD

**Issue by gtt1995** [google/clusterfuzz#2183]
Hello,
Excuseme,
i deploy clusterfuzz locally(in docker)，it seems that my rnn_model not work.

**Comment by inferno-chromium** [comment]
It is not enabled by default. you need to do two things

1. Set
ML_MODELS_TO_USE: rnn_generator
in your job type for libFuzzer ASan
2. Create some training bots for
https://github.com/google/clusterfuzz/blob/master/configs/test/gce/clusters.yaml#L40

**Comment by gtt1995** [comment]
thanks
