### ISSUE TITLE
Found an obsolete TODO comment

### ISSUE THREAD

**Issue by beyondacm** [google/clusterfuzz#2186]
##### SUMMARY
Found an obsolete TODO comment within src/python/bot/fuzzers/libFuzzer/stats.py (line:170). 
The TODO comment mentions that "remove include_strategies", but the parameter "include_strategies" had already been removed in an earlier version (https://github.com/google/clusterfuzz/commit/055b529c4c8958711c0530637fa901e1b935d53a), which means this TODO comment is obsolete & may confuse the developers who perform the subsequent development.  

##### ISSUE TYPE

- Bugfix issue

##### COMPONENT NAME

src/python/bot/fuzzers/libFuzzer/stats.py (line:170)

##### ADDITIONAL INFORMATION

The pending task of the TODO comment has already performed in the earlier version, but the TODO comment was not removed accordingly at the moment. Please check the following commit: https://github.com/google/clusterfuzz/commit/055b529c4c8958711c0530637fa901e1b935d53a

**Comment by beyondacm** [comment]
It would be very much appreciated if anyone could confirm my assumption, @inferno-chromium @oliverchang @mbarbella,  many thanks in advance. :)

**Comment by inferno-chromium** [comment]
Please sign the cla and then we can review your PR.
