### ISSUE TITLE
How can i get the coverage information ?(clusterfuzz locally)

### ISSUE THREAD

**Issue by gtt1995** [google/clusterfuzz#2202]
Hello,i deployed clustefuzz locally, how can I get coverage information in time？
According to this instruction:https://google.github.io/clusterfuzz/using-clusterfuzz/advanced/code-coverage/   i failed.
Which dir store the latest corpus backup?
Should i recompile the src with clang?
When i build all the fuzzers in the project with code coverage instrumentation,  what arguments should i set ? 
I am sorry i have to many questions.
Thank you for your answers!

**Comment by oliverchang** [comment]
If you are running ClusterFuzz locally, you can find GCS artifacts in local/storage/local_gcs. The default bucket is "test-backup-bucket".

Coverage information is not generated by ClusterFuzz, but requires your own scripts/infra to generate based on the corpus backups on GCS.

**Comment by gtt1995** [comment]
hello,
why my test-backup-bucket is empty?
but there are some seeds in the test-corpus-bucket?
