### ISSUE TITLE
How can we dump the output from AppEngine?

### ISSUE THREAD

**Issue by lipeng28** [google/clusterfuzz#2204]
Hi There

After I checked the implementation of AppEngine, I would like to know more details in depth of it, so I decide to dump some outputs in AppEngine implementation. However, print() does not work, shall I ask if you have better suggestions to dump the outputs.

Thanks
Peng

**Comment by inferno-chromium** [comment]
Use logs module, see example - https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/triage.py#L330

**Comment by lipeng28** [comment]
> Use logs module, see example - https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/triage.py#L330
> That you can see in stackdriver.

How can I access stackdriver, is it located in the bot.log?

**Comment by oliverchang** [comment]
If you have deployed to GCP, you can follow this: https://cloud.google.com/logging/docs/view/logs-viewer-interface
