### ISSUE TITLE
Why my test-backup-bucket is empty? (clusterfuzz locally)

### ISSUE THREAD

**Issue by gtt1995** [google/clusterfuzz#2216]
hello,
i find my local clusterfuzz test-backup-bucket is empty when i want to get coverage information
but there are some testcases in the test-corpus-bucket.
#2202 
follow this instruction :https://google.github.io/clusterfuzz/using-clusterfuzz/advanced/code-coverage/  
right?
thanks!

**Comment by inferno-chromium** [comment]
have no clue, you need to debug on your own here.
locally coverage has never been tested, only in prod environment from appengine. several of cron only run in prod and not in local runs.

**Comment by gtt1995** [comment]
thanks,
I have thought of a new method.
