### ISSUE TITLE
clusterfuzz(locally),round 0,1,2,3 why they all start form initial point?

### ISSUE THREAD

**Issue by gtt1995** [google/clusterfuzz#2217]
I trace the bot_tmp_dir's log, the target coverage from 3000 to 3900 in 1950s  at the round 0,but in the  round 1,2,3 the  initial cov is  about 3000, why it does not start at breakpoint (3900)?
one difference is the number of seeds in corpus
It seems to waste a lot of time？
thanks

**Comment by inferno-chromium** [comment]
Paste the bot.log output, it is unclear what you mean. We always use what is currently in local corpus for the each of those 4 runs, so it should be using the improved corpus after every run.

**Comment by gtt1995** [comment]
thanks,As you said，Every run has a little improvement, but each run  costs 1950s, I think there is a little waste of time? Should I set a shorter fuzzing time? How long is suitable?

**Comment by gtt1995** [comment]
I also encountered another problem. When I started uploading a build, it always found a large number of new units in the first fuzzing round 0, and all the following rounds (round 1,2,3;round0,1,2,3; round0,1,2,3.........) Almost only a few units were found? is this normal?

**Comment by gtt1995** [comment]
This gives me the feeling that the fuzzer has stopped, as if it has encountered an obstacle? Or not continue to work without following the breakpoint? Can't it always explore new paths like libfuzzer does locally?
thanks!

**Comment by gtt1995** [comment]
Hello,
I have another question,
Which strategies(rnn) are effective in the clusterfuzz locally?
rnn_generation stategy  doesn't seem to work?
there isn't a rnn_model?
about other strategies?
