### ISSUE TITLE
Can not re-upload the testcase in local development

### ISSUE THREAD

**Issue by chenhb-zte** [google/clusterfuzz#222]
Tried to re-upload the testcase in the detail page of testcase,  reported "ERROR" or  performed the pending status.

**Comment by jonathanmetzman** [comment]
Couldn't repro this. Re-upload works fine for me.
Can you post more details about the "ERROR" message you're seeing?
How long have you been waiting for pending to resolve? Mine took less than 10 minutes after re-uploading for the stacktrace to be added to the testcase. FYI it will remain pending until a free bot gets a chance to run the testcase.

**Comment by chenhb-zte** [comment]
> Can you post more details about the "ERROR" message you're seeing?

Only "ERROR" , no other information. looks like it is timeout.

> How long have you been waiting for pending to resolve?

a long time. it does not seem  the status will be changed.  The bot is repeatedly running all the time after fuzzing,  how can i stop it ?

**Comment by jonathanmetzman** [comment]
> > Can you post more details about the "ERROR" message you're seeing?
> 
> Only "ERROR" , no other information. looks like it is timeout.

Post server and bot logs please.

> 
> > How long have you been waiting for pending to resolve?
> 
> a long time. it does not seem the status will be changed. The bot is repeatedly running all the time after fuzzing, how can i stop it ?

Are you using the heartbleed example or do you have real jobs that are being fuzzed? If you have real jobs then you need to wait for fuzzing to end which can take hours. In that case I would restart the bot or start another bot.

**Comment by chenhb-zte** [comment]
> Post server and bot logs please.

Where can i get the server logs ?

> Are you using the heartbleed example or do you have real jobs that are being fuzzed?

heartbleed.

**Comment by jonathanmetzman** [comment]
> > Post server and bot logs please.
> 
> Where can i get the server logs ?

The output from when you run run_server
(bot logs can be gotten from bot.log inside your bot directory)

**Comment by chenhb-zte** [comment]
1、re-upload testcase issue
  stopped bots via ctrl + c, then restart server and bot,  testcase could be successfully uploaded.  The reason should be the server was too busy.  Anyway,  i want here it has 2 issues. 
  1) There is not a friendly prompt message when the server is busy,  I only saw "ERROR" message.
  2) The uploaded testcase  show the pending all the time, and not changed.
![image](https://user-images.githubusercontent.com/18586714/53065369-542fb780-3506-11e9-9efc-7d0490fc1409.png)

2、The testcase is running all the time,  i did not know how to stop it except ctrl + c.
    please look the bot logs fragment.  https://xsnippet.org/363955

**Comment by jonathanmetzman** [comment]
Isn't libfuzzer_asan_first_fuzz a different job than heartbleed :-)?

>1. There is not a friendly prompt message when the server is busy,  I only saw "ERROR" message.

I'm not sure what you mean, where did you see this error message (what did you do for it to come up?)

>2\. The uploaded testcase  show the pending all the time, and not changed.
When you go to localhost:9000/testcase-detail/6544293208522752 does it say "pending"?

I'll have to try again with multiple jobs.

What version of ClusterFuzz are you running a release or did you clone from master (if you did, can you run git log and tell me what is the first commit?).

Also, can you confirm you haven't modified the source of CF (like was the case in the last bug)

**Comment by chenhb-zte** [comment]
> Isn't libfuzzer_asan_first_fuzz a different job than heartbleed :-)?

Yes, they are different job

> I'm not sure what you mean, where did you see this error message (what did you do for it to come up?)

When i created the re-upolad testcase, the ERROR performed on the upload-testcase dialog due to the busy server.
![image](https://user-images.githubusercontent.com/18586714/53070088-fe183f80-3518-11e9-9e5e-50e4798c65f0.png)

clone it from master, the commit is 7cf416d51ad206f4d902a8390ab45ebcbbf32820
What is the source of CF ?  I should not modify them.

Also,  i want to know why bots is repeatedly running those testcases all the time.

> I'm not sure what you mean, where did you see this error message (what did you do for it to come up?)

When i created the re-upolad testcase, the ERROR performed on the upload-testcase dialog due to the busy server.
![image](https://user-images.githubusercontent.com/18586714/53070088-fe183f80-3518-11e9-9e5e-50e4798c65f0.png)

clone it from master, the commit is 7cf416d51ad206f4d902a8390ab45ebcbbf32820
What is the source of CF ?  I should not modify them.

Also,  i want to know why bots is repeatedly running those testcases all the time.

**Comment by jonathanmetzman** [comment]
>Also, i want to know why bots are repeatedly running those testcases all the time.

I don't think it is running a testcase. I didn't see that in the logs you posted.
I'll try to see if there is an issue uploading testcases tomorrow.

**Comment by jonathanmetzman** [comment]
I can't repro this unfortunately.

**Comment by chenhb-zte** [comment]
HI  @jonathanmetzman  Thanks for tracking this issue. In my opinion, This issue should be reproduced while the capacity (memory,cpu,etc) is not enough in your environment. 
My host contains 4 cores CPU and 8G memory , then running AppEngine and 2 bots on the host.  You try to upload the testcase when bots are running the fuzz.

**Comment by jonathanmetzman** [comment]
I'll see if I can do this.

**Comment by inferno-chromium** [comment]
Do you still see this. I think this might be related if you are using a proxy.
