### ISSUE TITLE
 when install dependencies using ./local/install_deps.bash on ubuntu， I get the following error bower ESUDO Cannot be run with sudo

### ISSUE THREAD

**Issue by hellozhuzhu** [google/clusterfuzz#224]
local/install_deps_linux.bash#L122
bower install
I think `“--allow-root”` should be add here

**Comment by oliverchang** [comment]
install_deps.bash is not intended to be run with sudo. Is there any reason why you are doing that?

**Comment by hellozhuzhu** [comment]
![image](https://user-images.githubusercontent.com/46521901/53065771-0b78fe00-3508-11e9-8184-626074474766.png)
look like this

**Comment by hellozhuzhu** [comment]
The above problem occurs when I install using the root user.

**Comment by hellozhuzhu** [comment]
Is it necessary to add a permission to judge

**Comment by zlrs** [comment]
it seems you should run `install_deps.bash` with normal user, like `ubuntu`, not `root`, and without `sudo` in front of the command.

**Comment by hellozhuzhu** [comment]
Yes, I know that, I just ask this position to need to add permission to judge

**Comment by jonathanmetzman** [comment]
@hellozhuzhu Is this issue resolved?

**Comment by hellozhuzhu** [comment]
yes
