### ISSUE TITLE
clusterfuzz can use for Java or C# project?

### ISSUE THREAD

**Issue by Wind1991** [google/clusterfuzz#225]
can I use clusterFuzz to test Java or C# project?

**Comment by jonathanmetzman** [comment]
The short answer is probably not without modifying ClusterFuzz.

The longer answer is: that we've never done it so you would be on your own. If you can find a fuzzer for Java or C# you can integrate it with ClusterFuzz and submit a patch. You would also need to add some code to recognize errors in your language's runtimes. I think we have some of this already for Java.
