### ISSUE TITLE
Public OSS-Fuzz backups no longer public

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#2268]
Just noticed this happening today.
Here's how to repro:

```
curl https://storage.googleapis.com/systemd-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/systemd_fuzz-xdg-desktop/public.zip/public.zip
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
```

This probably impacts corpus pollination as well as CIFuzz.

**Comment by oliverchang** [comment]
Where did you find the link `https://storage.googleapis.com/systemd-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/systemd_fuzz-xdg-desktop/public.zip/public.zip` ?

The link is wrong. "public.zip" is duplicated.

**Comment by jonathanmetzman** [comment]
> Where did you find the link `https://storage.googleapis.com/systemd-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/systemd_fuzz-xdg-desktop/public.zip/public.zip` ?
> 
> The link is wrong. "public.zip" is duplicated. curl on the correct link works.

Ha. I sort of crafted it myself because a test where https://storage.googleapis.com/example-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/example_nocrash_fuzzer/public.zip was downloaded started failing. That one actually doesn't work.

**Comment by oliverchang** [comment]
That one doesn't exist (and a 403 is returned because the bucket itself is private).

The "example" project also is set to `disabled: true`, so we don't run this on ClusterFuzz (and hence no corpus backup).

**Comment by oliverchang** [comment]
Closing as WAI, but please reopen if you notice any other issues.
