### ISSUE TITLE
Question: Calling the function form.generate_csrf_token() via script - Error with ndb context

### ISSUE THREAD

**Issue by temp1337temp1337** [google/clusterfuzz#2279]
Hey all, 

I am trying to invoke the method `form.generate_csrf_token()`, from the file: `src/appengine/libs/form.py` in order to generate a CSRF token via a script. 

This however results in the following error: 
`google.cloud.ndb.exceptions.ContextError: No current context. NDB calls must be made in context established by google.cloud.ndb.Client.context.`

The only [solution](https://stackoverflow.com/questions/63929626/no-current-context-error-after-python-3-migration-should-i-include-more-logic) to this issue is to use a middleware, which I can see it is used here: `src/appengine/server.py`. However, I am still not sure how or if I can use this in this case. I have also tried using the `ndb_init` file (as shown here: `src/local/butler/run.py`), but this does not work either.

Does anyone know how can I get this information from the middleware or any way in general that I can get a valid CSRF token programmatically? 

Thanking you so much in advance!

**Comment by inferno-chromium** [comment]
if you need to call NDB, you need to call using a `with` wrap, like

with ndb_init.context():

see https://github.com/google/clusterfuzz/blob/master/src/python/bot/startup/run_bot.py#L183
