### ISSUE TITLE
Exception crashes being marked as security

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#2295]
Reported to us by @alex 
https://bugs.chromium.org/p/oss-fuzz/issues/list?q=Type%3DBug-Security%20exception&can=1 

CC @fmeum

**Comment by inferno-chromium** [comment]
Jake, this could be a good first bug to understand clusterfuzz, fix stack parsing, run tests, etc. Please work with either Oliver/Jonathan on this.

**Comment by fmeum** [comment]
I don't know what's up with the python exceptions here, but those seem to predate Jazzer.

The Java exceptions are working as intended IMO: Jazzer reported uncaught exceptions that contain the new manual severity markers (`FuzzerSecurityIssueLow` in this case) and were thus labeled as security bugs.

It's debatable whether the reported class should be different, but we decided to postpone that decision. Letting Jazzer report issues of classes other than `Uncaught exception` would also complicate matters a bit: While e.g. a timeout or OOM may not be considered a security issue in the C/C++ world, it would likely be viewed as a (low severity) security issue in the Java world.

**Comment by oliverchang** [comment]
Closing since Java exceptions are WAI.

For the Python ones, they were prior to https://github.com/google/clusterfuzz/commit/a6bb73e4988f4a7064e990a0a78cc6bc812ef741 (which fixed the issue with marking them generally as security).
