### ISSUE TITLE
Collaborative Fuzzing/Ensemble Fuzzing

### ISSUE THREAD

**Issue by hpathuri** [google/clusterfuzz#2322]
Hello,

Could we have a fuzzing binary that be used by libFuzzer, AFL, hongFuzz etc. on ClusterFuzz? Does this feature work and has it been tested?

Could not find much documentation     @ https://github.com/google/clusterfuzz

**Comment by inferno-chromium** [comment]
It automatically just works, just define the libfuzzer, honggfuzz, afl job types and then they just share the same corpora automatically, see "CORPUS_FUZZER_NAME_OVERRIDE = libFuzzer" in afl and honggfuzz templates here - https://github.com/google/clusterfuzz/blob/master/src/local/butler/scripts/setup.py#L57
