### ISSUE TITLE
can the server  listen to the port rather than instead of local address 127.0.0.1 and port

### ISSUE THREAD

**Issue by juewuer** [google/clusterfuzz#233]
the server listening local address 127.0.0.1, can it be changed to 0.0.0.0, so that an external client can connets the the server?

![image](https://user-images.githubusercontent.com/6682310/53235783-a3741480-36cd-11e9-8560-5e5cd9152d02.png)
such as 127.0.0.1:9000? change to 0.0.0.0:9000?

**Comment by jonathanmetzman** [comment]
I'm not sure how to make this configurable, but 127.0.0.1 should definitely be default since anyone with access to the development server can essential get code execution on the bots (ie: your computer).

**Comment by Dor1s** [comment]
You need to pass `--host` argument to `dev_appserver.py` here https://github.com/google/clusterfuzz/blob/master/src/local/butler/run_server.py#L177

**Comment by vijaykestwal** [comment]
> You need to pass `--host` argument to `dev_appserver.py` here https://github.com/google/clusterfuzz/blob/master/src/local/butler/run_server.py#L177

Hello, 
I'm new to clusterfuzz and was trying to run on linux machine and access via windows. 
But I'm facing issue while uploading zip file.
When i checked port 9008 is running at localhost but i added --host as 0.0.0.0 

"tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      15961/python"
"tcp        0      0 127.0.0.1:9008          0.0.0.0:*               LISTEN      15688/gcs" 


Can you please help me know what i'm missing?

Thanks.

**Comment by Dor1s** [comment]
> But I'm facing issue while uploading zip file.


What's the issue you are facing?

**Comment by vijaykestwal** [comment]
[error_log.txt](https://github.com/google/clusterfuzz/files/3299701/error_log.txt)

I updated error log.

https://github.com/google/clusterfuzz/issues/163
As per above issue i tried port port forwarding for 9000 and 9008 and able to access both port from remote.

target     prot opt source               destination
DNAT       tcp  --  anywhere             anywhere             tcp dpt:9008 to:127.0.0.1:9008
DNAT       tcp  --  anywhere             anywhere             tcp dpt:9000 to:127.0.0.1:9000

**Comment by Dor1s** [comment]
I'm not an expert in `iptables`, so can't really help you with the rules, but can suggest running something like `nc -lvvv -p 9008` on the server and trying to access it from your windows machine.
