### ISSUE TITLE
How to run main.py in src/appengine

### ISSUE THREAD

**Issue by lipeng28** [google/clusterfuzz#2381]
Hi There
I tried to run main.py directly in src/appengine, it keeps throwing errors shown below:

Traceback (most recent call last):
  File "main.py", line 43, in <module>
    import server
  File "/home/xxx/bytefuzz/src/appengine/server.py", line 21, in <module>
    from base import utils
  File "python/base/utils.py", line 32, in <module>
    from base import memoize
  File "python/base/memoize.py", line 23, in <module>
    from base import persistent_cache
  File "python/base/persistent_cache.py", line 21, in <module>
    from metrics import logs
ImportError: cannot import name 'logs' from 'metrics' (/home/xxx/.local/share/virtualenvs/bytefuzz-TNrYIRUR/lib/python3.7/site-packages/metrics/__init__.py)

Did I miss something?
Thanks
Peng

**Comment by lipeng28** [comment]
At present, I could execute python main.py without any issues. However, I did not find server running normally, can you please advise how to run main.py correctly? Thanks

**Comment by oliverchang** [comment]
Hi, can you try running with:

`python butler.py run_server` instead of running main.py directly?

**Comment by lipeng28** [comment]
Hi, I could. However, I do not want to run it in the local dev environment, we have hacked clusterfuzz a bit, and would like to deploy it under the production environment.

**Comment by oliverchang** [comment]
https://github.com/google/clusterfuzz/commit/4f8020c4c7ce73c1da0e68f04943af30bb5f0b32 will probably help here, as it looks like you had an import conflict. However, running the server without `python butler.py run_server` is not supported.
