### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by kennethkang** [google/clusterfuzz#2403]
https://github.com/google/clusterfuzz/blob/c67604c9d915159d334ee84df02ac26e8630d6e2/src/clusterfuzz/_internal/platforms/android/adb.py#L539

`device_serial` from `environment.get_value()` can return `None`

**Comment by oliverchang** [comment]
Yeah, there are many cases like this. It's a configuration error to not have the serial set at this point.
