### ISSUE TITLE
How can I best verify a job is running in production?

### ISSUE THREAD

**Issue by jfoote** [google/clusterfuzz#2437]
Hello,

I'm setting up a new production clusterfuzz instance. I've confirmed my bot runner VMs have been created. I've also manually created a Job from a simple test fuzz target zip file.

What is the best way to determine if the Job is executing? I'll share some of the things I've tried so far below for reference.

Thanks,
Jon

PS This instance is deployed to a constrained GCP environment. I ran into some extraneous permissions issues on setup but I believe I've addressed them. And have re-deployed several times since.

### GCE logs and monitoring
- The GCE CPU monitoring data show regular utilization for one of my `clusterfuzz-linux-pre` VMs, analogous to a busy fuzz target
- The Stackdriver logs for the same node don't contain meaningful details on fuzzer execution; I assume it is not being used by the bot runner

### Fuzzing stats
When I run a query via the Fuzzer Stastics page, I receive an error along the lines of:

```
Table (redacted).libFuzzer_stats.TestcaseRun does not have a schema.
```

I see similar errors from other codepaths in Stackdriver. Some AppEngine Cloud Scheduler jobs fail accordingly. The BigQuery console confirms the table doesn't have a schema.

I couldn't find where the schema is defined in the source code; the `datasets.yaml` and `engine_stats.jinja` files don't appear to define them. Perhaps it happens the first time the stats are written.

### Remote bot logs

When I run the `python butler.py remote tail` command on `v2.5.1` I receive a SyntaxError as follows:

```
(clusterfuzz) clusterfuzz@cf-staging-host:~/clusterfuzz$ python butler.py remote -i clusterfuzz-linux-ntcq tail bot 10
Traceback (most recent call last):
  File "butler.py", line 317, in <module>
    main()
  File "butler.py", line 302, in main
    command = importlib.import_module('local.butler.%s' % args.command)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/local/butler/remote.py", line 20, in <module>
    from fabric import api
  File "/home/clusterfuzz/.local/share/virtualenvs/clusterfuzz-Rm_c02UG/lib/python3.7/site-packages/fabric/api.py", line 10, in <module>
    from fabric.context_managers import (cd, hide, settings, show, path, prefix,
  File "/home/clusterfuzz/.local/share/virtualenvs/clusterfuzz-Rm_c02UG/lib/python3.7/site-packages/fabric/context_managers.py", line 535
    def accept(channel, (src_addr, src_port), (dest_addr, dest_port)):
                        ^
SyntaxError: invalid syntax
```

### Checking GCS buckets
Several GCS buckets associated with the project have been created, but all that I have spot-checked appear to be empty.

**Comment by the-xentropy** [comment]
I'm having the same issue right now. Though for me all the log files are empty despite that I can verify my build was pushed to the bot, Nevertheless, I'm struggling to conclusively determine if everything is working and if the fuzz jobs are actually doing anything.

A possible easy way to offer us a way to do this is hosting a sample custom build in the github repo (or elsewhere) that once pushed is expected to generate a few test cases. As it is I'm not sure if my fuzzer is to blame, the bot is to blame, or much of anything.

**Comment by jfoote** [comment]
@the-xentropy I wound up enabling [GCP OS login](https://cloud.google.com/compute/docs/instances/managing-instance-access) for the project. Then adding keys and ssh'ing to the fuzz VMs and inspecting the logs directly (e.g. via `docker log`). In my case the container startup code was stuck in a loop due to a latent IAM permission issue, FWIW.

**Comment by oliverchang** [comment]
Sorry for the very delayed responses here. In general, for debugging, a production CF deployment will push all logs to Cloud Logging that you can search/query through, assuming the bot has made it to running the actual CF code. 

Re `butler.py remote`, sadly this code has bitrotted and will likely have to be removed. 

> I wound up enabling GCP OS login for the project. Then adding keys and ssh'ing to the fuzz VMs and inspecting the logs directly (e.g. via docker log). In my case the container startup code was stuck in a loop due to a latent IAM permission issue, FWIW.

What kind of permission issue was this? I'm wondering if we can surface this in a more obvious way somehow.

**Comment by jfoote** [comment]
No worries on the delay. Thanks for the info @oliverchang!

> What kind of permission issue was this? I'm wondering if we can surface this in a more obvious way somehow.

I'm not sure this will be a common problem, but FWIW: the GCP project I was deploying to had the default service account removed. This was done automatically upon provisioning as part of a bespoke policy. I had undeleted the account, but for some undiagnosed reason it did not recover its associated role (not could any binding be associated with it). 

As mentioned above, this manifested itself as the container startup code looping infinitely. The `docker logs` output was of the form `AccessDeniedException: 403 XXXXXXXXXX-compute@developer.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket.`

I ultimately resolved the issue by creating a new service account with the required permissions and using that.
