### ISSUE TITLE
Jira v3 API integration issues

### ISSUE THREAD

**Issue by jfoote** [google/clusterfuzz#2499]
Hello,

I recently integrated a clusterfuzz deployment with an Atlassian Cloud Jira instance. Here are some issues I ran into:

- The clusterfuzz documentation does not describe how to integrate with Jira.
    - E.g., the relationships between clusterfuzz project name, ISSUE_TRACKER Job env var, and Jira project name are unclear
 - There are several incompatibilities between the clusterfuzz Jira integration implementation and the Jira REST v3 API
     - password-based authentication is no longer supported
     - clusterfuzz uses an integer-type project ID, whereas Jira uses a string-type project ID
     - Jira users are no longer identified via the `'name'` field
     - Various other incompatibilities
 - The secret used to authenticate with the Jira API is reflected in cleartext in the clusterfuzz UI

I was able to integrate the clusterfuzz deployment with Jira via some bespoke patching. But, I didn't address all the issues with synchronization and my code is generally unsuitable for contribution unfortunately. I wanted to share this information FYI and for any others that might attempt to integrate with Jira.

Thanks,
Jon

**Comment by oliverchang** [comment]
Thanks for the super helpful pointers to the issues! 

@bhatkishor FYI who contributed the initial support for this. We'd be very happy to help review any contributions to help make Jira V3 easier to use for you.
