### ISSUE TITLE
Builds uploaded to a bucket root are not detected

### ISSUE THREAD

**Issue by mykter** [google/clusterfuzz#251]
If you upload builds to, say, the root of the blobs bucket, they are not detected. Instead you get lots of `Error getting list of release build urls.` errors logged. If you move them (and update their job definition) to a folder within a bucket, they are picked up.

I think the culprit is https://github.com/google/clusterfuzz/blob/master/src/python/build_management/build_manager.py#L920 which adds a `/` into the regexp match.

The example in the docs doesn't include a folder, so I'm wondering if there is something else going on, or if it's just never been tested like this.

It might be helpful if that error message included the job build URL being used too.

**Comment by inferno-chromium** [comment]
I think @oliverchang last made some changes in that file, so assigning to his queue.

**Comment by inferno-chromium** [comment]
I am sheriff this week, so looking.

**Comment by inferno-chromium** [comment]
fixed in https://github.com/google/clusterfuzz/commit/6e92d54be3ad87ae6e689a6220eced164040a91e

**Comment by mykter** [comment]
thanks!
