### ISSUE TITLE
Recently test samples have magically disappeared from the web dashboard( https://clusterfuzz.com)

### ISSUE THREAD

**Issue by cooolie** [google/clusterfuzz#2532]
like this https://clusterfuzz.com/testcase-detail/4785404576071680 say Invalid test case! 
This is a link that can be accessed, but I can't see it on my fuzz testcase page (https://clusterfuzz.com/testcases)

These 2 links are chrome fuzzer I submitted running on clusterfuzz.

**Comment by oliverchang** [comment]
Hi @cooolie. This is expected behaviour -- We auto-delete non-reproducible testcases after some time as part of periodic cleanup.
