### ISSUE TITLE
Throttle / limit number of times we file an unreproducible crash

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#2533]
This can lead to spam: https://bugs.chromium.org/p/oss-fuzz/issues/list?q=%22Sanitizer%20CHECK%20failure%22%20curl&can=1 and developer confusion: https://github.com/google/oss-fuzz/issues/6879

**Comment by DavidKorczynski** [comment]
Another spam-related issue from OSS-Fuzz is this one https://github.com/google/oss-fuzz/issues/7040

Monorail query showing 100+ reports for same issue: https://bugs.chromium.org/p/oss-fuzz/issues/list?q=%22ASSERT%3A%20byte%20index%22%20json5format&can=1

**Comment by oliverchang** [comment]
Thanks @DavidKorczynski That looks like a separate issue with our grouping. All these testcases do end up getting grouped into the [one group](https://oss-fuzz.com/testcases?q=group%3A5421756379693056), but it happens too late after the bugs are filed.

**Comment by MarcoFalke** [comment]
An alternative to creating a new issue to re-open the existing one. See also https://github.com/google/oss-fuzz/issues/6791

**Comment by oliverchang** [comment]
> An alternative to creating a new issue to re-open the existing one. See also [google/oss-fuzz#6791](https://github.com/google/oss-fuzz/issues/6791)

Re-opening is something that doesn't fit well into our current bug triage workflow. For the unreproducible issues, we now only ever file them once.
