### ISSUE TITLE
No Fuzzers available when using local deployment

### ISSUE THREAD

**Issue by michaelbeale-IL** [google/clusterfuzz#2574]
I'm trying to follow along with the Heartbleed example but can't create a job, because I don't have any fuzzers available and I can't find any instructions on how to add them.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/63321611/156847903-ad6eed30-3012-4433-ab91-3a61e91d7d31.png">

Am I missing a step in my setup?

**Comment by securitykernel** [comment]
I have seen this randomly and as far as I can recall, restarting the server helped. You should see it adding the fuzzers in the logs at startup.

**Comment by michaelbeale-IL** [comment]
Thanks.  Any other tips on what I should look for in the logs?  I've restarted the server with no change.

**Comment by jonathanmetzman** [comment]
Did you start your server with `python butler.py run_server --bootstrap`

**Comment by michaelbeale-IL** [comment]
I did.  it appears that it took a few tries to get it to fully bootstrap for me.  Not sure what I've changed, but I've managed to get it working.  The difference is I saw the "python butler.py run setup --non-dry-run --local --config-dir=configs/test" command complete.  

But I've got it working now, and have been able to reproduce the heart bleed example.  Thanks 👍
