### ISSUE TITLE
Google OAuth2 during setup is no longer operable (redirect_uri: urn:ietf:wg:oauth:2.0:oob)

### ISSUE THREAD

**Issue by dbaker-rh** [google/clusterfuzz#2576]
When going through production setup on a new instance, I get to this step:

$ python butler.py create_config --oauth-client-secrets-path=$CLIENT_SECRETS_PATH   --firebase-api-key=$FIREBASE_API_KEY --project-id=$CLOUD_PROJECT_ID $CONFIG_DIR
...
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=5xxx.....

Visiting that site generates a 400 error: 

| Error 400: invalid_request
| You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

The error appears related to this, https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#instructions-oob which shows that from Feb 28th, 2022 and new OAuth flows related to the OOB will be blocked.

**Comment by oliverchang** [comment]
Thanks for flagging this! We'll take a look at updating the instructions here.

**Comment by oliverchang** [comment]
Sorry for the delay here. We have a simple fix out at https://github.com/google/clusterfuzz/pull/2579 to convert this to a browser based flow.

**Comment by dbaker-rh** [comment]
Thank you.  I can confirm the fix was successful and fixed my issue.
