### ISSUE TITLE
GitHub issue filing broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#2594]
See [this testcase](https://oss-fuzz.com/testcase-detail/5236985024872448)
```
Failed to file issue due to exception: 'Testcase' object has no attribute 'repo_id'
```

Also see this [stackdriver error](https://console.cloud.google.com/logs/query;query=error_group%2528%22CPKE37j21KqFAg%22%2529%0AlogName:%22app%22%0Aresource.type%3D%22gae_app%22%0Aresource.labels.version_id%3D%2220220323t152741%22%0Aresource.labels.project_id%3D%22clusterfuzz-external%22%0Aresource.labels.module_id%3D%22cron-service%22;timeRange=2022-03-29T14:14:37.923Z%2F2022-03-29T15:14:37.923Z;cursorTimestamp=2022-03-29T14:44:07.923522Z?project=clusterfuzz-external)

@Alan32Liu 's scarecrow project caught this bug.

**Comment by Alan32Liu** [comment]
Fixing with [Fix typos in attribute names](https://github.com/google/clusterfuzz/pull/2595).
