### ISSUE TITLE
Deploy failed from the newest tag v2.5.6

### ISSUE THREAD

**Issue by rafalnowicki116** [google/clusterfuzz#2628]
Hi,
I cannot deploy the CF into GCP because there is a problem with Google OAuth2. 
The problem has been solved here https://github.com/google/clusterfuzz/issues/2576.

In the official documentation, I found recommendations to use the latest tag not use master.

Are you going to release a new tag with OAuth2 changes?
Can I use master? (I know master is not stable) - what are your recommendations?

Thanks,

**Comment by oliverchang** [comment]
Thanks for the issue! We'll cut a new release soon that includes this fix.

**Comment by oliverchang** [comment]
We've released v2.5.7.
