### ISSUE TITLE
Runtime dependencies for target program

### ISSUE THREAD

**Issue by sboni1** [google/clusterfuzz#2633]
I tried to include a shared library which is needed by the binary being fuzzed in the same folder of the tar file. But i am still getting an error that particular library was not found while that binary is fuzzed by clusterfuzz. According to the documentation this should have worked. I was curious if i need to do something else as well ?

**Comment by oliverchang** [comment]
Hi @sboni1,

This usually depends on the rpath set in the binary. If the binary has shared library (.so) dependencies, the rpath usually should be set to be relative to the binary for it to be automatically discovered. 

see e.g. https://nehckl0.medium.com/creating-relocatable-linux-executables-by-setting-rpath-with-origin-45de573a2e98
