### ISSUE TITLE
Queuing/prioritization/cancelation/pausing jobs.

### ISSUE THREAD

**Issue by rafalnowicki116** [google/clusterfuzz#2646]
Hello,

Is there any mechanism for an administrator to control/monitor jobs/tasks, how many tasks are in the queue etc?? 

Without it, we cannot do any autoscaling. 

BR,
Rafał

**Comment by oliverchang** [comment]
Hi there,

The only mechanism to monitor tasks in the queue is via the Cloud Console's Pub/Sub pages and default metrics. Would those work for you?

**Comment by rafalnowicki116** [comment]
I will check it. But from what you are saying, it sounds like we cannot cancel tasks, prioritize or pause any tasks/job?? - **only monitor**??  
Am I right? The only way to permanently cancel all "fuzzing tasks" for a job is to delete the JOB?

**Comment by oliverchang** [comment]
Yes, either by deleting the job, or unassociating it with alls Fuzzers.
