### ISSUE TITLE
Is it possible to migrate one clusterfuzz to another?

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#2660]
We are looking to standup a new testing clusterfuzz in a new GCP project.  Is it possible to migrate one clusterfuzz with all the crash stats and history to another clean clusterfuzz instance?  If so what parts need to be migrated over such as BQ table data and cloud storage and datastore?

**Comment by oliverchang** [comment]
Unfortunately no, there is no easy migration functionality that I know of. 

The main things that would be migrated are:
- Datastore
- Cloud storage
- BQ

Not sure if I'm missing anything here.

**Comment by oliverchang** [comment]
(Closing as the question has been answered -- but please feel free to let me know if any follow up is needed).
