### ISSUE TITLE
Clean up references to private design documents/bugs

### ISSUE THREAD

**Issue by mhlakhani** [google/clusterfuzz#268]
Hi! There are a couple of places in the code where there are references to private links for explaining why certain design choices were made.

Would it be possible to re-host those documents or provide a summary within the code/documentation for clusterfuzz, so that external developers can contribute accordingly?

Here are the points I noticed:

https://github.com/google/clusterfuzz/blob/master/src/python/bot/fuzzers/ml/rnn/README.md references "go/ml-fuzzing"

https://github.com/google/clusterfuzz/blob/master/src/python/bot/fuzzers/strategy.py#L17 references a link which isn't publicly accessible

**Comment by inferno-chromium** [comment]
@Dor1s can analyze what needs to be made public for these and if these references are applicable/need to be removed.

**Comment by Dor1s** [comment]
Thanks, Hasnain!

https://crbug.com/682311 is now public. It still has some other non-publicly-accessible links inside, but overall comments should be interesting for anyone who's looking into corpus subset strategy (i.e. backtracking).

Here is another piece of evidence that it's useful: https://github.com/google/sanitizers/issues/964

Regarding the go/ml-fuzzing doc, I think we can make a public copy of it, but I'd need some time to remove all internal references from it + ask someone on the team to review it :)

**Comment by Dor1s** [comment]
> Regarding the go/ml-fuzzing doc, I think we can make a public copy of it, but I'd need some time to remove all internal references from it + ask someone on the team to review it :)

Apparently it's still a bit too much work for not so much value, so I'm not planning on publishing that go/ml-fuzzing doc. It's not rocket science, the model was inspired by https://github.com/martin-gorner/tensorflow-rnn-shakespeare with some improvements such as supporting an alphabet of all 256 characters, performance optimizations, and something else that I don't remember :)

**Comment by mhlakhani** [comment]
Thanks for the update/intel! this is useful clarification :)
