### ISSUE TITLE
Making corpus backup public

### ISSUE THREAD

**Issue by quanyangsc** [google/clusterfuzz#2684]
Is it intentional for `/corpus-backup/make-public` to be enabled for non-oss-fuzz/google deployment of clusterfuzz?

This came as a surprise to us because we weren't expecting clusterfuzz to make them public automatically.

**Comment by oliverchang** [comment]
It's intended to be disabled (by removing from cron.yaml) if it's not desired. 

I've uploaded https://github.com/google/clusterfuzz/pull/2686 to prevent this. Thanks!
