### ISSUE TITLE
AFL++ fuzzers not uploading corpus

### ISSUE THREAD

**Issue by TheCoryBarker** [google/clusterfuzz#2703]
From Jonathan Metzman:
Nothing is getting added to corpus because in the merge implementation ClusterFuzz thinks every testcase covers the same code

**Comment by jonathanmetzman** [comment]
I think it thinks this because showmap is broken.
I think I can reproduce this with an AFL++ build on my desktop. I'm going to confirm when I get a chance and file an issue with AFL++.

**Comment by jonathanmetzman** [comment]
Fix posted here: https://github.com/AFLplusplus/AFLplusplus/issues/1452 will add this to CF soon.
