### ISSUE TITLE
Clusterfzz should prevent creating too many new bugs at once

### ISSUE THREAD

**Issue by mi-ac** [google/clusterfuzz#2706]
Creating new bugs doesn't seem to have an upper limit and in certain situations a flood of bugs is created like [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1324097#c24).

This is a feature request to add a configuration e.g. per job type to automatically go into a panic mode when a certain number of new bugs created per day (or other configurable period) is breached.

* As a minimum it'd be great to start alerting someone e.g. per email.
* Stretch goal: Temporarily throttle the number of test cases per job, e.g. to 5%.

**Comment by Alan32Liu** [comment]
Yes, ideally we will improve on this later.

**Comment by oliverchang** [comment]
Thanks! bug throttling is certainly something that makes sense. 

@Navidem this might be something we can tackle after the variant analysis grouping.

**Comment by Navidem** [comment]
> Thanks! bug throttling is certainly something that makes sense.
> 
> @Navidem this might be something we can tackle after the variant analysis grouping.

Sure, will take a note to incorporate.

**Comment by mi-ac** [comment]
FYI, here was another little flood today: https://crbug.com/1365363

**Comment by mi-ac** [comment]
We are having two severe bug floods again: https://crbug.com/1435352 - this time Clusterfuzz created more than 1000 new issues. How difficult would it be to implement a throttle on the Clusterfuzz side?

**Comment by oliverchang** [comment]
Yes, we finally have some spare cycles here. @hogo6002 this can come next as a more interesting FR to implement!
