### ISSUE TITLE
Support for multiple projects

### ISSUE THREAD

**Issue by sfiecko** [google/clusterfuzz#2716]
Hi!

Is there a mechanism within ClusterFuzz to provide a project separation? Are we able to somehow link multiple GCP projects and then manage them via single ClusterFuzz UI?
I have seen "Projects" filter which points to our GCP project. Can we link more projects? What's the point of filtering those projects? 
![image](https://user-images.githubusercontent.com/72020202/176838361-4ba42608-9ff2-48e6-b9c9-0fe68e4f4d2d.png)

Best regards,
Sebastian

**Comment by oliverchang** [comment]
Hi there! Sorry for the delayed reply.

The "Project" filter is set simply by setting the "PROJECT_NAME" variable in the job definition. The intention is to allow different sub-teams to filter bugs that are more relevant to them.

You can also use multiple GCP projects to run GCE instances that connect to the main GCP project which provides the UI and DB.

**Comment by sfiecko** [comment]
Thanks, it works! 😄
