### ISSUE TITLE
Name conflicts detection/prevention

### ISSUE THREAD

**Issue by sfiecko** [google/clusterfuzz#2740]
Hi!

As I have seen, when creating a job with the same name ClusterFuzz will accept the new one and delete the old one with the same name (override - without any notice). Is there a name collision detection? What about other cases with zip name conflicts, fuzzer/dictionaries/corpuses name conflicts? Can ClusterFuzz handle it? Is ClusterFuzz able to handle a lot of interactions with various users (and possible conflicts) - keeping the user-friendliness and working properly? 

Best regards,
Sebastian

**Comment by Alan32Liu** [comment]
cc @oliverchang

**Comment by oliverchang** [comment]
> when creating a job with the same name ClusterFuzz will accept the new one and delete the old one with the same name
That was an intentional choice. 

This behaviour should be limited to Fuzzer/Jobs only. Zip names/dictionaries/corpora should not matter.
