### ISSUE TITLE
afl-fuzz: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by sfiecko** [google/clusterfuzz#2748]
Hi!

We are not able to fuzz with afl due to the following error:
`/mnt/scratch0/clusterfuzz/bot/builds/afl_asan_linux_fuzzme_withseed/custom/afl-fuzz: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`

VMs are based on this images:
https://console.cloud.google.com/gcr/images/clusterfuzz-images/global/base@sha256:0ea24b16a137ffba0ae4f0a4dea5204b69790c435714602a08227d8e5df83950/details
![image](https://user-images.githubusercontent.com/72020202/182370163-cf044187-659e-4583-84c2-a0b027b14747.png)

How can we update Python within ClusterFuzz bots? Should we modify Dockerfile? Is it [this](https://github.com/google/clusterfuzz/blob/master/docker/base/Dockerfile) Dockerfile?

Thank you in advance!
Sebastian

**Comment by oliverchang** [comment]
Indeed, you can build your own image with your own version of Python. https://github.com/google/clusterfuzz/blob/master/docker/base/Dockerfile is the correct Dockerfile.

**Comment by sfiecko** [comment]
Thanks! 😄

**Comment by sfiecko** [comment]
@oliverchang - I would like to reopen this, as I have one more question regarding this topic.

We have tried to update Python, but it is a set of linked libraries - then newer `glibc` is required, and with that we have to update it to the newest ubuntu 22 (which is sadly problematic currently, due to the compatibility issues with `google-fluentd` (information [here](https://cloud.google.com/logging/docs/agent/logging) as it is not supported yet by Ubuntu22).

What is your approach on fuzzing targets that are built with newer set of tools? Do you provide them with the package (inside the zip) with the modification of environment variable `LIBPATH` to override the local execution environment with the one provided from the zip file? What will be the correct way to solve this (as we are unable to use older versions for example).

Best regards,
Sebastian
