### ISSUE TITLE
Add support for parsing arbitrary file open

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#2750]
Implemented in https://github.com/google/oss-fuzz/pull/8009

**Comment by catenacyber** [comment]
So, waiting for this to see bugs pop ?

**Comment by oliverchang** [comment]
@Alan32Liu mind doing this when you get the chance?

**Comment by Alan32Liu** [comment]
Happy to!
I will work on it this afternoon.

**Comment by catenacyber** [comment]
@Alan32Liu should have bugs popped by now ? I did not spot any in my projects

**Comment by Alan32Liu** [comment]
> @Alan32Liu should have bugs popped by now? I did not spot any in my projects

Yep, I just checked and can see there are many.
But we might need to look deeper into them to filter out false positives.
I will try to get back to you later this week if we find anything interesting : )

**Comment by catenacyber** [comment]
Ok, I see none with my creds on https://bugs.chromium.org/p/oss-fuzz/issues/list?q=Arbitrary%20file%20open&can=2
Let me know what is next
