### ISSUE TITLE
About group-based corpus scheduling strategy for parallel fuzzing

### ISSUE THREAD

**Issue by gtt1995** [google/clusterfuzz#2761]
Hello @oliverchang  @jonathanmetzman 
     Sorry to bother you again, but I would like to ask if that corpus scheduling strategy is helpful to you (clusterfuzz), and I can be responsible for contributing the code after your brief evaluation.
      Thank you for your time!
       Best wishes.

**Comment by gtt1995** [comment]
In our local practice, we build ClusterFuzz locally and use glibFuzzer by enabling fork_strategy_probability=1.0  in  strategy.py   of ClusterFuzz source code, this allows one of the libFuzzer engines to generate more competitive seeds, such as generating new test cases at 50% of the previous size.

**Comment by gtt1995** [comment]
So in my opinion, there are two ways to apply this promising corpus scheduling strategy: 1. Use the built-in libFuzzer, add the command parameter -fork_corpus_groups=1, and modify the fork_strategy_ in the clusterfuzz's strategy.py source code to probability=1.0 (or as high a probability as possible) to apply our strategy with the above two parameters.
2. The second way is to set a new corpus assignment strategy in GCS, instead of directly assigning all the seeds in the bucket to different bots, we select some high quality seeds in these buckets and assign them to different libFuzzer engines, AFL++ engines, honggfuzz engines, etc. every 4500 seconds. I will contribute my code if the second way looks feasible.

**Comment by gtt1995** [comment]
@inferno-chromium @Dor1s  Thanks for your time. Thank you.

**Comment by gtt1995** [comment]
@inferno-chromium 
Hello, 
Please help me with this issue

**Comment by oliverchang** [comment]
Hi. You have sent us at least 5 emails and 6 issue comments about this in 4 days. Please have some patience here. Unfortunately we don't have the spare cycles at the moment to help with this. 

If you would like to evaluate your strategy, consider running a local fuzzbench experiment per https://google.github.io/fuzzbench/running-a-local-experiment

**Comment by gtt1995** [comment]
Hello, zhang,
&nbsp; &nbsp; &nbsp; &nbsp; First of all, I apologize for my impatience. And thank you very much for your reply, it was very helpful to me.
&nbsp; &nbsp; &nbsp; &nbsp; I will follow your tips for the next step, thank you.
&nbsp; &nbsp; &nbsp; &nbsp; Best wishes, thank you.





------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "google/clusterfuzz"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Aug 16, 2022 10:49 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [google/clusterfuzz] About group-based corpus scheduling strategy for parallel fuzzing (Issue #2761)





 
Hi. You have sent us at least 5 emails and 6 issue comments about this in 4 days. Please have some patience here. Unfortunately we don't have the spare cycles at the moment to help with this.
 
If you would like to evaluate your strategy, consider running a local fuzzbench experiment per https://google.github.io/fuzzbench/running-a-local-experiment
