### ISSUE TITLE
Support for syzkaller for generic linux-based kernels

### ISSUE THREAD

**Issue by sfiecko** [google/clusterfuzz#2766]
Hi!

Is there any support for fuzzing generic linux kernels that are not Android? What could be the effort to modify the ClusterFuzz to extend its fuzzing skills to standard linux VMs? When looking at the file [here](https://github.com/google/clusterfuzz/blob/e165ec32b4ee49f7ad55fbc212bc840c07ea2831/src/clusterfuzz/_internal/system/environment.py) We discovered a comment that says “ TODO add support for desktop architectures as needed” and when you look at the [runner object](https://github.com/google/clusterfuzz/blob/e165ec32b4ee49f7ad55fbc212bc840c07ea2831/src/clusterfuzz/_internal/bot/fuzzers/syzkaller/runner.py) for syzkaller it’s specifically android not generically Linux. We do of course realize that Android is derived from Linux but this seems to either expect or require some android specific elements that one wouldn’t encounter with a desktop or server linux kernel.

Thanks in advance for your support,
Sebastian

**Comment by oliverchang** [comment]
Unfortunately the syzkaller support is not generic, and currently only works for Android.
