### ISSUE TITLE
Running in production not on GCP

### ISSUE THREAD

**Issue by markszabo** [google/clusterfuzz#2773]
All the documentation and scripts seem to only talk about either running ClusterFuzz [locally](https://google.github.io/clusterfuzz/getting-started/local-instance/) or [on GCP](https://google.github.io/clusterfuzz/production-setup/clusterfuzz/) (with the exception of [running bots on non-GCP machines](https://google.github.io/clusterfuzz/production-setup/clusterfuzz/#other-cloud-providers)). Is there any documentation on running ClusterFuzz on any other platform, e.g. on kubernetes?

One [could](https://github.com/lookfwd/getting-started-clusterfuzz-local-in-aws) run the local script on any VM, however that seem to be missing features, and also unsure how performant/suitable it is for production use.

**Comment by oliverchang** [comment]
Hi! Unfortunately there's a pretty tight dependency on GCP for ClusterFuzz, and this would take a fair bit of engineering cycles to change.

**Comment by markszabo** [comment]
Understood, thank you for the answer.
