### ISSUE TITLE
Can't log in to oss-fuzz.com with Safari/macOS

### ISSUE THREAD

**Issue by nwellnhof** [google/clusterfuzz#2818]
When trying to log in to oss-fuzz.com with my Google account using Safari on macOS, I'm only seeing a box with a loading animation and nothing happens.

Safari Version 16.0 (17614.1.25.9.10, 17614)
macOS Monterey 12.6

**Comment by oliverchang** [comment]
@Alan32Liu or @Navidem can one of you help with this some time soon? 

Per https://github.com/google/clusterfuzz/issues/2818#issuecomment-1266550824 this is likely related to a missing CSP rule which we set up here: https://github.com/google/clusterfuzz/blob/1be95bd84e0868495a2b3c835b18577b2ae3e0e2/src/appengine/libs/csp.py

I don't have a macOS machine to debug this sadly.

**Comment by oliverchang** [comment]
@Navidem can you please help with this? I'm not sure why this is only an issue on Safari.

**Comment by Navidem** [comment]
> @Navidem can you please help with this? I'm not sure why this is only an issue on Safari.

Sure, I will.

**Comment by Navidem** [comment]
I can confirm adding `builder.add('img-src', 'data:')` makes the CSP error disappear, but login issue persists.

**Comment by oliverchang** [comment]
@Navidem can you check if the workaround in https://github.com/firebase/firebaseui-web/issues/977#issuecomment-1291567278 works?

**Comment by Navidem** [comment]
> firebase/firebaseui-web#977 (comment)

The solution did not help: at the time of login, a popup appears to select account but the console log show following error and UI returns back to the login page:

```
[Error] Unhandled Promise Rejection: TypeError: Right side of assignment cannot be destructured
	(anonymous function) (firebase-auth-compat.js:1:86987)
	asyncFunctionResume
	sendToConsumer (firebase-auth-compat.js:1:92175)
	(anonymous function) (firebase-auth-compat.js:1:91705)
	forEach
	onEvent (firebase-auth-compat.js:1:91645)
	(anonymous function) (firebase-auth-compat.js:1:98111)
	mm (cb=gapi.loaded_0:269:97)
	(anonymous function) (cb=gapi.loaded_0:269:268)
	Ek (cb=gapi.loaded_0:246:313)
	Nk (cb=gapi.loaded_0:246:475)
	hk (cb=gapi.loaded_0:247)
	(anonymous function) (cb=gapi.loaded_0:240:374)
	(anonymous function)
```

**Comment by jonathanmetzman** [comment]
CC @byron

**Comment by jonathanmetzman** [comment]
I suspect we won't fix this soon. Maybe we should put a banner up asking people to use chrome or firefox?

**Comment by oliverchang** [comment]
Hmm, looking at https://firebase.google.com/docs/auth/web/redirect-best-practices, this might actually be easier to solve than expected if we just use https://firebase.google.com/docs/auth/web/redirect-best-practices#update-authdomain

**Comment by oliverchang** [comment]
Oh actually, we don't fit "If you host your app with Firebase Hosting on a custom domain or a subdomain of web.app, use [Option 1](https://firebase.google.com/docs/auth/web/redirect-best-practices#update-authdomain).". 

We'll need to go with Options 2, 3, 4, 5 instead. The best ones for us looks like 2 or 3.

**Comment by hogo6002** [comment]
Fixed. It's able to log in to oss-fuzz.com with Safari/macOS now.
