### ISSUE TITLE
Keep ClusterFuzz up-to-date on PyPI

### ISSUE THREAD

**Issue by Alan32Liu** [google/clusterfuzz#2823]
The latest version of [ClusterFuzz on PyPI](https://pypi.org/project/clusterfuzz/) is still 2.5.6, despite that we have released [2.5.7](https://github.com/google/clusterfuzz/releases/tag/v2.5.7) in May.
Shall we keep ClusterFuzz up-to-date on PyPI?

FuzzBench is affected by this issue, as it has ClusterFuzz as a dependency, and cannot update some other dependencies because old ClusterFuzz requires old versions of them.

**Comment by Alan32Liu** [comment]
The impact on FuzzBench is not huge, so this is not urgent at all : )

**Comment by oliverchang** [comment]
ClusterFuzz is up to date on PyPI now :)
