### ISSUE TITLE
How to Use Web Pages

### ISSUE THREAD

**Issue by gongpx** [google/clusterfuzz#283]
I've installed it here and successfully started the web page, but I haven't found a window to upload it. I'm visiting port 9002. The page directory is as follows:
Instances
Datastore Viewer
Datastore Indexes
Datastore stats
Interactive Console
Memcache Viewer
Blobstore Viewer
Task Queues
Cron Jobs
XMPP
Inbound Mall
Full Text Search
After clicking on the directory: Interactive Console. I would like to ask if the interactive console is currently disabled. To enable the console,invoke dev_appserver.py with the --enable_console argumen.Di can give some instructions on how to use the web page. Thank you.

**Comment by inferno-chromium** [comment]
You are on the wrong console, 9002 is admin console. You need to use 9000 port.
