### ISSUE TITLE
Support Google Groups for Auth

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#2831]
The protobuf team complained that having to add people to auto_ccs is too burdensome. A lot of others have asked for it and I'm of the opinion that because it would help our users a lot, we should do this unless there's some sort of technical limitation preventing it.

**Comment by jonathanmetzman** [comment]
@oliverchang wdyt?

**Comment by devjgm** [comment]
💯  subscribing to this issue

**Comment by jonathanmetzman** [comment]
There is a technical issue. Last we checked, there's no API we can use in an open source project that can test for membership in a google group

**Comment by jonathanmetzman** [comment]
I think this is WontFix unfortunately
