### ISSUE TITLE
libFuzzer stats on oss-fuzz not appearing after October 20th

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#2832]
https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2022-10-12&date_end=2022-10-25&fuzzer=libFuzzer&job=libfuzzer_asan_skia&project=skia

**Comment by oliverchang** [comment]
Fuzzers are running, but it looks like the BQ import failed.

**Comment by oliverchang** [comment]
This is the error we're getting:

```
"status": {
    "errorResult": {
      "reason": "resourcesExceeded",
      "debugInfo": "redacted"
    },
    "errors": [
      {
        "reason": "resourcesExceeded",
        "message": "Resources exceeded during query execution: The query could not be executed in the allotted memory. Peak usage: 101% of limit.\nTop memory consumer(s):\n  table/storage metadata: 100%\n"
      }
    ],
    "state": "DONE"
  },
```

**Comment by oliverchang** [comment]
We may need to create separate jobs here: https://github.com/google/clusterfuzz/blob/57073e10e76726c1e8a57ef75d3dadd80cf3d85e/src/appengine/handlers/cron/load_bigquery_stats.py#L148 

And partition manually by file prefix.

**Comment by oliverchang** [comment]
Tentative fix out: https://github.com/google/clusterfuzz/pull/2834.

**Comment by jonathanmetzman** [comment]
Thanks!
CC @kjlubick

**Comment by oliverchang** [comment]
Still seeing some weirdness with the new stats (some days have very low numbers), so re-opening to investigate.

**Comment by oliverchang** [comment]
On closer inspection this was due to an OOM. This along some other minor issues are mitigated in https://github.com/google/clusterfuzz/pull/2837
