### ISSUE TITLE
Several bots in one GCE instance

### ISSUE THREAD

**Issue by fxkjd** [google/clusterfuzz#2846]
Hello

while configuring the bots' cluster (in $CONFIG_DIR/gce/clusters.yaml) is it possible to setup a GCE VM with several bots (let's say I have a multiple-core VM and I want to take advantage of all resources)? Or is it only possible to deploy one bot per VM?

Thanks!

**Comment by Alan32Liu** [comment]
Not sure if this possible, @oliverchang to confirm.
