### ISSUE TITLE
Setting up a production, an error occurred when verifying appspot_domain

### ISSUE THREAD

**Issue by kylelin529** [google/clusterfuzz#2862]
When i trying to Setting up a production project using ClusterFuzz, i follow the steps in the document.
And error occur when i run 
python butler.py create_config --oauth-client-secrets-path=$CLIENT_SECRETS_PATH \
  --firebase-api-key=$FIREBASE_API_KEY --project-id=$CLOUD_PROJECT_ID $CONFIG_DIR

Following is part of error message:

Production deployment finished.
Source updated to 20221123081651-utc-25ba7217-kylelin529

Traceback (most recent call last):
  File "butler.py", line 319, in <module>
    main()
  File "butler.py", line 305, in main
    command.execute(args)
  File "/mnt/c/Users/USER/Desktop/work/LAB/clusterfuzz-new/clusterfuzz/src/local/butler/create_config.py", line 292, in execute
    verifier.verify(appspot_domain)
  File "/mnt/c/Users/USER/Desktop/work/LAB/clusterfuzz-new/clusterfuzz/src/local/butler/create_config.py", line 95, in verify
    self.api.webResource().insert(
  File "/mnt/c/Users/USER/Desktop/work/LAB/clusterfuzz-new/clusterfuzz/src/third_party/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/mnt/c/Users/USER/Desktop/work/LAB/clusterfuzz-new/clusterfuzz/src/third_party/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/siteVerification/v1/webResource?verificationMethod=FILE&alt=json returned "The necessary verification token could not be found on your site.">

And the response in https://www.googleapis.com/siteVerification/v1/webResource?verificationMethod=FILE&alt=json is: 

{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Login Required.",
        "domain": "global",
        "reason": "required",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "method": "security.irdb.api.VerificationService.List",
          "service": "siteverification.googleapis.com"
        }
      }
    ]
  }
}

**Comment by oliverchang** [comment]
Hi, I am not able to reproduce this. Did you follow the steps [here](https://google.github.io/clusterfuzz/production-setup/clusterfuzz/#create-oauth-credentials) to create your oauth secrets?
