### ISSUE TITLE
Running clusterfuzz locally without Internet

### ISSUE THREAD

**Issue by xychong** [google/clusterfuzz#2865]
Hi, I am keen to run a local instance of ClusterFuzz without internet. I have managed to start a local server by running "python butler.py run_server". I am also able to navigate to the web interface through http://localhost:9000/. 
However, this doesn't work once I disable internet access. How should I go about running the local server without internet?

**Comment by oliverchang** [comment]
Hi!

Unfortunately this (local development without internet access) is not a supported workflow for local users. We are open to PRs though!

**Comment by xychong** [comment]
May I check what's the purpose of having Internet? Is it solely for installation of dependencies?
