### ISSUE TITLE
ModuleNotFoundError: No module named 'google.cloud.datastore_v1.services'

### ISSUE THREAD

**Issue by isaacbrodsky** [google/clusterfuzz#2882]
Our cifuzz / clusterfuzz run has stopped working in uber/h3#734, and it looks like an upstream failure: https://github.com/uber/h3/actions/runs/3633774270/jobs/6131508900 The PR this started failing on should not have made any changes to how Clusterfuzz runs.

**Comment by oliverchang** [comment]
Thanks! This is tracked in https://github.com/google/oss-fuzz/issues/9151. We have a mitigation in place, so it should be working now, and we also have a fix out for the underlying issue. 

Closing in favour of the OSS-Fuzz issue.
