### ISSUE TITLE
Links to "latest" oss-fuzz coverage reports still pointing to Feb 13th

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#2971]
for example https://oss-fuzz.com/coverage-report/job/libfuzzer_asan_skia/latest points to https://storage.googleapis.com/oss-fuzz-coverage/skia/reports/20230213/linux/report.html even though https://storage.googleapis.com/oss-fuzz-coverage/skia/reports/20230313/linux/report.html exists.

**Comment by jonathanmetzman** [comment]
@DavidKorczynski @AdamKorcz The python coverage reports are causing this because they don't follow the same format as the C++ ones (see https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/fuzzer_coverage.py#L74). Could you change it to match?

**Comment by DavidKorczynski** [comment]
@jonathanmetzman yeah, I will do this early next week as I was OOO end of this week.

**Comment by jonathanmetzman** [comment]
no problem! Thanks!

**Comment by jonathanmetzman** [comment]
We're getting (very few) exceptions about malformed cov for lxml, numpy, pydantic, and cryptography. I'm not super concerned about a few projects, but maybe if you have time, you can see why your solution isn't perfect?

**Comment by DavidKorczynski** [comment]
Will do -- IIRC these projects have in common that they involve native code within the project. This may be related to https://github.com/google/oss-fuzz/issues/10084

**Comment by jonathanmetzman** [comment]
No worries, that sounds like the correct explanation to me.
