### ISSUE TITLE
Specify the version of `pipenv`

### ISSUE THREAD

**Issue by Alan32Liu** [google/clusterfuzz#2981]
@hogo6002 and I found that `install_deps` may fail due to outdated `pipenv`.
This is because some version of `pipenv` (e.g., 2022.1.XX) does not have the command `requirements` and will fail when [converting `Pipfile` to `requirements.txt`](https://github.com/google/clusterfuzz/blob/3334748ec42e93ae307b81b8739edd44013be894/src/local/butler/common.py#L242).
Shall we [specify the version of `pipenv` in `install_deps`](https://github.com/google/clusterfuzz/blob/master/local/install_deps_linux.bash#L156)?
For example, `version 2022.10.11` works.

**Comment by oliverchang** [comment]
Thanks, that indeed sounds like a good idea! Can you (or @hogo6002 ) please create a PR?

This may also resolve #2952.
