### ISSUE TITLE
Re-run crash inputs with different sanitizers for better deduplication and more detailed reports

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#311]
For a further discussion. Reported by @davidben over email.

**Comment by Dor1s** [comment]
IMO it'd be nice to have, and the re-running part shouldn't be hard to implement, but the crash processing and de-duplication logic might get pretty complicated.

**Comment by alex** [comment]
Similar to my own request over in OSS-Fuzz: https://github.com/google/oss-fuzz/issues/1220 So big 👍  from me.

**Comment by inferno-chromium** [comment]
tracked in https://github.com/google/clusterfuzz/issues/565
