### ISSUE TITLE
File bug for any flake percentage (or custom flake percentag).

### ISSUE THREAD

**Issue by smore-lore** [google/clusterfuzz#3149]
Maybe here:
https://github.com/google/clusterfuzz/blob/4801d348930b11f7e2c0e0d50c2a8a3b30fabf49/src/clusterfuzz/_internal/datastore/data_types.py#L58

I'd like clusterfuzz to automatically file issues, even those that are not reproducible. For certain fuzzers, non-deterministic issues may block finding other issues, or in large legacy codebases, deterministic issues may not always be an option. In other cases, non-deterministic issues may indicate fuzzing issues that can be fixed to introduce determinism.

**Comment by jonathanmetzman** [comment]
@oliverchang What do think? I think this is only refrenced in one place?

**Comment by oliverchang** [comment]
There's a fair bit of plumbing complexity here to support this, and we have not seen this request from anyone else before.  

The easy alternative to this is to just keep an eye on the ClusterFuzz dashboard for all unreproducible testcases.
