### ISSUE TITLE
Upgrade Python

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3218]
Python 3.7 was deprecated June 27

**Comment by jonathanmetzman** [comment]
CC @ochang

**Comment by jonathanmetzman** [comment]
CC @oliverchang

**Comment by oliverchang** [comment]
Yeah, we're gonna have to bite the bullet soon here

**Comment by jonathanmetzman** [comment]
Done.

**Comment by jonathanmetzman** [comment]
We reverted this and fixed Python3.7 on Mac and Android.
But it looks like support for Python3.7 is going to be dropped by AppEngine on January 30th 2024.
We may get away with upgrading the appengine version before the rest of the codebase.
