### ISSUE TITLE
Smaller inputs don't get subsituted for engine fuzzers (libFuzzer, AFL)

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#322]
@kcc discovered this, we just verified this in our code - https://github.com/google/clusterfuzz/blob/master/src/python/bot/fuzzers/libFuzzer/launcher.py#L925

Basically since we add corpus directory in front, -merge=1 won't add the smaller inputs to existing corpus. This is bad, hampers fuzzer efficiency since we could have a much smaller corpus.

**Comment by jonathanmetzman** [comment]
I think we make this same mistake in AFL's merging by the way.

**Comment by inferno-chromium** [comment]
This is done by @jonathanmetzman in https://github.com/google/clusterfuzz/commit/0b73741e3a1c6b1b3a0f5714f1275232510232b3 and https://github.com/google/clusterfuzz/commit/1b51e2a9e1c96894bd745bd698aeb5619db9a37b
