### ISSUE TITLE
fix prerequisites documentation

### ISSUE THREAD

**Issue by MjMoshiri** [google/clusterfuzz#3289]
According to the [documentation](https://google.github.io/clusterfuzz/getting-started/prerequisites/) supported version of Ubuntu are 
Ubuntu (14.04, 16.04, 17.10, 18.04, 18.10) However the [dependacy installer](https://github.com/google/clusterfuzz/blob/c2de16f9c9ae209a56156f69431e0bc48e608969/local/install_deps_linux.bash#L55) supports till Focal.

also there are no explanation about supported architectures in the documentation although It's a [check](https://github.com/google/clusterfuzz/blob/c2de16f9c9ae209a56156f69431e0bc48e608969/local/install_deps_linux.bash#L69) in the deps_installer

**Comment by cdxvy30** [comment]
Agree. The version should includes Focal and supported architectures should be `x86_64`.

**Comment by pinaki-08** [comment]
Hi, can I please contribute to this issue ?
