### ISSUE TITLE
butler create_config keep asking for "Please visit this URL to authorize this application: " despite using gcloud auth

### ISSUE THREAD

**Issue by dummys** [google/clusterfuzz#3329]
When I want to create a new instance of clusterfuzz, it keep asking to connect to the url. The problem is that I'm seting this up on a headless computer hosted already on gcloud, and when I type the url on another browser, I get an accepting page for permissions, which I do but then it get redirected to localhost:

The exact url (removed the token) is: `Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=myclientid.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification&state=ASTATE&access_type=offline`

Is the redirect_uri correct ? I don't understand why it want to connect to localhost to be honest...

**Comment by jonathanmetzman** [comment]
I think it is correct,I think this is how it communicates with your local copy of the SDK (i.e. it listens on a port, waits for you to auth by going to google.com, which then gives the credentials to the app via your local port.
