### ISSUE TITLE
Documentation: Requirements is unclear and lead to misconfguration

### ISSUE THREAD

**Issue by dummys** [google/clusterfuzz#3330]
Hello,

in the requirements page: `https://google.github.io/clusterfuzz/getting-started/prerequisites/`
I think you should remove the line:
```
Google Cloud SDK
Install the Google Cloud SDK by following the [online instructions](https://cloud.google.com/sdk/).
```

As if you follow the online documentation to install it, it asked to use a signed deb repo which will produce an conflict error later when you run the `local/install_deps.sh` script, which will also install the gcloud client using a NON-signed deb repo.
Why not put `Run the local/install_deps.sh` script at the beginning of the requirements and removing the google SDK installation`

**Comment by leonasdev** [comment]
> Hello,
> 
> in the requirements page: `https://google.github.io/clusterfuzz/getting-started/prerequisites/` I think you should remove the line:
> 
> ```
> Google Cloud SDK
> Install the Google Cloud SDK by following the [online instructions](https://cloud.google.com/sdk/).
> ```
> 
> As if you follow the online documentation to install it, it asked to use a signed deb repo which will produce an conflict error later when you run the `local/install_deps.sh` script, which will also install the gcloud client using a NON-signed deb repo. Why not put `Run the local/install_deps.sh` script at the beginning of the requirements and removing the google SDK installation`

I think this prerequisite should be exists for macOS since `install_deps_macos.bash` does not install google cloud sdk like `install_deps_linux.bash`.

But the document should write it as a prerequisite specific with macOS.
