### ISSUE TITLE
Rediscovered bug don't appear in CF board

### ISSUE THREAD

**Issue by 0x0abd** [google/clusterfuzz#3393]
Hi,
If, for some reason, CF rediscovered previously fixed bug on the newest build, it will not be appeared in **Testcases**.
Steps(local instance): 
1. create **job1** for **build1** with bug
2. wait while CF find this bug - **bug1** which will be appeared in **Testcase**
3. update **job1** for **build2** with fix
4. wait while CF mark this **bug1** as fixed
5. update **job1** for **build3** with same bug
6. **bug1** will never shown in **Testcases** as non-fixed. It's appeared only as fixed.

PS
If you manually assign testcase for **job1** in **Upload Testcase** the **bug2** will be found but not will be appeared in **Testcases**. Moreover this bug will be **duplicate** of **bug3**(which was found after step5 and stored silently hidden somewhere in CF db, I suppose. Which is also not appeared in **Testcase**).

PPS
If you manually try **Redo Task** for **bug1**(which is fixed with **build2**), then this bug will be appeared in **Testcase**. But info such as Fuzz Target, Stack Trace etc stored in report - info from fixed version(Step3-4).
MOREOVER, **bug1** after a few minutes will be marked as fixed, since it's associated with **build2**(while **Redo Task** was applied for latest **build3**). You could never seen rediscovered bugs even with **Redo Task** help.

May be this is not a correct way - update jobs with newest builds and waiting the results?
It works as expected?
This evidence affects only local CF instance?
Or this is a bug in design?
Thanks.

**Comment by oliverchang** [comment]
Hi,

We have some controls to avoid filing similar looking bugs too soon after the bug is marked as fixed (https://github.com/google/clusterfuzz/blob/c682de25d58a1a8dcf286c6b45a06478c7396bdb/src/clusterfuzz/_internal/datastore/data_types.py#L76).  This is to deal with potential race conditions and churn.

**Comment by 0x0abd** [comment]
Got it! Thanks, Oliver
