### ISSUE TITLE
Fluentd install in docker image is broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3411]
Workaround is to use the cache to avoid this.

**Comment by oliverchang** [comment]
We can likely get rid of fluentd completely if we just use something like this: https://github.com/google/osv.dev/blob/8ea0d1546965eafbbf4110da28e40800c7fd0bcf/osv/logs.py#L24

**Comment by jonathanmetzman** [comment]
Nice. Could you say more? Why do we have fluentd and how does this eliminate it? Do we expect this to work with our ancient logging version?

**Comment by oliverchang** [comment]
> Nice. Could you say more? Why do we have fluentd and how does this eliminate it? Do we expect this to work with our ancient logging version?

This is just to pipe our logs to Google Cloud. I'd expect us to be able to completely remove it if we just use the newer cloud logging client  libraries instead.

**Comment by oliverchang** [comment]
I have a change out to replace fluentd completely: https://github.com/google/clusterfuzz/pull/3422

However, this requires our google-cloud-logging library to be upgraded to 3.x, which also requires other google cloud logging libraries to be upgraded. 

@jonathanmetzman I think you have a patch coming soon to upgrade all of our cloud libraries right? I'll wait for that before taking that PR any further.
