### ISSUE TITLE
No stats since September

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3429]
@oliverchang could you please take a look?

**Comment by oliverchang** [comment]
Which instance?

**Comment by oliverchang** [comment]
I think this is the Chrome instance, where the load is still timing out. Should hopefully be fixed by https://github.com/google/clusterfuzz/pull/3430

**Comment by jonathanmetzman** [comment]
I think sundew complained as well

**Comment by oliverchang** [comment]
This looks to be fixed now.
