### ISSUE TITLE
Question about Running Bots on Self-Hosted Kubernetes Cluster: Preemptible vs. Non-Preemptible?

### ISSUE THREAD

**Issue by leonasdev** [google/clusterfuzz#3431]
Hello, I've been trying to run the bot on my self-hosted Kubernetes cluster recently. 

In the documentation, it recommended running the scalable bot (only do fuzzing task) on GCE **preemptible** machines since they are more cost-effective. 

If I want to run the bot on our own Kubernetes cluster, do I still need to allocate both preemptible and non-preemptible bots? Can I configure all the bots as non-preemptible (allowing all tasks)? I'm assuming that services like pub/sub will optimize task distribution and not incur any overhead?

Additionally, I would like to inquire if you recommend keeping the bot's configuration the same as 1 core and 4GB, following the original GCE configuration (since the bot seems only support single thread?). Thank you.

**Comment by jonathanmetzman** [comment]
>If I want to run the bot on our own Kubernetes cluster, do I still need to allocate both preemptible and non-preemptible bots? Can I configure all the bots as non-preemptible (allowing all tasks)? I'm assuming that services like pub/sub will optimize task distribution and not incur any overhead?

I think certain tasks aren't fault tolerant and can't be done on preemptible machines or configured to do so.

>Additionally, I would like to inquire if you recommend keeping the bot's configuration the same as 1 core and 4GB, following the original GCE configuration (since the bot seems only support single thread?). Thank you.

I think this is still the recommendation.

Thanks!

**Comment by leonasdev** [comment]
> > If I want to run the bot on our own Kubernetes cluster, do I still need to allocate both preemptible and non-preemptible bots? Can I configure all the bots as non-preemptible (allowing all tasks)? I'm assuming that services like pub/sub will optimize task distribution and not incur any overhead?
> 
> I think certain tasks aren't fault tolerant and can't be done on preemptible machines or configured to do so.
> 
> > Additionally, I would like to inquire if you recommend keeping the bot's configuration the same as 1 core and 4GB, following the original GCE configuration (since the bot seems only support single thread?). Thank you.
> 
> I think this is still the recommendation.
> 
> Thanks!


Thank you for your response! @jonathanmetzman 

I'm curious if configuring all bots to "allow all tasks" would negatively impact the fuzzing performance. Is there a particular ratio of preemptible to non-preemptible machines that would optimize efficiency for this task?
