### ISSUE TITLE
In testcase viewer page,I can't see auto generate cases,why?

### ISSUE THREAD

**Issue by jokie2015** [google/clusterfuzz#345]
Hi,I create a job in local development and I see It's Generated 4/4 testcases in fuzzers page,but I can't see anything in viewer page (eg: http://{host}/viewer?key=0c910608-18a2-426c-8be6-398721ec38e1),and not error in logs. why?

**Comment by inferno-chromium** [comment]
Testcase viewer page only shows crashes / real bugs. What you see on fuzzers page is an overview and sample on how many testcases that your fuzzer generated as input, which are later run against your app to see if any crashes happen. Only testcases that cause your app to crash are considered important and tracked on the testcase viewer page.
