### ISSUE TITLE
clusterfuzz-1.1.0,when I pip install protobuf-3.6.1,it notified me which is incompatible

### ISSUE THREAD

**Issue by cumtluhuaxing** [google/clusterfuzz#354]
Collecting protobuf==3.6.1
  Downloading https://files.pythonhosted.org/packages/b8/c2/b7f587c0aaf8bf2201405e8162323037fe8d17aa21d3c7dda811b8d01469/protobuf-3.6.1-cp27-cp27mu-manylinux1_x86_64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 17kB/s 
Requirement already satisfied: six>=1.9 in ./ENV/lib/python2.7/site-packages (from protobuf==3.6.1) (1.11.0)
**Requirement already satisfied: setuptools in ./ENV/lib/python2.7/site-packages (from protobuf==3.6.1) (40.8.0)
proto-google-cloud-datastore-v1 0.90.4 has requirement oauth2client<4.0dev,>=2.0.0, but you'll have oauth2client 4.1.3 which is incompatible.
tensorboard 1.8.0 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.
google-cloud-datastore 1.7.0 has requirement google-cloud-core<0.29dev,>=0.28.0, but you'll have google-cloud-core 0.29.1 which is incompatible.**
Installing collected packages: protobuf
  Found existing installation: protobuf 3.7.1
    Uninstalling protobuf-3.7.1:
      Successfully uninstalled protobuf-3.7.1
Successfully installed protobuf-3.6.1
(ENV) root@lhx:/home/lhx/clusterfuzz-1.1.0#

**Comment by inferno-chromium** [comment]
It is more of a warning and currently does not result in any breakages.
