### ISSUE TITLE
when I exec python butler.py run_server --bootstrap, it returns Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cumtluhuaxing** [google/clusterfuzz#355]
(ENV) root@lhx:/home/lhx/clusterfuzz-1.1.0# python butler.py run_server --bootstrap
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Running: pkill -KILL -f "dev_appserver.py"
| Return code is non-zero (-9).
Running: pkill -KILL -f "CloudDatastore.jar"
| Return code is non-zero (-9).
Running: pkill -KILL -f "pubsub-emulator"
| Return code is non-zero (-9).
Running: pip install -r src/requirements.txt --upgrade --target src/third_party
| DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
| Collecting backports.lzma==0.0.13 (from -r src/requirements.txt (line 1))
| Collecting google-api-python-client==1.7.4 (from -r src/requirements.txt (line 2))
| Collecting google-auth-oauthlib==0.2.0 (from -r src/requirements.txt (line 3))
|   Using cached https://files.pythonhosted.org/packages/46/df/d1f94ee2cffe5a83721f262efe51f3b2dcdd3b616caf007b8490e824c550/google_auth_oauthlib-0.2.0-py2.py3-none-any.whl
| Collecting google-cloud-datastore==1.7.0 (from -r src/requirements.txt (line 4))
|   Using cached https://files.pythonhosted.org/packages/d8/4b/aab0f1578eff1146e019670e079f5f939e46c5b004b65063b450c8d87af0/google_cloud_datastore-1.7.0-py2.py3-none-any.whl
| Collecting google-cloud-monitoring==0.30.1 (from -r src/requirements.txt (line 5))
|   Using cached https://files.pythonhosted.org/packages/1f/d3/9d8133efb90453a6a0747141aa78c64fa29618ecc713bea6e7b1bb9ff49d/google_cloud_monitoring-0.30.1-py2.py3-none-any.whl
| Collecting google-cloud-profiler==1.0.3 (from -r src/requirements.txt (line 6))
| Collecting google-cloud-storage==1.13.2 (from -r src/requirements.txt (line 7))
|   Using cached https://files.pythonhosted.org/packages/92/da/115f23ba9aa56f4d5de3f02306a36eb6d0884561e0059987865cb0cce42e/google_cloud_storage-1.13.2-py2.py3-none-any.whl
| Collecting grpcio==1.15.0 (from -r src/requirements.txt (line 8))
|   Using cached https://files.pythonhosted.org/packages/3d/15/b34114198a2bc9c9bb73b21e2b559468a1a68bb28b373d21da6e51d6204f/grpcio-1.15.0-cp27-cp27mu-manylinux1_x86_64.whl
| Collecting html5lib==1.0.1 (from -r src/requirements.txt (line 9))
|   Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
| Collecting httplib2==0.11.3 (from -r src/requirements.txt (line 10))
| Collecting mozprocess==1.0.0 (from -r src/requirements.txt (line 11))
|   Using cached https://files.pythonhosted.org/packages/3f/de/cd2d1831026bff999ee7ee47fe7e2c26f402c9504cdaaa2d20e2f5775966/mozprocess-1.0.0-py2.py3-none-any.whl
| Collecting oauth2client==4.1.3 (from -r src/requirements.txt (line 12))
|   Using cached https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl
| Collecting protobuf==3.6.1 (from -r src/requirements.txt (line 13))
|   Using cached https://files.pythonhosted.org/packages/b8/c2/b7f587c0aaf8bf2201405e8162323037fe8d17aa21d3c7dda811b8d01469/protobuf-3.6.1-cp27-cp27mu-manylinux1_x86_64.whl
| Collecting pytz==2018.5 (from -r src/requirements.txt (line 14))
|   Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
| Collecting PyYAML==4.2b4 (from -r src/requirements.txt (line 15))
| Collecting requests==2.21.0 (from -r src/requirements.txt (line 16))
|   Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
| Collecting urllib3==1.23 (from -r src/requirements.txt (line 17))
|   Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
| Collecting google-auth-httplib2>=0.0.3 (from google-api-python-client==1.7.4->-r src/requirements.txt (line 2))
|   Using cached https://files.pythonhosted.org/packages/33/49/c814d6d438b823441552198f096fcd0377fd6c88714dbed34f1d3c8c4389/google_auth_httplib2-0.0.3-py2.py3-none-any.whl
| Collecting google-auth>=1.4.1 (from google-api-python-client==1.7.4->-r src/requirements.txt (line 2))
|   Using cached https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl
| Collecting six<2dev,>=1.6.1 (from google-api-python-client==1.7.4->-r src/requirements.txt (line 2))
|   Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
| Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client==1.7.4->-r src/requirements.txt (line 2))
|   Using cached https://files.pythonhosted.org/packages/f6/25/66a49231b44409d7f07cfcf2506a8b070ce3c99fc47cc256bea833f24791/uritemplate-3.0.0-py2-none-any.whl
| Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib==0.2.0->-r src/requirements.txt (line 3))
|   Using cached https://files.pythonhosted.org/packages/c2/e2/9fd03d55ffb70fe51f587f20bcf407a6927eb121de86928b34d162f0b1ac/requests_oauthlib-1.2.0-py2.py3-none-any.whl
| Collecting google-cloud-core<0.29dev,>=0.28.0 (from google-cloud-datastore==1.7.0->-r src/requirements.txt (line 4))
|   Using cached https://files.pythonhosted.org/packages/0f/41/ae2418b4003a14cf21c1c46d61d1b044bf02cf0f8f91598af572b9216515/google_cloud_core-0.28.1-py2.py3-none-any.whl
| Collecting google-api-core[grpc]<2.0.0dev,>=1.0.0 (from google-cloud-datastore==1.7.0->-r src/requirements.txt (line 4))
|   Using cached https://files.pythonhosted.org/packages/7d/73/e4877e921fe59307ec6b1b0b0c2ad9fde2d1c6bab8dd06ec913891a20dc6/google_api_core-1.8.2-py2.py3-none-any.whl
| Collecting google-resumable-media>=0.3.1 (from google-cloud-storage==1.13.2->-r src/requirements.txt (line 7))
|   Using cached https://files.pythonhosted.org/packages/e2/5d/4bc5c28c252a62efe69ed1a1561da92bd5af8eca0cdcdf8e60354fae9b29/google_resumable_media-0.3.2-py2.py3-none-any.whl
| Collecting enum34>=1.0.4 (from grpcio==1.15.0->-r src/requirements.txt (line 8))
|   Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
| Collecting futures>=2.2.0 (from grpcio==1.15.0->-r src/requirements.txt (line 8))
|   Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
| Collecting webencodings (from html5lib==1.0.1->-r src/requirements.txt (line 9))
|   Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
| Collecting mozinfo (from mozprocess==1.0.0->-r src/requirements.txt (line 11))
|   Using cached https://files.pythonhosted.org/packages/65/54/7cb1912fcf3f2176616fd17b9afa9665e82918e6a1fcc7b91b1407a602c9/mozinfo-1.0.0-py2.py3-none-any.whl
| Collecting rsa>=3.1.4 (from oauth2client==4.1.3->-r src/requirements.txt (line 12))
|   Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
| Collecting pyasn1>=0.1.7 (from oauth2client==4.1.3->-r src/requirements.txt (line 12))
|   Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
| Collecting pyasn1-modules>=0.0.5 (from oauth2client==4.1.3->-r src/requirements.txt (line 12))
|   Using cached https://files.pythonhosted.org/packages/da/98/8ddd9fa4d84065926832bcf2255a2b69f1d03330aa4d1c49cc7317ac888e/pyasn1_modules-0.2.4-py2.py3-none-any.whl
| Collecting setuptools (from protobuf==3.6.1->-r src/requirements.txt (line 13))
|   Using cached https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl
| Collecting certifi>=2017.4.17 (from requests==2.21.0->-r src/requirements.txt (line 16))
|   Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
| Collecting chardet<3.1.0,>=3.0.2 (from requests==2.21.0->-r src/requirements.txt (line 16))
|   Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
| Collecting idna<2.9,>=2.5 (from requests==2.21.0->-r src/requirements.txt (line 16))
|   Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
| Collecting cachetools>=2.0.0 (from google-auth>=1.4.1->google-api-python-client==1.7.4->-r src/requirements.txt (line 2))
|   Using cached https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
| Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib==0.2.0->-r src/requirements.txt (line 3))
|   Using cached https://files.pythonhosted.org/packages/16/95/699466b05b72b94a41f662dc9edf87fda4289e3602ecd42d27fcaddf7b56/oauthlib-3.0.1-py2.py3-none-any.whl
| Collecting googleapis-common-protos!=1.5.4,<2.0dev,>=1.5.3 (from google-api-core[grpc]<2.0.0dev,>=1.0.0->google-cloud-datastore==1.7.0->-r src/requirements.txt (line 4))
| Collecting mozfile>=0.12 (from mozinfo->mozprocess==1.0.0->-r src/requirements.txt (line 11))
|   Using cached https://files.pythonhosted.org/packages/85/ed/4f8bec5ac04373ef0c79428bdd50ce039e91e4b53660d08e9a45988b74dc/mozfile-2.0.0-py2.py3-none-any.whl
| google-cloud-storage 1.13.2 has requirement google-cloud-core<0.30dev,>=0.29.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
| proto-google-cloud-datastore-v1 0.90.4 has requirement oauth2client<4.0dev,>=2.0.0, but you'll have oauth2client 4.1.3 which is incompatible.
| googledatastore 7.0.1 has requirement httplib2<0.10,>=0.9.1, but you'll have httplib2 0.11.3 which is incompatible.
| googledatastore 7.0.1 has requirement oauth2client<4.0.0,>=2.0.1, but you'll have oauth2client 4.1.3 which is incompatible.
| tensorboard 1.8.0 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.
| bleach 1.5.0 has requirement html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999, but you'll have html5lib 1.0.1 which is incompatible.
| Installing collected packages: backports.lzma, httplib2, cachetools, pyasn1, pyasn1-modules, six, rsa, google-auth, google-auth-httplib2, uritemplate, google-api-python-client, oauthlib, urllib3, certifi, chardet, idna, requests, requests-oauthlib, google-auth-oauthlib, setuptools, protobuf, futures, pytz, googleapis-common-protos, enum34, grpcio, google-api-core, google-cloud-core, google-cloud-datastore, google-cloud-monitoring, google-cloud-profiler, google-resumable-media, google-cloud-storage, webencodings, html5lib, mozfile, mozinfo, mozprocess, oauth2client, PyYAML
| Successfully installed PyYAML-4.2b4 backports.lzma-0.0.13 cachetools-3.1.0 certifi-2019.3.9 chardet-3.0.4 enum34-1.1.6 futures-3.2.0 google-api-core-1.8.2 google-api-python-client-1.7.4 google-auth-1.6.3 google-auth-httplib2-0.0.3 google-auth-oauthlib-0.2.0 google-cloud-core-0.28.1 google-cloud-datastore-1.7.0 google-cloud-monitoring-0.30.1 google-cloud-profiler-1.0.3 google-cloud-storage-1.13.2 google-resumable-media-0.3.2 googleapis-common-protos-1.5.9 grpcio-1.15.0 html5lib-1.0.1 httplib2-0.11.3 idna-2.8 mozfile-2.0.0 mozinfo-1.0.0 mozprocess-1.0.0 oauth2client-4.1.3 oauthlib-3.0.1 protobuf-3.6.1 pyasn1-0.4.5 pyasn1-modules-0.2.4 pytz-2018.5 requests-2.21.0 requests-oauthlib-1.2.0 rsa-4.0 setuptools-40.8.0 six-1.12.0 uritemplate-3.0.0 urllib3-1.23 webencodings-0.5.1
**Running: bower install --allow-root
| Segmentation fault (core dumped)
| Return code is non-zero (139).**
| Exit.

**Comment by inferno-chromium** [comment]
Please provide a backtrace and os used (with version) which might provide us some hints. Do you have bower already installed ? Looks like your bower is crashing, maybe uninstall and reinstall a newer version ?

**Comment by inferno-chromium** [comment]
Can you do this
```
npm cache clean --force
npm install -g bower
```
to see if it fixes your bower.

**Comment by cumtluhuaxing** [comment]
> Can you do this
> 
> ```
> npm cache clean --force
> npm install -g bower
> ```
> to see if it fixes your bower.

thank you，I fixed it follow your methods!

**Comment by inferno-chromium** [comment]
Great, closing.
