### ISSUE TITLE
./build.sh for docker images fails locally because of keyboard-configuration

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3609]
It has an interactive prompt that never resumes even when interacted with.

**Comment by jonathanmetzman** [comment]
https://chromium.googlesource.com/chromium/src/+/main/build/install-build-deps.py seems to have changed.

**Comment by jonathanmetzman** [comment]
@letitz Could someone from your team take a look at this? I don't have the cycles and solving this could help me get untrusted execution sped up (I need to rebuild the images to support image streaming)

**Comment by letitz** [comment]
Would this still be useful? If so, maybe @alhijazi has a couple spare cycles.

**Comment by jonathanmetzman** [comment]
It probably won't be immediately useful (I don't need the speed right now) but it is important we do this. Otherwise we can't rebuild any images.

**Comment by letitz** [comment]
Got it. Filed crbug.com/1520504, we'll look into it.

**Comment by jonathanmetzman** [comment]
Now that the new team members are here, it would be better if they didn't get blocked on this. Could Chrome Fuzzing try to find time for this?

**Comment by letitz** [comment]
Yes, I'll try to look into it tomorrow, or will delegate.
