### ISSUE TITLE
Please revert/fix/or finish https://github.com/google/clusterfuzz/commit/b38691b82ea080c2309588a72f797609779c3de5

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3702]
It's the most common error on ClusterFuzz. As far as I can tell it happens all the time for libFuzzer jobs.
@letitz I think you authored it, could you please look into this.

**Comment by jonathanmetzman** [comment]
Most importantly though, it's making it harder to diagnose actually misbehaving jobs.

**Comment by letitz** [comment]
Looking into b38691b82ea080c2309588a72f797609779c3de5

**Comment by letitz** [comment]
I see two versions of the issue in the most recent samples: https://console.cloud.google.com/errors/detail/CLuEsY-G8c3aaA;service=;version=?project=google.com:clusterfuzz

> Could not find app '' in search directories.
> Could not find app 'd8.exe' in search directories.

I can certainly ignore the error when the app name is empty, that's just silly. Missing `d8.exe` might be pointing to a real error though?
