### ISSUE TITLE
when I run python butler.py run_server,it returns RuntimeError: pubsub emulator did not get ready in time.

### ISSUE THREAD

**Issue by cumtluhuaxing** [google/clusterfuzz#373]
Created symlink: source: /home/clusterfuzz/configs/test, target /home/clusterfuzz/src/appengine/config.
Created symlink: source: /home/clusterfuzz/configs/test, target /home/clusterfuzz/src/go/server/config.
Created symlink: source: /home/clusterfuzz/src/protos, target /home/clusterfuzz/src/appengine/protos.
Created symlink: source: /home/clusterfuzz/src/python, target /home/clusterfuzz/src/appengine/python.
Running: bazel run //local:create_gopath (cwd='src')
| Loading:
| Loading: 0 packages loaded
| Analyzing: target //local:create_gopath (0 packages loaded, 0 targets configured)
| DEBUG: Rule 'org_golang_x_sys' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1538141909 +0000"
| DEBUG: Rule 'org_golang_x_tools' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "2384fa91351a7414b643c5230422ce45f5aa2be8a82727609afd4e64e6973a30"
| DEBUG: Rule 'com_github_golang_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1534281267 -0700"
| DEBUG: Rule 'go_googleapis' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c65fa17dcc40408f0a6d9d1a309e60bf896201be9cd4d09043779fc525fc901c"
| DEBUG: Rule 'org_golang_google_grpc' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1536688131 -0700"
| DEBUG: Rule 'org_golang_x_net' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1537976840 +0000"
| DEBUG: Rule 'org_golang_x_text' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1513256923 +0000"
| INFO: Analysed target //local:create_gopath (0 packages loaded, 0 targets configured).
| INFO: Found 1 target...
| [0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
| Target //local:create_gopath up-to-date:
|   bazel-bin/local/create_gopath
| INFO: Elapsed time: 0.232s, Critical Path: 0.00s
| INFO: 0 processes.
| INFO: Build completed successfully, 1 total action
| INFO: Running command line: bazel-bin/local/create_gopath local/gopath
| INFO: Build completed successfully, 1 total action
| /root/.cache/bazel/_bazel_root/2ad9d25912904b4b1a3186f98d003514/execroot/__main__/bazel-out/k8-fastbuild/bin/local/gopath
Running: python polymer_bundler.py (cwd='local')
| Building templates for App Engine...
| App Engine templates built successfully.
Created symlink: source: /home/clusterfuzz/local/storage/local_gcs, target /home/clusterfuzz/src/appengine/local_gcs.
Traceback (most recent call last):
  File "butler.py", line 286, in <module>
    main()
  File "butler.py", line 260, in main
    command.execute(args)
  File "src/local/butler/run_server.py", line 164, in execute
    data_dir=args.storage_path)
  File "/home/clusterfuzz/src/python/tests/test_libs/test_utils.py", line 279, in start_cloud_emulator
    '{} emulator did not get ready in time.'.format(emulator))
RuntimeError: pubsub emulator did not get ready in time.
(ENV) root@lhx:/home/clusterfuzz# python butler.py run_server

**Comment by inferno-chromium** [comment]
Cannot reproduce this. Looks like you are using a proxy server which we don't support. You will have to debug and find a workaround here.

**Comment by cumtluhuaxing** [comment]
this is because I didn't install jdk

**Comment by inferno-chromium** [comment]
@cumtluhuaxing - please use ./local/install_deps.bash, that should have installed jdk.

**Comment by temp1337temp1337** [comment]
For future reference and macos users, I have faced the same issue while I rejected 'java' from accessing my downloads folder, in order to create a few symlinks as part of the initial setup of the `butler.py` script with the `run_server --bootstrap` options.

The only thing I needed to do to work it around was to go to my system settings and allow this access (duh!)
