### ISSUE TITLE
Error deleting blob

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3744]
@alhijazi Could you PTAL at this: https://pantheon.corp.google.com/errors/detail/CLazj7bz3fjeuwE;filter=%5B%5D;time=P30D?project=google.com:clusterfuzz&e=-13802955&mods=logs_tg_prod

**Comment by alhijazi** [comment]
I am taking a look, thanks!

**Comment by ParisMeuleman** [comment]
This is resolved: we fixed the bot's permissions.
