### ISSUE TITLE
NoneType has no attribute endswith

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3782]
This is an error introduced by https://github.com/google/clusterfuzz/commit/6f9b8429d05eb0ef8b9d272c2f54f9af600948ce in get_supporting_file
See https://pantheon.corp.google.com/errors/detail/CPSb9O-X-oCR_AE;filter=%5B%5D;time=P7D?e=-13802955&mods=logs_tg_prod&project=google.com:clusterfuzz

CC @ParisMeuleman

**Comment by ParisMeuleman** [comment]
Sorry I meant to reply earlier. I'm failing to see how that changeset could introduce this error, this seems quite unrelated?
How did you corelate the two? deployment time? I'm happy to review in more details if you're positive my change introduced this.

**Comment by jonathanmetzman** [comment]
Ah it didn't cause this. I think I meant to link to Paul's (then recent CL).
