### ISSUE TITLE
Support newer versions of Python

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#3809]
The main blocker to this is our dependency on python libraries with C extensions ([e.g. protobuf, grpc)](https://github.com/google/clusterfuzz/blob/master/src/platform_requirements.txt)), and the need to bundle them in  our deployment zips across Linux, Windows, and Mac.

We should see if there's a way for us to set up cross platform build environments (e.g. leveraging GitHub actions) to build the these necessary dependencies into reusable Python wheels.

**Comment by oliverchang** [comment]
@jonathanmetzman wdyt?

**Comment by vitorguidi** [comment]
@oliverchang close?

**Comment by oliverchang** [comment]
Yep!
