### ISSUE TITLE
when I run ./local/install_deps.bash,there is a error but it still returns Installation succeeded in the end.

### ISSUE THREAD

**Issue by cumtluhuaxing** [google/clusterfuzz#388]
Analyzing: target //local:create_gopath (0 packages loaded, 0 targets configured)
| Analyzing: target //local:create_gopath (0 packages loaded, 0 targets configured)
| Analyzing: target //local:create_gopath (0 packages loaded, 0 targets configured)
| Analyzing: target //local:create_gopath (0 packages loaded, 0 targets configured)
| Analyzing: target //local:create_gopath (0 packages loaded, 0 targets configured)
| Analyzing: target //local:create_gopath (0 packages loaded, 0 targets configured)
| ERROR: /root/.cache/bazel/_bazel_root/2ad9d25912904b4b1a3186f98d003514/external/org_golang_x_net/idna/BUILD.bazel:3:1: no such package '@org_golang_x_text//unicode/norm': Traceback (most recent call last):
| 	File "/root/.cache/bazel/_bazel_root/2ad9d25912904b4b1a3186f98d003514/external/bazel_tools/tools/build_defs/repo/git.bzl", line 164
| 		_clone_or_update(ctx)
| 	File "/root/.cache/bazel/_bazel_root/2ad9d25912904b4b1a3186f98d003514/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
| 		fail(("error cloning %s:\n%s" % (ctx....)))
| error cloning org_golang_x_text:
| Timed out; also encountered an error while attempting to retrieve output and referenced by '@org_golang_x_net//idna:go_default_library'
| ERROR: Analysis of target '//local:create_gopath' failed; build aborted: no such package '@org_golang_x_text//unicode/norm': Traceback (most recent call last):
| 	File "/root/.cache/bazel/_bazel_root/2ad9d25912904b4b1a3186f98d003514/external/bazel_tools/tools/build_defs/repo/git.bzl", line 164
| 		_clone_or_update(ctx)
| 	File "/root/.cache/bazel/_bazel_root/2ad9d25912904b4b1a3186f98d003514/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
| 		fail(("error cloning %s:\n%s" % (ctx....)))
| error cloning org_golang_x_text:
| Timed out; also encountered an error while attempting to retrieve output
| INFO: Elapsed time: 1574.724s
| INFO: 0 processes.
| FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
| ERROR: Build failed. Not running target
| FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
| Return code is non-zero (1).
| Exit.

Installation succeeded!
Please load virtualenv environment by running 'source ENV/bin/activate'.

**Comment by inferno-chromium** [comment]
Cannot reproduce this. I injected a sys.exit(1) in butler.py bootstrap and i see script correctly exit without printing install succeeded.

Is "#!/bin/bash -ex" there in your local/install_deps_linux.bash. do you have local modifications in that file that is causing this.
