### ISSUE TITLE
Add new issue trackers based on issue tracker specification

### ISSUE THREAD

**Issue by dukebarman** [google/clusterfuzz#389]
What about another issue trackers? (monorail is only for chromium project) We would like to add support gitlab issues (or trac/Bugzilla), but it's not clear what is the best way to do it. Do you have any plans to add more bug trackers or at least making that part of the code easily extendable?

**Comment by inferno-chromium** [comment]
We currently don't have cycles to add support for other issue trackers. We encourage community contributions here. the package issue_management (https://github.com/google/clusterfuzz/tree/master/src/python/issue_management) should be self-contained and extendable.

**Comment by jonathanmetzman** [comment]
Btw, we would love to support other trackers, so if you'd like to add support we'd be happy to work with you to do so.

**Comment by inferno-chromium** [comment]
The code is totally extendable now - see e.g.monorail dir in https://github.com/google/clusterfuzz/tree/master/src/appengine/libs/issue_management/monorail. this shows how a new tracker can be added based on a generic specification by @oliverchang

**Comment by dukebarman** [comment]
It's nice to hear. Thanks!

**Comment by inferno-chromium** [comment]
@dukebarman - do you want to take a shot at adding gitlab or any other popular issue tracker (jira). let us know if you have any questions.

**Comment by prestonvanloon** [comment]
Any chance for adding github as an issue tracker?

**Comment by oliverchang** [comment]
Unfortunately we're short on cycles for adding GitHub support, but we always welcome contributions :) See https://github.com/google/clusterfuzz/issues/389#issuecomment-659745271 as an example where Jira was added.

**Comment by sfiecko** [comment]
Sorry for returning to this topic after nearly 2 years - Is this PR #1321 a kind of Jira enablement? Can anyone confirm that Jira functionality is working?
