### ISSUE TITLE
Transition from Container Registry

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3913]
We currently are using Google's container registry for critical pieces of our infra:
- clusterfuzz: gcr.io/clusterfuzz-images and an internal one.
- oss-fuzz: gcr.io/oss-fuzz-base: Used for ordinary builds, trial builds and CIFuzz
- fuzzbench: gcr.io/fuzzbench

[Container registry is being shut down March 18th 2025](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr), we need to move artifact registry.

**Comment by jonathanmetzman** [comment]
CC @oliverchang

**Comment by vitorguidi** [comment]
@jonathanmetzman this should be closed right?

**Comment by oliverchang** [comment]
Yep I did this one.
