### ISSUE TITLE
corpus_pruning task needs privileges

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3942]
I think this is for creating the backup.
https://pantheon.corp.google.com/errors/detail/COrmxa-WxN3_kAE;time=P30D?project=google.com:clusterfuzz&utm_source=error-reporting-notification&utm_medium=email&utm_content=new-error

**Comment by jonathanmetzman** [comment]
Revert here: https://github.com/google/clusterfuzz/commit/e9d9f04e0770519a6acf8208375672f3b4204b51

**Comment by alhijazi** [comment]
I will be sending a fix shortly

**Comment by jonathanmetzman** [comment]
I think this is fixed now.
