### ISSUE TITLE
Unable to access clusterfuzz

### ISSUE THREAD

**Issue by bruhdev1290** [google/clusterfuzz#4012]
Hello I’m trying to access clusterfuzz however I’m unable to Im getting this message 
You (email=[planetman1125@gmail.com are not authorized to access this page!

If you reached here via a crbug link, please confirm that you have been manually cc'ed. Otherwise, Please contact [chrome-fuzzing-core@google.com]

I’m currently fuzzing Firefox and want to be able to use the clusterfuzz tool to get better data and find any security vulnerabilities or just hard  to find bugs like null deference

**Comment by jonathanmetzman** [comment]
Which testcase-detail page is this?

**Comment by jonathanmetzman** [comment]
Closing until this receives more feedback
