### ISSUE TITLE
Py2to3: Appengine Memcache alternative

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#405]
As part of Python 3 migration (#183)

As per https://cloud.google.com/appengine/docs/standard/python3/python-differences,

```
Memcache
The Memcache service is not available in Python 3. If you need access to a hosted caching service, you can use a third party memcache service like Redis Labs Cloud.
```

**Comment by oliverchang** [comment]
This was replaced with Cloud Redis in https://github.com/google/clusterfuzz/pull/1194
