### ISSUE TITLE
Upgrade to python3.11

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#4059]
All PRs related to this effort should link here.

**Comment by eduarddfinity** [comment]
Hello clusterfuzz team

do you have an ETA for migrating to python3.11? 
Unfortunately we've been locked out of our clusterfuzz instance since last month, because cross origin redirect login is not supported in firebase. I know this has been fixed in clusterfuzz but we cannot update our instance as app engine no longer allows python3.7 apps to be deployed.

Thanks in advance!

**Comment by oliverchang** [comment]
I'll let @vitorguidi comment in more detail on this, but we are actively working on this upgrade and should hopefully be completing this in the coming weeks / month.

**Comment by vitorguidi** [comment]
> Hello clusterfuzz team
> 
> do you have an ETA for migrating to python3.11? Unfortunately we've been locked out of our clusterfuzz instance since last month, because cross origin redirect login is no longer supported in firebase. I know this has been fixed in clusterfuzz but we cannot update our instance as app engine no longer allows python3.7 apps to be deployed.
> 
> Thanks in advance!

We already have all dependencies bumped, the next step is switching the interpreter and performing a canary with production instances. This should be done next week, and it will be possible to more accurately gauge how complex the process will be, but Oliver's estimate is what I am expecting.

**Comment by vitorguidi** [comment]
#4025 has already been merged and we have been running clusterfuzz in production for >1 week at Python3.11, so it should be good now @eduarddfinity

**Comment by nguyendon** [comment]
@vitorguidi are you all running from a stable release branch or are you just running off of `master`?

**Comment by nguyendon** [comment]
@jonathanmetzman is running off of master just for an internal instance or is that what OSS-Fuzz runs on as well?
