### ISSUE TITLE
Py2to3: Futurize stage 2

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#406]
As part of Python 3 migration (#183)

git ls-files "*.py" | xargs futurize -w -n --stage2 

obviously not as simple. need to be done in steps, and str and unicode fixes are the more tricky ones.

**Comment by inferno-chromium** [comment]
Need to think about these

```
src/local/butler/generate_datastore_models.py:  if py_type == long:
src/python/platforms/android/device.py:  if isinstance(value, long):
```

**Comment by inferno-chromium** [comment]
Remaining ones, probably for Q3 and need to do str-unicode ones more carefully.

libfuturize.fixes.fix_unicode_keep_u
libfuturize.fixes.fix_future_standard_library_urllib (maybe start using requests)
libfuturize.fixes.fix_future_standard_library
libfuturize.fixes.fix_object
libfuturize.fixes.fix_basestring
libfuturize.fixes.fix_future_builtins

**Comment by inferno-chromium** [comment]
Remaining (libfuturize.fixes.fix_object does not seem to be required, except ndb_patcher which is going away):

libfuturize.fixes.fix_unicode_keep_u
libfuturize.fixes.fix_future_standard_library
libfuturize.fixes.fix_basestring
libfuturize.fixes.fix_future_builtins

**Comment by oliverchang** [comment]
i'll tackle the unicode/str conversion

**Comment by inferno-chromium** [comment]
For future, need to careful of any migration change in docker/ dir, example breakage due to https://github.com/google/clusterfuzz/commit/6d9f9e76a1bb37a8c2a5cdd451b14dec4e58dd4a#diff-f1db2c4f1d1b92aef6e74abff3119154 (my bad :() since we don't have future lib during start_host.py time. also got noticed when we updated host image.

**Comment by inferno-chromium** [comment]
Just for tracking, we include everything now except libfuturize.fixes.fix_unicode_keep_u and libfuturize.fixes.fix_future_builtins (these need more work, will come later). minor exclusion is ndb_patcher which will go away soon.

To replicate / reapply fixes, do
git ls-files "*.py" | xargs futurize -w -n --stage2 -x libfuturize.fixes.fix_unicode_keep_u -x libfuturize.fixes.fix_future_builtins

**Comment by oliverchang** [comment]
All the futurize fixes were completed.
