### ISSUE TITLE
Tests time out after 10min, but show "pending" state for much longer than that

### ISSUE THREAD

**Issue by flowerhack** [google/clusterfuzz#409]
The build triggered by "/gcbrun" has a yellow dot next to it for approx. 2 hours after the build is kicked off.  This is even though failure occurs much earlier than that--tests time out after 10min, and it seems like the build should turn red shortly after https://pantheon.corp.google.com/cloud-build/builds/b303e791-63d9-4685-bfd4-24f854635dbc?project=clusterfuzz-testing-public

Would be nice to have this turn red faster; otherwise users get confused about whether a test is failing or just taking a long time.

**Comment by inferno-chromium** [comment]
Are you sure it timed after 10 min, from logs, it looks like

```
Step #3: | Return code is non-zero (-9).
Step #3: Traceback (most recent call last):
Step #3:   File "butler.py", line 286, in <module>
Step #3:     main()
Step #3:   File "butler.py", line 260, in main
Step #3:     command.execute(args)
Step #3:   File "src/local/butler/py_unittest.py", line 291, in execute
Step #3:     run_tests_parallel(args, test_directory)
Step #3:   File "src/local/butler/py_unittest.py", line 205, in run_tests_parallel
Step #3:     results = results.get(timeout=600)
Step #3:   File "/usr/lib/python2.7/multiprocessing/pool.py", line 563, in get
Step #3:     raise TimeoutError
Step #3: multiprocessing.TimeoutError
Finished Step #3
TIMEOUT
ERROR: context deadline exceeded
```
this actually used all of build timeout which is 1.5 hours. test got stuck and didn't get killed until 1.5 hr build timeout.

**Comment by flowerhack** [comment]
I don't know the exact timings, so I could reproduce and try to make sure--I seem to remember seeing a "yellow" icon, and when I clicked through, I saw "TimeoutError" in the logs, but I may have goofed!

**Comment by inferno-chromium** [comment]
Closing, if you see this again, we can reopen.
