### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by nguyendon** [google/clusterfuzz#4156]
Is there a roadmap for a release schedule anywhere / is there some frequency the CF team aims to have releases? `v2.6.0` was released in Feb 2023 so I am wondering what to expect for future releases since development is still fairly active.

**Comment by oliverchang** [comment]
Hi,

Most of our development these days is focused on modernizing and streamlining our infrastructure. We expect a lot of breaking changes for users during this long process, so we won't be making any releases in the meantime. 

This modernization process will likely still take quite a bit of time (at least until 2025).

**Comment by nguyendon** [comment]
Thanks @oliverchang - that's helpful information.
