### ISSUE TITLE
Fix IsADirError

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#4172]
https://pantheon.corp.google.com/errors/detail/CNXapdjsv6uKHQ;filter=%5B%22IsADir%22%5D;time=P1D;locations=global?e=-13802955&invt=AbZefA&mods=logs_tg_prod&project=clusterfuzz-external

It looks like its caused because some testcases are marked archived when they should not be.

**Comment by jonathanmetzman** [comment]
Example: https://pantheon.corp.google.com/datastore/databases/-default-/entities;kind=Testcase;ns=__$DEFAULT$__/edit;key=0%252F%257C8%252FTestcase%257C19%252Fid%253A6195041175928832?e=-13802955&invt=AbZefA&mods=logs_tg_prod&project=clusterfuzz-external

**Comment by jonathanmetzman** [comment]
Older testcases don't have this problem: https://pantheon.corp.google.com/datastore/databases/-default-/entities;kind=Testcase;ns=__$DEFAULT$__/edit;key=0%252F%257C8%252FTestcase%257C19%252Fid%253A5875353648693248?e=-13802955&invt=AbZefA&mods=logs_tg_prod&project=clusterfuzz-external

**Comment by jonathanmetzman** [comment]
Weirdly, this isn't happening in Chrome: https://pantheon.corp.google.com/datastore/databases/-default-/entities;kind=Testcase;ns=__$DEFAULT$__/query/kind;queryModel=2%7CLIM%7C3%2F100%7CWH%7C1%7C7%2F__key__%7CEQ%7CKEY%7C44%2FS2V5KFRlc3RjYXNlLCA0ODI0MTA4NDM5MTA5NjMyKQ..?e=-13802955&invt=AbZefA&mods=logs_tg_prod&project=cluster-fuzz

**Comment by oliverchang** [comment]
We need to fix this: https://github.com/google/clusterfuzz/pull/4137/files#diff-cddf5b1a0c64533064fe09cf6b31fa4a2bdac1e90c0d0347ea76b6131ced6222R923 . I think we just haven't deployed to Chrome for a while?

**Comment by jonathanmetzman** [comment]
It seems to be running in chrome.

**Comment by oliverchang** [comment]
This is fixed right?
