### ISSUE TITLE
CI blocks on lint failures unrelated to current changelist

### ISSUE THREAD

**Issue by flowerhack** [google/clusterfuzz#418]
To run tests in CI you must first pass a lint check.

Unfortunately (I think after https://github.com/google/clusterfuzz/pull/411 ?), a recent change makes this behave too greedily.  Instead of just linting the files that were explicitly touched in the CL, it lints everything that shows up in `git diff --name-only master FETCH_HEAD`.  So, if your CL is at all behind where master is, you'll get extraneous files linted in your diff.

For instance, notice the lint failure in src/python/bot/minimizer/html_tokenizer.py in https://pantheon.corp.google.com/cloud-build/builds/b7c53201-6070-45f1-98fe-3936147662e0?project=clusterfuzz-testing-public , which was generated from this pull request: https://github.com/google/clusterfuzz/pull/398 , despite the fact that that PR did not touch the file at all.

Opinionatedly, I think CI should continue to run even if there's a linting failure (CI doesn't have to *pass*, but it can be helpful to e.g. see if tests seem to pass before resolving all the linting issues).

Less opinionatedly, I think it'd be helpful to return to the previous behavior, where it only linted files that were actually touched by the changelist.

**Comment by inferno-chromium** [comment]
Do these show up after git rebase ?

**Comment by inferno-chromium** [comment]
@flowerhack - ping?

**Comment by inferno-chromium** [comment]
Closing, this shouldn't be issue after rebase.
