### ISSUE TITLE
Fuchsia support

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#421]

**Comment by oliverchang** [comment]
creating a tracking bug for work here :) 

@nopsledder

**Comment by inferno-chromium** [comment]
@flowerhack - can you check why bot/resources/fuchsia/README.md is modified after running one iteration of tests. just creates pain as the diff becomes part of new cls.

**Comment by flowerhack** [comment]
ahh!  sorry, i only just now saw this comment. will stay more on top of Github issues in the future.

pushed a fix there: https://github.com/google/clusterfuzz/pull/486

**Comment by inferno-chromium** [comment]
Code changes can be seen here - https://github.com/google/clusterfuzz/commits/master/src/python/platforms/fuchsia

**Comment by inferno-chromium** [comment]
i think this is done.
