### ISSUE TITLE
Triage and cleanups on instance fuzzing internal code (not chrome) is still running on App Engine

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#4249]
On chrome clusterfuzz it was migrated to k8s. We should do this.
@vitorguidi Can you take this one?

**Comment by oliverchang** [comment]
Do you mean the Google instance? That needs to stay on App Engine because of the way issue tracker creds are obtained. We'd have to figure out an alternative for that if we migrate to k8s.

**Comment by jonathanmetzman** [comment]
Ah, makes sense.
