### ISSUE TITLE
Check for chrome version before installing chromedriver

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#426]
Chromedriver releases are now based on Chrome versions.

**Comment by inferno-chromium** [comment]
Have talked to dev at length. There is no easy way to determine chrome version in a cross platform way. So, we will just continue to rely on gs://chromedriver/LATEST_RELEASE file. We just hope that all devs will have latest stable release of chrome to run js_unittest or stable-1 and hope that things just work there.
