### ISSUE TITLE
workspace and requirements updates

### ISSUE THREAD

**Issue by kkuehl** [google/clusterfuzz#449]
git clone https://github.com/google/clusterfuzz
cd clusterfuzz
git checkout tags/1.2.0
local/install_deps.bash

| ERROR: google-cloud-storage 1.13.2 has requirement google-cloud-core<0.30dev,>=0.29.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
| ERROR: google-cloud-firestore 1.1.0 has requirement google-cloud-core<0.30dev,>=0.29.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
| ERROR: bleach 1.5.0 has requirement html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999, but you'll have html5lib 1.0.1 which is incompatible.
| ERROR: tensorboard 1.8.0 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.
| ERROR: proto-google-cloud-datastore-v1 0.90.4 has requirement oauth2client<4.0dev,>=2.0.0, but you'll have oauth2client 4.1.3 which is incompatible.
| ERROR: googledatastore 7.0.1 has requirement httplib2<0.10,>=0.9.1, but you'll have httplib2 0.11.3 which is incompatible.
| ERROR: googledatastore 7.0.1 has requirement oauth2client<4.0.0,>=2.0.1, but you'll have oauth2client 4.1.3 which is incompatible.

To fix those errors, I had to modify src/requirements.txt 
The next error encountered:
| Loading:
| Loading: 0 packages loaded
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:21:1: file '@bazel_gazelle//:deps.bzl' does not contain symbol 'go_repository'
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:26:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:32:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:38:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:44:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:50:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:56:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:62:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:68:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:74:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:80:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: /home/kkuehl/fuzzing/clusterfuzz/src/WORKSPACE:86:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
| ERROR: Error evaluating WORKSPACE file
| ERROR: Skipping '//local:create_gopath': error loading package 'external': Package 'external' contains errors

Here are my fixes:
```
From 77dc7042d5e7d03bbc06ce2b196d7b0080b2dc01 Mon Sep 17 00:00:00 2001
From: Kirby Kuehl <kkuehl@gmail.com>
Date: Mon, 6 May 2019 10:49:11 -0700
Subject: [PATCH] Fix Errors

---
 src/WORKSPACE        | 38 +++++++++++++++++++++++++++-----------
 src/requirements.txt |  9 +++++----
 2 files changed, 32 insertions(+), 15 deletions(-)

diff --git a/src/WORKSPACE b/src/WORKSPACE
index ab16061..58637eb 100644
--- a/src/WORKSPACE
+++ b/src/WORKSPACE
@@ -1,26 +1,42 @@
 load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
-
 http_archive(
     name = "io_bazel_rules_go",
-    sha256 = "7be7dc01f1e0afdba6c8eb2b43d2fa01c743be1b9273ab1eaf6c233df078d705",
-    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.5/rules_go-0.16.5.tar.gz"],
+    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.3/rules_go-0.18.3.tar.gz"],
+    sha256 = "86ae934bd4c43b99893fc64be9d9fc684b81461581df7ea8fc291c816f5ee8c5",
 )
-
 http_archive(
     name = "bazel_gazelle",
-    sha256 = "6e875ab4b6bf64a38c352887760f21203ab054676d9c1b274963907e0768740d",
-    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.15.0/bazel-gazelle-0.15.0.tar.gz"],
+    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
+    sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
 )
+load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
+go_rules_dependencies()
+go_register_toolchains()
+load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
+gazelle_dependencies()
+#load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
 
-load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
+#http_archive(
+#    name = "io_bazel_rules_go",
+#    sha256 = "7be7dc01f1e0afdba6c8eb2b43d2fa01c743be1b9273ab1eaf6c233df078d705",
+#    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.5/rules_go-0.16.5.tar.gz"],
+#)
 
-go_rules_dependencies()
+#http_archive(
+#    name = "bazel_gazelle",
+#    sha256 = "6e875ab4b6bf64a38c352887760f21203ab054676d9c1b274963907e0768740d",
+#    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.15.0/bazel-gazelle-0.15.0.tar.gz"],
+#)
 
-go_register_toolchains()
+#load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
+#
+#go_rules_dependencies()
 
-load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
+#go_register_toolchains()
 
-gazelle_dependencies()
+#load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
+
+#gazelle_dependencies()
 
 # Google Cloud client libraries.
 go_repository(
diff --git a/src/requirements.txt b/src/requirements.txt
index 62aa8a9..db0fb87 100644
--- a/src/requirements.txt
+++ b/src/requirements.txt
@@ -1,17 +1,18 @@
 backports.lzma==0.0.13
 firebase-admin==2.16.0
 future==0.17.1
+google-cloud-core==0.29.1
 google-api-python-client==1.7.4
 google-auth-oauthlib==0.2.0
-google-cloud-datastore==1.7.0
+google-cloud-datastore==1.7.2
 google-cloud-monitoring==0.30.1
 google-cloud-profiler==1.0.3
 google-cloud-storage==1.13.2
 grpcio==1.15.0
-html5lib==1.0.1
-httplib2==0.11.3
+html5lib==0.9999999
+httplib2==0.9.2
 mozprocess==1.0.0
-oauth2client==4.1.3
+oauth2client==3.0.0
 protobuf==3.6.1
 pytz==2018.5
 PyYAML==5.1
-- 
```

**Comment by inferno-chromium** [comment]
It was fixed in https://github.com/google/clusterfuzz/commit/5cd2710bec05b652d6c90aed6adcb075ae7f232a, let me just release a new version.

**Comment by inferno-chromium** [comment]
Please use latest release 1.2.1 https://github.com/google/clusterfuzz/releases/tag/1.2.1
