### ISSUE TITLE
CI bot is failing as it cannot access the test bucket

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#460]
See the log from https://pantheon.corp.google.com/cloud-build/builds/0ecf0a22-ebd5-449e-80e5-52a6f9d07287?project=clusterfuzz-testing-public

**Comment by Dor1s** [comment]
I'm trying to rerun, maybe that was just an occasional flakiness.

**Comment by inferno-chromium** [comment]
Seems fixed now.
