### ISSUE TITLE
Blackbox fuzzer generates testcases, but shows Generates 0/X testcases in results.

### ISSUE THREAD

**Issue by haxmeadroom** [google/clusterfuzz#479]
A blackbox fuzzer successfully runs and generates `no_of_files` testcases as seen from the log.  For some reason, the results under Fuzzers shows `Generated 0/20 testcases.`

![image](https://user-images.githubusercontent.com/29556072/58195514-f9c90300-7c7c-11e9-9583-e43ab26b036d.png)

Fuzzing does not start and as far as I can tell, the jobs are never executed.  This is with version 
`commit c18cea06ab485b8f6817f5b4cfbeb83f54e4799b (HEAD, tag: 1.2.1)`

**Comment by inferno-chromium** [comment]
The filenames need to have 'fuzz-' as filename prefix for testcases. if it is not there, then ClusterFuzz won't count it and won't know which ones to fuzz against.

**Comment by inferno-chromium** [comment]
Thanks for reporting this, we should have mentioned this explicitly in docs. Now did it.
