### ISSUE TITLE
Unit tests don't display logs.log messages, even when they are run with the -u flag

### ISSUE THREAD

**Issue by flowerhack** [google/clusterfuzz#485]
For instance, run:

`python butler.py py_unittest -t core -v -u -p build_manager_test.py`

Based off the content of those tests, you'd expect messages like "Build already exists" and "Retrieved build foo" to appear.  But no such messages appear.

You can work around this by converting logs.log calls to print statements, but ideally we'd like it to be possible to view logs during unit testing.

**Comment by inferno-chromium** [comment]
I have a fix for this.

**Comment by flowerhack** [comment]
Thanks for this!
