### ISSUE TITLE
Files reading using the "with open" syntax.

### ISSUE THREAD

**Issue by farziengineer** [google/clusterfuzz#495]
https://github.com/google/clusterfuzz/blob/2591c16e5b20db4425cb3ab78bafea8ce7f23d6d/src/python/fuzzer_utils/tests.py#L37-L39

https://github.com/google/clusterfuzz/blob/2591c16e5b20db4425cb3ab78bafea8ce7f23d6d/src/python/fuzzer_utils/tests.py#L70-L72

https://github.com/google/clusterfuzz/blob/6d9f9e76a1bb37a8c2a5cdd451b14dec4e58dd4a/src/python/system/environment.py#L712-L714

The above two snippets can be replaced with 
```python
with open("filename", mode) as f:
 ...
```

> The with statement handles opening and closing the file, including if an exception is raised in the inner block. 
. Read [here](https://stackoverflow.com/a/8010133/8577285)

Can I raise a PR for the above.

**Comment by inferno-chromium** [comment]
Sure, go ahead and send a PR for this.

**Comment by inferno-chromium** [comment]
closed in https://github.com/google/clusterfuzz/pull/528
