### ISSUE TITLE
How to handle a large corpus that we cannot rsync to disk

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#507]
When discussing issue #462 with @inferno-chromium, another problem came up. When a target's corpus becomes too huge, we may be unable to rsync it to the disk ever. How should we handle that?

One idea is to delete the corpus and use the latest backup, but that sounds kinda disruptive and we'll also have to track and count the failures somehow prior to doing that hard reset.

**Comment by inferno-chromium** [comment]
Just fyi, this isn't a major problem atm, i only saw this issue with compositor_frame_fuzzer on internal.

**Comment by inferno-chromium** [comment]
This worked to fix compositor_frame_fuzzer. 

@oliverchang fyi - 30K files take like an hour to delete. Since this is not a recurring occurence i am not spending time to optimize this. If you have immediate ideas to implement, i can try, but closing for now.
