### ISSUE TITLE
some old reproducible bugs are not auto-filed

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#523]
e.g.
https://clusterfuzz.com/testcases?issue=no&open=yes&page=4&project=chromium&reproducible=yes
https://oss-fuzz.com/testcases?issue=no&open=yes&page=4&reproducible=yes
https://bugs.chromium.org/p/chromium/issues/detail?id=969499

**Comment by inferno-chromium** [comment]
actually the issue is similar bug with that crash are still open. we lose the group_bug_information mapping, that seems like a issue.

**Comment by Dor1s** [comment]
Other examples are:
- https://oss-fuzz.com/testcase-detail/5642897908563968
- https://oss-fuzz.com/testcase-detail/5082243548053504

from https://oss-fuzz.com/testcases?project=rapidjson&open=yes

**Comment by inferno-chromium** [comment]
@Dor1s for rapidjson, i found the culprit - https://github.com/google/oss-fuzz/commit/a3c935fe9ca7f82bafa520731525e1cc38acf650 :)

**Comment by Dor1s** [comment]
Thanks @inferno-chromium, good to know! :)

**Comment by inferno-chromium** [comment]
Should be fixed with the two fixes above.
