### ISSUE TITLE
Move issue updates to appengine cron.

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#541]

**Comment by inferno-chromium** [comment]
This is needed for Google Issue Tracker integration (https://developers.google.com/issue-tracker/), so that all updates go through appengine and we don't need to do these from GCE.

**Comment by inferno-chromium** [comment]
@oliverchang - i think for progression task, we can just remove the issue comment code completely. See cleanup.mark_issue_as_closed_if_testcase_is_fixed, i think we do double update which might be not needed. we can just add the range in the message in cleanup function and then progression task one can go away. wdyt ? 

Rest, should be handled by my cl above.

**Comment by oliverchang** [comment]
having a single update SGTM.
