### ISSUE TITLE
Reproduce found crashes on other job types / platforms / sanitizers

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#565]
See also https://github.com/google/oss-fuzz/issues/775

**Comment by inferno-chromium** [comment]
See also cross job deduplication and other improvements - https://bugs.chromium.org/p/chromium/issues/detail?id=787078

**Comment by inferno-chromium** [comment]
See also
https://bugs.chromium.org/p/chromium/issues/detail?id=950353

**Comment by jonathanmetzman** [comment]
A possible example of a bug that ASAN reports incorrectly: crbug.com/976429

**Comment by Dor1s** [comment]
Another potential benefit here is that for crashes found e.g. on Android, we might prefer reproducing and reporting on Linux, if possible.

**Comment by inferno-chromium** [comment]
Started - https://github.com/google/clusterfuzz/commit/08cbad1c5b655356003327c166098124bd982c27

**Comment by inferno-chromium** [comment]
Will be evaluating results first, fixing exceptions. And then do a CL to show in UI. Also, need to exclude cases to avoid cpu wastage.

**Comment by inferno-chromium** [comment]
Exception fix list
- https://github.com/google/clusterfuzz/commit/0ad2cb40bafe3a849dd989f3cddd68dc2d6bef64
- https://github.com/google/clusterfuzz/commit/00224d652c03b686cdf2fa7524d30089a4322b4b
- https://github.com/google/clusterfuzz/commit/db17ff45b081b398c09bd7ee12f978c67586eed8
- https://github.com/google/clusterfuzz/commit/db4f12d0a62bdead8960438f86d70655f1c84e82

**Comment by inferno-chromium** [comment]
Should be done. Many more fixes went in, forgot to associate them all to this.
