### ISSUE TITLE
Fuzzer Stats are loading incorrectly, ignoring CoverageInformation entities from Datastore

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#577]
See also https://bugs.chromium.org/p/chromium/issues/detail?id=952995
Assigning to current sheriff if he gets cycles.

**Comment by Dor1s** [comment]
Didn't get a chance to look at this during my rotation and afterwards, assigning for now.

It also seems to be not super reliable. E.g. right now I'm getting all the stats correctly: https://clusterfuzz.com/fuzzer-stats/by-fuzzer/fuzzer/libFuzzer/job/libfuzzer_chrome_asan

So I keep blaming caching, and suggest us to keep this issue open just in case we'll be able to catch a good reproducing moment / condition.

**Comment by inferno-chromium** [comment]
Seems ok now.
