### ISSUE TITLE
Refactor launcher tests for better readability and maintainability 

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#594]
In #581 and #583 @jonathanmetzman has pointed out that our current tests for launchers (and probably some other stuff) are quite redundant and annoying to add / update. Replacing the large `AssertEqual` e.g. for stats with `AssertIn` might be one relatively simple but nice improvement.

Also many tests are asserting the same things again and again, maybe those items could be moved into separate test(s), and the rest will be focused on their specific feature (i.e. strategy tests just verify the strategy, not need to assert the whole output equivalence).

I suspect this might be a good task to tackle during fuzzing engine plugability work, as the test might be affected by the new interface development anyway.

**Comment by Dor1s** [comment]
Another issue pointed out in #583 is that we have a ton of literal strings (file file paths, etc) that are repeated many times across the same test file.

Also many tests are using the `@mock.patch@` decorators for the same functions. Maybe we can group tests better so that patching is done once in the `setUp` method.

Minijail assertions are also duplicated and possibly could be specified in a single helper or reduced to shorter assertions that would test only the test specific values.

**Comment by inferno-chromium** [comment]
I think this is already done by @oliverchang , please close if done.
