### ISSUE TITLE
When the same crash is found on a new platform, we should post link on the bug

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#617]
https://bugs.chromium.org/p/chromium/issues/detail?id=973508 was initially found on Android, but turned out to be hard to reproduce.

Later on, CF found another reproducer on Linux. If we linked the testcase details page for the Linux crash, when we update the OS label, the but could get more traction as reproducing on Linux is much easier.

**Comment by Dor1s** [comment]
Assigning to myself, but feel free to steal / WontFix if it seems to be a bad idea.

**Comment by inferno-chromium** [comment]
Problem is we don't create new testcases for duplicates, just log entry in crash stats. maybe we do need to create on if it is different platform (maybe different sanitizer even, job feels like it will explode the num of testcases). Needs to be brainstormed together with https://github.com/google/clusterfuzz/issues/565.

**Comment by Dor1s** [comment]
Unassigning myself for now.

**Comment by inferno-chromium** [comment]
This is done in variant task with link to testcase added.
