### ISSUE TITLE
Improve page load performance

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#618]
Pages can take ~10 seconds to load sometimes. Investigate why and optimize this.

**Comment by inferno-chromium** [comment]
Added this as an okr item. Internal instance is resolved. We can keep this open to track general testcase-list and testcase-detail loading pains.

**Comment by inferno-chromium** [comment]
@oliverchang already did a bunch, here are some more

https://github.com/google/clusterfuzz/pull/653 - remove /testcases redirect
there is another issue i see on testcase details which is it makes 2 heavy blob size calls to get fuzzed and minimized size every time.

**Comment by inferno-chromium** [comment]
Average load time decreased from 7 sec (avg apr1-aug4) to 3 sec (jul15-aug4). Closing. As per @Dor1s , sometimes initially a few page take like 7-8 sec. I cannot reproduce it, e.g. https://clusterfuzz.com/testcase-detail/5741708005736448 too like 3.38 sec.
