### ISSUE TITLE
Permissions not working for /testcases?

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#635]
One user reported to me that they couldn't access the list of testcases for vtest_fuzzer even though I gave them permission on the configuration page. Here is a screenshot of what they saw instead:
![image](https://user-images.githubusercontent.com/31354670/60556244-39135680-9cf5-11e9-9662-4c6834c5f597.png) When I go to that page I see a list of testcases.

Note that this screenshot shows an error on my part, I accidentally granted permission for vtest_fuzzer instead of libFuzzer_chromeos_vtest_fuzzer. I corrected this mistake, but the user still says they can't access any of the testcases.

**Comment by inferno-chromium** [comment]
Verified with a gmail account, this happen when user is trying to access security bugs added on config page. Two bugs
- Testcases list is not working
- Testcase detail page is not working for overridden fuzzers (e.g. libfuzzer, afl)

**Comment by inferno-chromium** [comment]
Should be fixed.

**Comment by inferno-chromium** [comment]
And now the fuzzer filter is broken since it needs lower names.

**Comment by inferno-chromium** [comment]
Phew fixed!

**Comment by jonathanmetzman** [comment]
Thanks everyone!
