### ISSUE TITLE
Stats messup

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#640]
https://oss-fuzz.com/fuzzer-stats/by-day/date-start/2019-06-01/date-end/2019-07-02/fuzzer/libFuzzer_arduinojson_json_fuzzer/job/libfuzzer_asan_arduinojson

no tests executed, no avg_exec_per_sec. regressed around Jun 26-27

**Comment by inferno-chromium** [comment]
Guessing https://github.com/google/clusterfuzz/pull/606
@mukundv-chrome ?

**Comment by inferno-chromium** [comment]
No stats on internal after June 28 - https://clusterfuzz.com/fuzzer-stats/by-day/date-start/2019-06-01/date-end/2019-07-02/fuzzer/libFuzzer_ax_table_fuzzer/job/libfuzzer_chrome_asan

**Comment by Dor1s** [comment]
This seems to be resolved by our collective effort. The other outstanding issue is #643 which is libFuzzer specific.
