### ISSUE TITLE
"Failed to set up a build." error

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#642]
e.g. https://pantheon.corp.google.com/errors/CIqbiIa8_JXeDA?time=P7D&project=google.com:clusterfuzz&organizationId=433637338589

This is not necessarily a breakage. I think we just ignored the failure previously, this error was added in https://github.com/google/clusterfuzz/commit/f09f17e53b2e1d26853124b4777e33e7ec5dbde8#diff-0454c916ab182c79b11e88ed57c6e3b1L1170

But can also be that something has regressed, of course.

**Comment by inferno-chromium** [comment]
This was a good catch, we were exceptioning out in

```
Exception occurred in function <function store_file_in_cache at 0x7fc0cbf50578>: args: ('/mnt/scratch0/clusterfuzz/bot/builds/chromium-browser-ubsan_linux-release-vptr_4fef60c0a7f4af06cd176068e87ecd9cc70321d1/revisions/ubsan-vptr-linux-release-674669.zip',), kwargs: {} exception: [Errno 2] No such file or directory: '/mnt/nfs/cfvolume/cache/11abd02bcce65c0c8088a4d67df51b5736a056de/ubsan-vptr-linux-release-674646.zip' Traceback (most recent call last): File "/mnt/scratch0/clusterfuzz/src/python/base/utils.py", line 732, in _wrapper return async_result.get(timeout=duration) File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get raise self._value OSError: [Errno 2] No such file or directory: '/mnt/nfs/cfvolume/cache/11abd02bcce65c0c8088a4d67df51b5736a056de/ubsan-vptr-linux-release-674646.zip'
```

**Comment by inferno-chromium** [comment]
actually a real bug, fix coming.

**Comment by inferno-chromium** [comment]
This is now fixed with https://github.com/google/clusterfuzz/commit/f2fa7453af092f1f0477d0d568e1141250d18dba
