### ISSUE TITLE
local/install_deps.bash fails on Rodete Linux due to missing docker-ce package

### ISSUE THREAD

**Issue by 1Project** [google/clusterfuzz#649]
Dependencies fail to install on Rodete Linux for me:
```bash
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
```
Manually installing `docker-ce-rodete` repo fixes it for me, I wonder if a bash script needs to be updated to accomodate for that.

**Comment by inferno-chromium** [comment]
Thanks for the report, yes we missed this step from the wiki.
