### ISSUE TITLE
V8 assertion failures starting with "[disabled] " are not being parsed

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#664]
I recall @jonathanmetzman asking about this recently, also V8 team reported this issue last week: https://bugs.chromium.org/p/chromium/issues/detail?id=980891#c11

Testcase example (with empty crash signature): https://clusterfuzz.com/testcase-detail/5918207076859904

Here's the regexp that needs to be updated: https://github.com/google/clusterfuzz/blob/e4e26f03597ace0a13311ffd4974e5138aa3f9f3/src/python/crash_analysis/stack_parsing/stack_analyzer.py#L213

Should be a simple fix, the only question is whether we want to report such crashes or ignore them? //cc @hammacher to advise.

**Comment by inferno-chromium** [comment]
this looks like a regex issue and should be supported. at that time, we didn't have this example. @hammacher - you can propose a fix as well, see regex and a needed test here :) - https://github.com/google/clusterfuzz/blob/master/src/python/tests/core/crash_analysis/stack_parsing/stack_analyzer_test.py#L801

**Comment by hammacher** [comment]
Aha, now I understand better what is going on here. I assumed that the "[disabled] " prefix was somehow produced by ClusterFuzz. But it's generated because of the --disable-abortjs flag.
In this case, I would actually propose to fix this differently, see https://crbug.com/v8/9453.

**Comment by Dor1s** [comment]
Sounds good! Thanks, @hammacher.
