### ISSUE TITLE
OSS-Fuzz issues are being assigned to "a_deleted_user"

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#667]
See [these bugs](https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=+-status%3DDuplicate%2CWontFix+opened%3E2019-07-01+opened%3C2019-07-31&sort=-owner&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary) for example.

**Comment by jonathanmetzman** [comment]
I think this started happening some time after July 2nd

**Comment by jonathanmetzman** [comment]
Assigning to current sheriff.

**Comment by mbarbella-chromium** [comment]
Didn't see any obvious changes on the ClusterFuzz side that could have caused this. I'll take a closer look if the Monorail team doesn't have any ideas on https://bugs.chromium.org/p/monorail/issues/detail?id=5901

**Comment by inferno-chromium** [comment]
Thanks for fixing - https://github.com/google/clusterfuzz/commit/c38221849be002da3c710a05c4fe73324e3caaaf
