### ISSUE TITLE
bot.log without error info when start exe with error

### ISSUE THREAD

**Issue by lion-roadbike** [google/clusterfuzz#670]
Hello, my program failed to start in the clusterfuzz machine, for example:
```
root@23ff1a43df93:/clusterfuzz/mytestdir# ./mytest_fuzzer 
./mytest_fuzzer: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

But there is no error message in the bot.log, so it is hard to find this startup failure problem.

clusterfuzz version: tags/1.2.1

**Comment by inferno-chromium** [comment]
The fuzzing logs are too big to store in bot.log itself, so they are stored in another directory (local) / gcs (remote). See test-fuzz-logs-bucket in https://github.com/google/clusterfuzz/blob/master/configs/test/project.yaml#L86

If you are running locally,
look at <clusterfuzz-dir>/local/storage/local_gcs/test-fuzz-logs-bucket
If you are running in production
look at gcs://<value of FUZZ_LOGS_BUCKET env var in project.yaml in your config-dir>
