### ISSUE TITLE
FIND SIMILAR ISSUES provides links that do not work with Monorail

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#694]
For example:

1) go to https://clusterfuzz.com/testcase-detail/5076520674131968

2) click FIND SIMILAR ISSUES: ALL

3) try to open any of the similar issues, I'm getting HTTP 400 error

**Comment by inferno-chromium** [comment]
Works for me, can you retry.

**Comment by Dor1s** [comment]
Yes, I'm still getting 400 error when I click on any of the bugs. I guess it might've been unclear in my initial report that the error comes from Monorail when you click on a bug number provided by ClusterFuzz. The "FIND SIMILAR ISSUES: ALL" button itself works fine.

**Comment by inferno-chromium** [comment]
Yes, the hyperlink is wrong. instead of id, it is issue json itself, should be an easy fix, should assigning to you :)

**Comment by Dor1s** [comment]
Fixed in https://github.com/google/clusterfuzz/commit/89cbed491db3d61341077907d8e78969520fbc96
