### ISSUE TITLE
Some blackbox fuzzers are failing because of empty `files.info`

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#722]
e.g. https://console.cloud.google.com/errors/CPHKm8uOk_iNUg?time=P1D&project=clusterfuzz-experimental&organizationId=433637338589

**Comment by Dor1s** [comment]
Not sure why this is happening, taking a closer look.

**Comment by Dor1s** [comment]
Started to happen ~7 hours ago, doesn't seem related to any code changes.

**Comment by Dor1s** [comment]
Something's wrong with `/mnt/nfs/cfvolume/common/pdf`.

**Comment by Dor1s** [comment]
Hm, just SSH'ed into one of the bots, looks totally fine...

```
# cat /mnt/nfs/cfvolume/common/pdf/files.info | head -n 10
1.pdf
10.pdf
100.pdf
1000.pdf
1001.pdf
1002.pdf
1003.pdf
1004.pdf
1005.pdf
1006.pdf
```

**Comment by inferno-chromium** [comment]
Could be NFS flake that goes away. lets wait for a few more hours.

**Comment by Dor1s** [comment]
Ack!

**Comment by Dor1s** [comment]
> Could be NFS flake that goes away. lets wait for a few more hours.

You're right!
