### ISSUE TITLE
Create testcase for fuzz target startup crash without sanitizer stack

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#741]
This could just have a crash type - "Startup-crash", and crash state - "fuzz_target_name", similar to oom and timeout cases.

**Comment by Dor1s** [comment]
Ideally, we don't want such test targets to be uploaded at all, but since this happens from to to time, I think it makes sense. Would it work for bad builds in case of black box fuzzers?

**Comment by inferno-chromium** [comment]
You bring an interesting point.

So, bad build detection helps to prevent bad targets from being used at all, but does cannot be used to file a bug (since you need to fuzz with it once). It only works on blackbox stuff right now.

I am still thinking how to take care of both problems. we do want regression testing to find culprit. but ideally we want to ignore that build/target as well.

**Comment by inferno-chromium** [comment]
need to wait on fuzzing engine refactoring to atleast get enabled. right now, code modifications can create more confusion and might even get dropped out in refactoring.

**Comment by inferno-chromium** [comment]
We capture startup crashes but only for things we have signature for. This covers missing library crashes, check failures. We can't just create startup crash for everything.
