### ISSUE TITLE
Support HELP_TEMPLATE or something similar 

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#761]
To be used as a message for displaying reproduction instructions.

With support for substituting in testcase ID, fuzz target names etc.

**Comment by oliverchang** [comment]
@mbarbella-chromium assigning to you as discussed, thanks :)

**Comment by inferno-chromium** [comment]
i can think of
* testcase id
* fuzz target name (without libfuzzer_)
* engine name
