### ISSUE TITLE
Show fuzz target + engine on testcase details instead of fully qualified fuzzer name.

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#781]
This seems especially important when the fully qualified name is long and after normalizing. 

Right now, on the testcase details page, we will show:

```
Fuzzer: libFuzzer_a-b-c-d-e-fuzzer
```
( where a-b-c-d-e is the normalized project name)

Proposed change:
```
Engine: libFuzzer
Target: fuzzer
```

We can still link to the testcase list page with the full libFuzzer_a-b-c-d-e-fuzzer filter on the "fuzzer" text.

**Comment by oliverchang** [comment]
Similarly, we should do this for our issue report format also.

**Comment by inferno-chromium** [comment]
I will do this first thing tmrw.
