### ISSUE TITLE
REVISION_VARS_URL is unused.

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#793]
The only reference is revisions.get_src_map, which is dead code. It's also mentioned in our docs in build_pipeline.md

We should keep REVISION_VARS_URL though, and remove revision_vars_url from data_types.Config. We can set a default value in the project.yaml env section and get the value via data_handler.get_value_from_job_definition_or_environment

**Comment by inferno-chromium** [comment]
We have to migrate existing jobs on https://clusterfuzz.com/configuration first.

**Comment by inferno-chromium** [comment]
revision_vars_url in data_types.Config is used for chromium deps link per job, you mean just move them to job definition itself, and then remove it from config.

**Comment by oliverchang** [comment]
Yep, we added REVISION_VARS_URL to jobs a while back, but it looks like it became stale and unused. It seems like a better way to define such a thing compared to the job;value format on /configuration.
