### ISSUE TITLE
Cap file sizes when using radamsa/other mutators.

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#810]
Seeing some exceptions on a target which has an input that is 100s of MBs in size.

**Comment by Dor1s** [comment]
Wow, should we completely forbid such long inputs?

ML RNN mutator uses the length of the existing corpus items, so it shouldn't produce anything longer than that. Radamsa can, I guess.

**Comment by inferno-chromium** [comment]
4-4.5 mb of files in seed corpus for this target.

**Comment by inferno-chromium** [comment]
it just fills up that 10 gb of tmpfs quickly.

**Comment by inferno-chromium** [comment]
Lets wait on this - https://github.com/google/clusterfuzz/pull/814 before trying a fix since this code is all getting moved. i am fine with per-file limit or overall corpus size limit or something smart like shell.get_free_disk_space(path) and then break out of loop.

**Comment by Dor1s** [comment]
Just remembered that ML RNN has explicit limit of 10K bytes per input https://github.com/google/clusterfuzz/blob/6d9f9e76a1bb37a8c2a5cdd451b14dec4e58dd4a/src/python/bot/fuzzers/ml/rnn/generate.py#L40
