### ISSUE TITLE
Speedup radamsa using in-process custom mutator

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#817]
See documentation https://gitlab.com/akihe/radamsa
we shouldn't be generating one-by-one, just fire it at once.

path
write to files, %n is testcase # and %s the first suffix
$ radamsa -o test-%n.%s -n 100 samples/*.foo

**Comment by inferno-chromium** [comment]
ah, cant do since we dont have one input file but a bunch of them and we pick them at random. maybe can generate a bunch of them per input file, instead of one.

**Comment by inferno-chromium** [comment]
Using an in-process custom mutator should be thing to try as per discussion.

**Comment by Dor1s** [comment]
Do we want to close this? @mbarbella @mpherman2

**Comment by mbarbella-chromium** [comment]
Yeah, good catch.
