### ISSUE TITLE
Add %ARGS% to HELP_FORMAT

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#819]

**Comment by oliverchang** [comment]
Probably also %SANITIZER_OPTIONS%

**Comment by inferno-chromium** [comment]
ARGS needs some cleanup before actual use. in this case, we need to always strip %TESTCASE% and fuzzer name as these arguments are the ones passed to launcher.
"%TESTCASE% yaml_fuzzer -timeout=25 -rss_limit_mb=2048"
