### ISSUE TITLE
Google Group is Private?

### ISSUE THREAD

**Issue by SecurityInsanity** [google/clusterfuzz#958]
When clicking the link on the clusterfuzz repo page (which takes you to: <https://groups.google.com/forum/#!forum/clusterfuzz-announce> ). Results in:

```This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.```

I get this when logged into my work email, personal email, or incognito. Is there a public place for announcements, or am I perhaps doing something incorrect here?

**Comment by inferno-chromium** [comment]
Should be fixed now, but we havent done any annoucements so far. All releases and details can be seen on https://github.com/google/clusterfuzz/releases
